refresh materialized view rst.recreation_resource_access_count_view;
refresh materialized view rst.recreation_resource_district_count_view;
refresh materialized view rst.recreation_resource_type_count_view;
refresh materialized view rst.recreation_resource_search_view;
