repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: (^charts/.*/templates/)
        args: ["--unsafe"]
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.15.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        exclude: (^backend/src/prisma-generated-sql/) # includes prisma ORM generated files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.1
    hooks:
      - id: prettier
        name: Prettier
        stages: [pre-commit]
        exclude: (^charts/.*/templates/)

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        stages: [pre-commit]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.19.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
