# Reusable vars
x-var:
  - &POSTGRES_USER postgres
  - &POSTGRES_PASSWORD default
  - &POSTGRES_DATABASE postgres

# Reusable envars for postgres
x-postgres-vars: &postgres-vars
  POSTGRES_HOST: database
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_DATABASE: *POSTGRES_DATABASE

services:
  database:
    image: postgis/postgis:16-3.4 # if using crunchy , make sure to align with crunchy version, currently it is at 16 and postgis 3.3
    container_name: database
    environment:
      <<: *postgres-vars
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]
    ports: ["5432:5432"]

  migrations:
    image: ghcr.io/bcgov/nr-rec-resources/migrations:a9b5134b270aab6498590d4f27c92c662184dfda
    depends_on:
      database:
        condition: service_healthy

  backend:
    image: ghcr.io/bcgov/nr-rec-resources/backend:a9b5134b270aab6498590d4f27c92c662184dfda
    ports: ["8000:8000"]

  frontend:
    image: ghcr.io/bcgov/nr-rec-resources/frontend:a9b5134b270aab6498590d4f27c92c662184dfda
    environment:
      API_URL: http://backend:8000
    ports: ["3000:3000"]
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
