/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
import * as $runtime from '@prisma/client/runtime/client';

/**
 * @param _int8
 */
export const getRecreationAssetGeom = $runtime.makeTypedQueryFactory(
  '\nselect\nrag.asset_id,\nrag.geometry_type_code,\nround(public.st_y(public.st_transform(\ncase\nwhen public.st_srid(rag.geometry) = 0\nthen public.st_setsrid(rag.geometry, 3005)\nelse rag.geometry\nend, 4326))::numeric, 6) as latitude,\nround(public.st_x(public.st_transform(\ncase\nwhen public.st_srid(rag.geometry) = 0\nthen public.st_setsrid(rag.geometry, 3005)\nelse rag.geometry\nend, 4326))::numeric, 6) as longitude\nfrom rst.recreation_asset_geom rag\nwhere rag.asset_id = any ($1::bigint[])\nand rag.geometry is not null;',
) as (
  _int8: (number | bigint)[],
) => $runtime.TypedSql<
  getRecreationAssetGeom.Parameters,
  getRecreationAssetGeom.Result
>;

export namespace getRecreationAssetGeom {
  export type Parameters = [_int8: (number | bigint)[]];
  export type Result = {
    asset_id: bigint;
    geometry_type_code: string | null;
    latitude: $runtime.Decimal | null;
    longitude: $runtime.Decimal | null;
  };
}
