/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict";
exports.getRecreationResourceSuggestions =
  require("./getRecreationResourceSuggestions.js").getRecreationResourceSuggestions;
