export const BASE_URL = process.env.E2E_BASE_URL || 'http://localhost:3001';

// Which login flow to drive. The explicit E2E_TARGET flag wins (CI sets it from
// the workflow's `local` input); when unset it falls back to inferring from the
// URL, so local dev needs no configuration.
export const E2E_TARGET: 'local' | 'deployed' =
  (process.env.E2E_TARGET as 'local' | 'deployed') ??
  (BASE_URL.includes('localhost') ? 'local' : 'deployed');

// Playwright storageState files — generated by e2e/auth/setup.ts, gitignored
export const ADMIN_STATE = 'e2e/auth/.admin.storageState.json';
export const VIEWER_STATE = 'e2e/auth/.viewer.storageState.json';
