/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC API
 * RST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecreationResourceDto } from './RecreationResourceDto';
import {
  RecreationResourceDtoFromJSON,
  RecreationResourceDtoFromJSONTyped,
  RecreationResourceDtoToJSON,
  RecreationResourceDtoToJSONTyped,
} from './RecreationResourceDto';
import type { FilterDto } from './FilterDto';
import {
  FilterDtoFromJSON,
  FilterDtoFromJSONTyped,
  FilterDtoToJSON,
  FilterDtoToJSONTyped,
} from './FilterDto';

/**
 *
 * @export
 * @interface PaginatedRecreationResourceDto
 */
export interface PaginatedRecreationResourceDto {
  /**
   *
   * @type {Array<RecreationResourceDto>}
   * @memberof PaginatedRecreationResourceDto
   */
  data: Array<RecreationResourceDto>;
  /**
   *
   * @type {number}
   * @memberof PaginatedRecreationResourceDto
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof PaginatedRecreationResourceDto
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof PaginatedRecreationResourceDto
   */
  limit: number;
  /**
   *
   * @type {Array<FilterDto>}
   * @memberof PaginatedRecreationResourceDto
   */
  filters: Array<FilterDto>;
}

/**
 * Check if a given object implements the PaginatedRecreationResourceDto interface.
 */
export function instanceOfPaginatedRecreationResourceDto(
  value: object,
): value is PaginatedRecreationResourceDto {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('total' in value) || value['total'] === undefined) return false;
  if (!('page' in value) || value['page'] === undefined) return false;
  if (!('limit' in value) || value['limit'] === undefined) return false;
  if (!('filters' in value) || value['filters'] === undefined) return false;
  return true;
}

export function PaginatedRecreationResourceDtoFromJSON(
  json: any,
): PaginatedRecreationResourceDto {
  return PaginatedRecreationResourceDtoFromJSONTyped(json, false);
}

export function PaginatedRecreationResourceDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaginatedRecreationResourceDto {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(RecreationResourceDtoFromJSON),
    total: json['total'],
    page: json['page'],
    limit: json['limit'],
    filters: (json['filters'] as Array<any>).map(FilterDtoFromJSON),
  };
}

export function PaginatedRecreationResourceDtoToJSON(
  json: any,
): PaginatedRecreationResourceDto {
  return PaginatedRecreationResourceDtoToJSONTyped(json, false);
}

export function PaginatedRecreationResourceDtoToJSONTyped(
  value?: PaginatedRecreationResourceDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(RecreationResourceDtoToJSON),
    total: value['total'],
    page: value['page'],
    limit: value['limit'],
    filters: (value['filters'] as Array<any>).map(FilterDtoToJSON),
  };
}
