{{- /*
  CronJob template for backend-el.
  This template schedules and manages recurring daily & hourly jobs for the backend-el service.
  The PVC and secret names are derived from the shared resource name prefix which is shared across the jobs.
*/ -}}
{{- $sharedResourceNamePrefix := .Values.config.sharedResourceNamePrefix | default .Release.Name -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  schedule: {{.Values.schedule | quote}}
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: {{.Values.successHistoryLimit }}
  failedJobsHistoryLimit: {{.Values.failedHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      backoffLimit: {{.Values.backoffLimit}}
      activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            {{- include "labels" . | nindent 12 }}
        spec:
          volumes:
            - name: {{ $sharedResourceNamePrefix }}-csv
              persistentVolumeClaim:
                claimName: {{ $sharedResourceNamePrefix }}-csv
          containers:
            - name: {{ .Chart.Name }}
              image: "artifacts.developer.gov.bc.ca/github-docker-remote/bcgov/nr-rec-resources/backend-el:{{ .Values.image.tag | default .Chart.AppVersion }}"
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              envFrom:
                - secretRef:
                    name: {{ $sharedResourceNamePrefix }}-backend-el
                - secretRef:
                    name: aws-secrets
              env:
                - name: DB_PORT
                  value: "1543"
                - name: FILE_BASE_PATH # this is where the pvc is mounted and local csv files are stored before uploading to S3
                  value: "/uploads"
                - name: SPRING_JPA_SHOW_SQL
                  value: "false"
                - name: AWS_S3_BUCKET
                  value: "{{ .Values.config.awsS3Bucket }}"
                - name: JOB_MODE # additional arguments to pass to the application
                  value: "{{ .Values.config.jobMode }}"
                - name: spring_profiles_active
                  value: "openshift"
                - name: FLYWAY_ECS_CLUSTER
                  value: "{{ .Values.config.flywayEcsCluster }}"
                - name: FLYWAY_TASK_DEFINITION
                  value: "{{ .Values.config.flywayTaskDefinition }}"
                - name: FLYWAY_TASK_VPC_SUBNET
                  value: "{{ .Values.config.flywayTaskVpcSubnet }}"
                - name: FLYWAY_TASK_VPC_SECURITY_GROUP_ID
                  value: "{{ .Values.config.flywayTaskVpcSecurityGroup }}"
              volumeMounts:
                - name: {{ $sharedResourceNamePrefix }}-csv
                  mountPath: /uploads
          restartPolicy: OnFailure
