{{- if (hasSuffix "-hourly" .Release.Name) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  activeDeadlineSeconds: 3600
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ .Release.Name | replace "-hourly" "" }}-csv
          persistentVolumeClaim:
            claimName: {{ .Release.Name | replace "-hourly" "" }}-csv
      containers:
        - name: {{ .Chart.Name }}
          image: "artifacts.developer.gov.bc.ca/github-docker-remote/bcgov/nr-rec-resources/backend-el:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            requests:
              cpu: 200m
              memory: 1000Mi
          envFrom:
            - secretRef:
                name: {{ .Release.Name | replace "-hourly" "" }}-backend-el
            - secretRef:
                name: aws-secrets
          env:
            - name: DB_PORT
              value: "1543"
            - name: FILE_BASE_PATH
              value: "/uploads"
            - name: SPRING_JPA_SHOW_SQL
              value: "false"
            - name: AWS_S3_BUCKET
              value: "{{ .Values.config.awsS3Bucket }}"
            - name: JOB_MODE
              value: "{{ .Values.config.jobMode }}"
            - name: spring_profiles_active
              value: "openshift"
            - name: ECS_CLUSTER
              value: "{{ .Values.config.ecsCluster }}"
            - name: ECS_TASK_DEFINITION
              value: "{{ .Values.config.ecsTaskDefinition }}"
            - name: APP_SUBNET
              value: "{{ .Values.config.appSubnet }}"
            - name: APP_SECURITY_GROUP
              value: "{{ .Values.config.appSecurityGroup }}"
          volumeMounts:
            - name: {{ .Release.Name | replace "-hourly" "" }}-csv
              mountPath: /uploads
      restartPolicy: OnFailure
{{- end}}