{{- if eq .Values.config.createPvc "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.sharedResourceNamePrefix | default .Release.Name }}-csv
  labels: {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "500Mi"
  storageClassName: netapp-file-standard
{{- end }}
