apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name | replace "-hourly" "" }}-csv
  labels: {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "500Mi"
  storageClassName: netapp-file-standard
