{{- $jdbcUrl:= printf "jdbc:oracle:thin:@tcps://%s:1543/%s?oracle.net.ssl_server_dn_match=false" .Values.secrets.dbHost .Values.secrets.dbName}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | replace "-hourly" "" }}-backend-el-init
  labels: {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep

data:
  DB_HOST: {{ .Values.secrets.dbHost | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | replace "-hourly" "" }}-backend-el
  labels: {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep

data:
  DB_HOST: {{ .Values.secrets.dbHost | b64enc | quote }}
  DB_NAME: {{ .Values.secrets.dbName | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  DB_USER: {{ .Values.secrets.dbUser | b64enc | quote }}
  JDBC_URL: {{$jdbcUrl | b64enc | quote}}
