---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-el-init
  labels: {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep

data:
  DB_HOST: {{ .Values.secrets.dbHost | b64enc | quote }}
  CERT_SECRET: {{ .Values.secrets.certSecret | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-el
  labels: {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep

data:
  DB_HOST: {{ .Values.secrets.dbHost | b64enc | quote }}
  CERT_SECRET: {{ .Values.secrets.certSecret | b64enc | quote }}
  AWS_ACCESS_KEY: {{ .Values.secrets.awsAccessKey | b64enc | quote }}
  AWS_SECRET_KEY: {{ .Values.secrets.awsSecretKey | b64enc | quote }}
  DB_NAME: {{ .Values.secrets.dbName | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  DB_USER: {{ .Values.secrets.dbUser | b64enc | quote }}
