/* tslint:disable */
/* eslint-disable */
/**
 * FSA Forest Client API
 * Forest Client API Application - Version 302
 *
 * The version of the OpenAPI document: 302
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A location associated to a client
 */
export interface ClientLocationDto {
  /**
   * The client number
   */
  clientNumber?: string;
  /**
   * The location index
   */
  locationCode?: string;
  /**
   * The reference name of the location
   */
  locationName?: string;
  /**
   * The internal company code
   */
  companyCode?: string;
  /**
   * The address information
   */
  address1?: string;
  /**
   * The address information
   */
  address2?: string;
  /**
   * The address information
   */
  address3?: string;
  /**
   * The city name
   */
  city?: string;
  /**
   * The province/territory code
   */
  province?: string;
  /**
   * The postal code/zip code
   */
  postalCode?: string;
  /**
   * The country code
   */
  country?: string;
  /**
   * The business phone number
   */
  businessPhone?: string;
  /**
   * The home/personal phone number
   */
  homePhone?: string;
  /**
   * The cellphone number
   */
  cellPhone?: string;
  /**
   * The fax number
   */
  faxNumber?: string;
  /**
   * The email address
   */
  email?: string;
  /**
   * Define if this entry is expired or not<br>Y means yes<br>N means no
   */
  expired?: ClientLocationDto.ExpiredEnum;
  /**
   * Define if this entry is to be trusted or not<br>Y means yes<br>N means no
   */
  trusted?: ClientLocationDto.TrustedEnum;
  /**
   * The date when the mail was returned
   */
  returnedMailDate?: string;
  /**
   * An open field containing comments about the address
   */
  comment?: string;
}
export namespace ClientLocationDto {
  export type ExpiredEnum = 'Y' | 'N';
  export const ExpiredEnum = {
    Y: 'Y' as ExpiredEnum,
    N: 'N' as ExpiredEnum,
  };
  export type TrustedEnum = 'Y' | 'N';
  export const TrustedEnum = {
    Y: 'Y' as TrustedEnum,
    N: 'N' as TrustedEnum,
  };
}
