/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  BulkAssetUpdateResponseDto,
  CreateRecreationAssetDto,
  CreateRecreationAssetRepairDto,
  PaginatedRecreationAssetDto,
  RecreationAssetBulkRepairDto,
  RecreationAssetBulkUpdateDto,
  RecreationAssetCodeDto,
  RecreationAssetDto,
  RecreationAssetRepairDto,
  RecreationRepairCodeDto,
  UpdateRecreationAssetDto,
  UpdateRecreationAssetRepairDto,
} from '../models/index';
import {
  BulkAssetUpdateResponseDtoFromJSON,
  BulkAssetUpdateResponseDtoToJSON,
  CreateRecreationAssetDtoFromJSON,
  CreateRecreationAssetDtoToJSON,
  CreateRecreationAssetRepairDtoFromJSON,
  CreateRecreationAssetRepairDtoToJSON,
  PaginatedRecreationAssetDtoFromJSON,
  PaginatedRecreationAssetDtoToJSON,
  RecreationAssetBulkRepairDtoFromJSON,
  RecreationAssetBulkRepairDtoToJSON,
  RecreationAssetBulkUpdateDtoFromJSON,
  RecreationAssetBulkUpdateDtoToJSON,
  RecreationAssetCodeDtoFromJSON,
  RecreationAssetCodeDtoToJSON,
  RecreationAssetDtoFromJSON,
  RecreationAssetDtoToJSON,
  RecreationAssetRepairDtoFromJSON,
  RecreationAssetRepairDtoToJSON,
  RecreationRepairCodeDtoFromJSON,
  RecreationRepairCodeDtoToJSON,
  UpdateRecreationAssetDtoFromJSON,
  UpdateRecreationAssetDtoToJSON,
  UpdateRecreationAssetRepairDtoFromJSON,
  UpdateRecreationAssetRepairDtoToJSON,
} from '../models/index';

export interface RecreationAssetControllerBulkCreateRepairsRequest {
  recreationAssetBulkRepairDto: RecreationAssetBulkRepairDto;
}

export interface RecreationAssetControllerBulkUpdateAssetsRequest {
  recreationAssetBulkUpdateDto: RecreationAssetBulkUpdateDto;
}

export interface RecreationAssetControllerCreateAssetRequest {
  createRecreationAssetDto: CreateRecreationAssetDto;
}

export interface RecreationAssetControllerCreateRepairRequest {
  id: number;
  createRecreationAssetRepairDto: CreateRecreationAssetRepairDto;
}

export interface RecreationAssetControllerDeleteAssetRequest {
  id: number;
}

export interface RecreationAssetControllerDeleteRepairRequest {
  repairId: number;
}

export interface RecreationAssetControllerFindAllAssetsRequest {
  page?: number;
  limit?: number;
  parentId?: number;
  assetTag?: string;
  recResourceId?: string;
  assetCode?: number;
  assetName?: string;
  legacyStructureId?: string;
  minActualValue?: number;
  maxActualValue?: number;
  includeRepair?: boolean;
}

export interface RecreationAssetControllerFindAssetByIdRequest {
  id: number;
  includeRepair?: boolean;
}

export interface RecreationAssetControllerFindRepairsByAssetIdRequest {
  id: number;
}

export interface RecreationAssetControllerUpdateAssetRequest {
  id: number;
  updateRecreationAssetDto: UpdateRecreationAssetDto;
}

export interface RecreationAssetControllerUpdateRepairRequest {
  repairId: number;
  updateRecreationAssetRepairDto: UpdateRecreationAssetRepairDto;
}

/**
 *
 */
export class AssetsApi extends runtime.BaseAPI {
  /**
   * Applies a common repair code and completion date across multiple grouped asset IDs with varying costs.
   * Bulk create or record repairs across multiple recreation assets
   */
  async recreationAssetControllerBulkCreateRepairsRaw(
    requestParameters: RecreationAssetControllerBulkCreateRepairsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['recreationAssetBulkRepairDto'] == null) {
      throw new runtime.RequiredError(
        'recreationAssetBulkRepairDto',
        'Required parameter "recreationAssetBulkRepairDto" was null or undefined when calling recreationAssetControllerBulkCreateRepairs().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/bulk-repairs`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RecreationAssetBulkRepairDtoToJSON(
          requestParameters['recreationAssetBulkRepairDto'],
        ),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Applies a common repair code and completion date across multiple grouped asset IDs with varying costs.
   * Bulk create or record repairs across multiple recreation assets
   */
  async recreationAssetControllerBulkCreateRepairs(
    requestParameters: RecreationAssetControllerBulkCreateRepairsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.recreationAssetControllerBulkCreateRepairsRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * Bulk update common fields across multiple recreation assets
   */
  async recreationAssetControllerBulkUpdateAssetsRaw(
    requestParameters: RecreationAssetControllerBulkUpdateAssetsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<BulkAssetUpdateResponseDto>> {
    if (requestParameters['recreationAssetBulkUpdateDto'] == null) {
      throw new runtime.RequiredError(
        'recreationAssetBulkUpdateDto',
        'Required parameter "recreationAssetBulkUpdateDto" was null or undefined when calling recreationAssetControllerBulkUpdateAssets().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/bulk-update`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: RecreationAssetBulkUpdateDtoToJSON(
          requestParameters['recreationAssetBulkUpdateDto'],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BulkAssetUpdateResponseDtoFromJSON(jsonValue),
    );
  }

  /**
   * Bulk update common fields across multiple recreation assets
   */
  async recreationAssetControllerBulkUpdateAssets(
    requestParameters: RecreationAssetControllerBulkUpdateAssetsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<BulkAssetUpdateResponseDto> {
    const response = await this.recreationAssetControllerBulkUpdateAssetsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Create a new recreation asset
   */
  async recreationAssetControllerCreateAssetRaw(
    requestParameters: RecreationAssetControllerCreateAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RecreationAssetDto>> {
    if (requestParameters['createRecreationAssetDto'] == null) {
      throw new runtime.RequiredError(
        'createRecreationAssetDto',
        'Required parameter "createRecreationAssetDto" was null or undefined when calling recreationAssetControllerCreateAsset().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateRecreationAssetDtoToJSON(
          requestParameters['createRecreationAssetDto'],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RecreationAssetDtoFromJSON(jsonValue),
    );
  }

  /**
   * Create a new recreation asset
   */
  async recreationAssetControllerCreateAsset(
    requestParameters: RecreationAssetControllerCreateAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RecreationAssetDto> {
    const response = await this.recreationAssetControllerCreateAssetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Bulk create multiple recreation assets
   */
  async bulkCreateRecreationAssets(
    assets: CreateRecreationAssetDto[],
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RecreationAssetDto[]> {
    const headerParameters: runtime.HTTPHeaders = {};
    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);
      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    const response = await this.request(
      {
        path: `/api/v1/assets/bulk-create`,
        method: 'POST',
        headers: headerParameters,
        query: {},
        body: { assets: assets.map((a) => CreateRecreationAssetDtoToJSON(a)) },
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<RecreationAssetDto[]>(
      response,
      (jsonValue) => (jsonValue as any[]).map(RecreationAssetDtoFromJSON),
    ).value();
  }

  /**
   * Create a repair record for an asset
   */
  async recreationAssetControllerCreateRepairRaw(
    requestParameters: RecreationAssetControllerCreateRepairRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RecreationAssetRepairDto>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling recreationAssetControllerCreateRepair().',
      );
    }

    if (requestParameters['createRecreationAssetRepairDto'] == null) {
      throw new runtime.RequiredError(
        'createRecreationAssetRepairDto',
        'Required parameter "createRecreationAssetRepairDto" was null or undefined when calling recreationAssetControllerCreateRepair().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/{id}/repairs`;
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateRecreationAssetRepairDtoToJSON(
          requestParameters['createRecreationAssetRepairDto'],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RecreationAssetRepairDtoFromJSON(jsonValue),
    );
  }

  /**
   * Create a repair record for an asset
   */
  async recreationAssetControllerCreateRepair(
    requestParameters: RecreationAssetControllerCreateRepairRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RecreationAssetRepairDto> {
    const response = await this.recreationAssetControllerCreateRepairRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Delete a recreation asset
   */
  async recreationAssetControllerDeleteAssetRaw(
    requestParameters: RecreationAssetControllerDeleteAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling recreationAssetControllerDeleteAsset().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/{id}`;
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a recreation asset
   */
  async recreationAssetControllerDeleteAsset(
    requestParameters: RecreationAssetControllerDeleteAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.recreationAssetControllerDeleteAssetRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * Delete a repair record
   */
  async recreationAssetControllerDeleteRepairRaw(
    requestParameters: RecreationAssetControllerDeleteRepairRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['repairId'] == null) {
      throw new runtime.RequiredError(
        'repairId',
        'Required parameter "repairId" was null or undefined when calling recreationAssetControllerDeleteRepair().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/repairs/{repairId}`;
    urlPath = urlPath.replace(
      `{${'repairId'}}`,
      encodeURIComponent(String(requestParameters['repairId'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a repair record
   */
  async recreationAssetControllerDeleteRepair(
    requestParameters: RecreationAssetControllerDeleteRepairRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.recreationAssetControllerDeleteRepairRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * Retrieve all recreation asset type codes
   */
  async recreationAssetControllerFindAllAssetCodesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RecreationAssetCodeDto>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/codes`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(RecreationAssetCodeDtoFromJSON),
    );
  }

  /**
   * Retrieve all recreation asset type codes
   */
  async recreationAssetControllerFindAllAssetCodes(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RecreationAssetCodeDto>> {
    const response =
      await this.recreationAssetControllerFindAllAssetCodesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Retrieve recreation assets with filtering and pagination
   */
  async recreationAssetControllerFindAllAssetsRaw(
    requestParameters: RecreationAssetControllerFindAllAssetsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PaginatedRecreationAssetDto>> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['parentId'] != null) {
      queryParameters['parent_id'] = requestParameters['parentId'];
    }

    if (requestParameters['assetTag'] != null) {
      queryParameters['asset_tag'] = requestParameters['assetTag'];
    }

    if (requestParameters['recResourceId'] != null) {
      queryParameters['rec_resource_id'] = requestParameters['recResourceId'];
    }

    if (requestParameters['assetCode'] != null) {
      queryParameters['asset_code'] = requestParameters['assetCode'];
    }

    if (requestParameters['assetName'] != null) {
      queryParameters['asset_name'] = requestParameters['assetName'];
    }

    if (requestParameters['legacyStructureId'] != null) {
      queryParameters['legacy_structure_id'] =
        requestParameters['legacyStructureId'];
    }

    if (requestParameters['minActualValue'] != null) {
      queryParameters['min_actual_value'] = requestParameters['minActualValue'];
    }

    if (requestParameters['maxActualValue'] != null) {
      queryParameters['max_actual_value'] = requestParameters['maxActualValue'];
    }

    if (requestParameters['includeRepair'] != null) {
      queryParameters['include_repair'] = requestParameters['includeRepair'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PaginatedRecreationAssetDtoFromJSON(jsonValue),
    );
  }

  /**
   * Retrieve recreation assets with filtering and pagination
   */
  async recreationAssetControllerFindAllAssets(
    requestParameters: RecreationAssetControllerFindAllAssetsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PaginatedRecreationAssetDto> {
    const response = await this.recreationAssetControllerFindAllAssetsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Retrieve all recreation asset repair codes
   */
  async recreationAssetControllerFindAllRepairCodesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RecreationRepairCodeDto>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/repair-codes`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(RecreationRepairCodeDtoFromJSON),
    );
  }

  /**
   * Retrieve all recreation asset repair codes
   */
  async recreationAssetControllerFindAllRepairCodes(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RecreationRepairCodeDto>> {
    const response =
      await this.recreationAssetControllerFindAllRepairCodesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Find a recreation asset by ID
   */
  async recreationAssetControllerFindAssetByIdRaw(
    requestParameters: RecreationAssetControllerFindAssetByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RecreationAssetDto>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling recreationAssetControllerFindAssetById().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['includeRepair'] != null) {
      queryParameters['include_repair'] = requestParameters['includeRepair'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/{id}`;
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RecreationAssetDtoFromJSON(jsonValue),
    );
  }

  /**
   * Find a recreation asset by ID
   */
  async recreationAssetControllerFindAssetById(
    requestParameters: RecreationAssetControllerFindAssetByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RecreationAssetDto> {
    const response = await this.recreationAssetControllerFindAssetByIdRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get all repair records for an asset
   */
  async recreationAssetControllerFindRepairsByAssetIdRaw(
    requestParameters: RecreationAssetControllerFindRepairsByAssetIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RecreationAssetRepairDto>>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling recreationAssetControllerFindRepairsByAssetId().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/{id}/repairs`;
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(RecreationAssetRepairDtoFromJSON),
    );
  }

  /**
   * Get all repair records for an asset
   */
  async recreationAssetControllerFindRepairsByAssetId(
    requestParameters: RecreationAssetControllerFindRepairsByAssetIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RecreationAssetRepairDto>> {
    const response =
      await this.recreationAssetControllerFindRepairsByAssetIdRaw(
        requestParameters,
        initOverrides,
      );
    return await response.value();
  }

  /**
   * Update an existing recreation asset
   */
  async recreationAssetControllerUpdateAssetRaw(
    requestParameters: RecreationAssetControllerUpdateAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RecreationAssetDto>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling recreationAssetControllerUpdateAsset().',
      );
    }

    if (requestParameters['updateRecreationAssetDto'] == null) {
      throw new runtime.RequiredError(
        'updateRecreationAssetDto',
        'Required parameter "updateRecreationAssetDto" was null or undefined when calling recreationAssetControllerUpdateAsset().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/{id}`;
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateRecreationAssetDtoToJSON(
          requestParameters['updateRecreationAssetDto'],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RecreationAssetDtoFromJSON(jsonValue),
    );
  }

  /**
   * Update an existing recreation asset
   */
  async recreationAssetControllerUpdateAsset(
    requestParameters: RecreationAssetControllerUpdateAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RecreationAssetDto> {
    const response = await this.recreationAssetControllerUpdateAssetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Update a repair record
   */
  async recreationAssetControllerUpdateRepairRaw(
    requestParameters: RecreationAssetControllerUpdateRepairRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RecreationAssetRepairDto>> {
    if (requestParameters['repairId'] == null) {
      throw new runtime.RequiredError(
        'repairId',
        'Required parameter "repairId" was null or undefined when calling recreationAssetControllerUpdateRepair().',
      );
    }

    if (requestParameters['updateRecreationAssetRepairDto'] == null) {
      throw new runtime.RequiredError(
        'updateRecreationAssetRepairDto',
        'Required parameter "updateRecreationAssetRepairDto" was null or undefined when calling recreationAssetControllerUpdateRepair().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/assets/repairs/{repairId}`;
    urlPath = urlPath.replace(
      `{${'repairId'}}`,
      encodeURIComponent(String(requestParameters['repairId'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateRecreationAssetRepairDtoToJSON(
          requestParameters['updateRecreationAssetRepairDto'],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RecreationAssetRepairDtoFromJSON(jsonValue),
    );
  }

  /**
   * Update a repair record
   */
  async recreationAssetControllerUpdateRepair(
    requestParameters: RecreationAssetControllerUpdateRepairRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RecreationAssetRepairDto> {
    const response = await this.recreationAssetControllerUpdateRepairRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
