/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type BcgwClosuresShortFeatureCollectionDto,
  BcgwClosuresShortFeatureCollectionDtoFromJSON,
  BcgwClosuresShortFeatureCollectionDtoToJSON,
} from '../models/BcgwClosuresShortFeatureCollectionDto';
import {
  type BcgwFeatureCollectionDto,
  BcgwFeatureCollectionDtoFromJSON,
  BcgwFeatureCollectionDtoToJSON,
} from '../models/BcgwFeatureCollectionDto';
import {
  type BcgwRecreationLinesFeatureCollectionDto,
  BcgwRecreationLinesFeatureCollectionDtoFromJSON,
  BcgwRecreationLinesFeatureCollectionDtoToJSON,
} from '../models/BcgwRecreationLinesFeatureCollectionDto';
import {
  type BcgwRecreationPolygonsFeatureCollectionDto,
  BcgwRecreationPolygonsFeatureCollectionDtoFromJSON,
  BcgwRecreationPolygonsFeatureCollectionDtoToJSON,
} from '../models/BcgwRecreationPolygonsFeatureCollectionDto';

export interface GetBcgwClosuresFullyAttributedRequest {
  /**
   * Page number (1-indexed). Each page returns up to 1000 features.
   */
  page?: number;
}

export interface GetBcgwClosuresShortRequest {
  /**
   * Page number (1-indexed). Each page returns up to 1000 features.
   */
  page?: number;
}

export interface GetBcgwRecreationLinesRequest {
  /**
   * Page number (1-indexed). Each page returns up to 1000 features.
   */
  page?: number;
}

export interface GetBcgwRecreationPolygonsRequest {
  /**
   * Page number (1-indexed). Each page returns up to 1000 features.
   */
  page?: number;
}

/**
 *
 */
export class BcgwApi extends runtime.BaseAPI {
  /**
   * Creates request options for getBcgwClosuresFullyAttributed without sending the request
   */
  async getBcgwClosuresFullyAttributedRequestOpts(
    requestParameters: GetBcgwClosuresFullyAttributedRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken(
        'bcgw-keycloak',
        [],
      );
    }

    let urlPath = `/api/v1/bcgw/closures-fully-attributed`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a paginated GeoJSON FeatureCollection of recreation resources intended for ingestion by the BC Geographic Warehouse (BCGW) into the WHSE_FOREST_TENURE.FTEN_REC_DTAILS_CLOSURES_FA_SV layer. Data is sourced from a pre-computed materialized view refreshed every 5 minutes.
   * Get all recreation resources for BCGW ingestion
   */
  async getBcgwClosuresFullyAttributedRaw(
    requestParameters: GetBcgwClosuresFullyAttributedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<BcgwFeatureCollectionDto>> {
    const requestOptions =
      await this.getBcgwClosuresFullyAttributedRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BcgwFeatureCollectionDtoFromJSON(jsonValue),
    );
  }

  /**
   * Returns a paginated GeoJSON FeatureCollection of recreation resources intended for ingestion by the BC Geographic Warehouse (BCGW) into the WHSE_FOREST_TENURE.FTEN_REC_DTAILS_CLOSURES_FA_SV layer. Data is sourced from a pre-computed materialized view refreshed every 5 minutes.
   * Get all recreation resources for BCGW ingestion
   */
  async getBcgwClosuresFullyAttributed(
    requestParameters: GetBcgwClosuresFullyAttributedRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<BcgwFeatureCollectionDto> {
    const response = await this.getBcgwClosuresFullyAttributedRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for getBcgwClosuresShort without sending the request
   */
  async getBcgwClosuresShortRequestOpts(
    requestParameters: GetBcgwClosuresShortRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v1/bcgw/closures-short`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a paginated GeoJSON FeatureCollection of recreation resources intended for ingestion by the BC Geographic Warehouse (BCGW) into the WHSE_FOREST_TENURE.FTEN_REC_DTAILS_CLOSURES_SV layer. A 20-column subset of the fully attributed closures layer.
   * Get recreation resources for the short closures BCGW layer
   */
  async getBcgwClosuresShortRaw(
    requestParameters: GetBcgwClosuresShortRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<BcgwClosuresShortFeatureCollectionDto>> {
    const requestOptions =
      await this.getBcgwClosuresShortRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BcgwClosuresShortFeatureCollectionDtoFromJSON(jsonValue),
    );
  }

  /**
   * Returns a paginated GeoJSON FeatureCollection of recreation resources intended for ingestion by the BC Geographic Warehouse (BCGW) into the WHSE_FOREST_TENURE.FTEN_REC_DTAILS_CLOSURES_SV layer. A 20-column subset of the fully attributed closures layer.
   * Get recreation resources for the short closures BCGW layer
   */
  async getBcgwClosuresShort(
    requestParameters: GetBcgwClosuresShortRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<BcgwClosuresShortFeatureCollectionDto> {
    const response = await this.getBcgwClosuresShortRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for getBcgwRecreationLines without sending the request
   */
  async getBcgwRecreationLinesRequestOpts(
    requestParameters: GetBcgwRecreationLinesRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v1/bcgw/recreation-lines`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a paginated GeoJSON FeatureCollection of recreation trail/line features intended for ingestion by the BC Geographic Warehouse (BCGW) into the WHSE_FOREST_TENURE.FTEN_RECREATION_LINES_SVW layer. Data is sourced from a pre-computed materialized view refreshed every 5 minutes.
   * Get recreation line features for BCGW ingestion
   */
  async getBcgwRecreationLinesRaw(
    requestParameters: GetBcgwRecreationLinesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<BcgwRecreationLinesFeatureCollectionDto>> {
    const requestOptions =
      await this.getBcgwRecreationLinesRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BcgwRecreationLinesFeatureCollectionDtoFromJSON(jsonValue),
    );
  }

  /**
   * Returns a paginated GeoJSON FeatureCollection of recreation trail/line features intended for ingestion by the BC Geographic Warehouse (BCGW) into the WHSE_FOREST_TENURE.FTEN_RECREATION_LINES_SVW layer. Data is sourced from a pre-computed materialized view refreshed every 5 minutes.
   * Get recreation line features for BCGW ingestion
   */
  async getBcgwRecreationLines(
    requestParameters: GetBcgwRecreationLinesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<BcgwRecreationLinesFeatureCollectionDto> {
    const response = await this.getBcgwRecreationLinesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for getBcgwRecreationPolygons without sending the request
   */
  async getBcgwRecreationPolygonsRequestOpts(
    requestParameters: GetBcgwRecreationPolygonsRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v1/bcgw/recreation-polygons`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a paginated GeoJSON FeatureCollection of recreation polygon features intended for ingestion by the BC Geographic Warehouse (BCGW) into the WHSE_FOREST_TENURE.FTEN_RECREATION_POLY_SVW layer. Data is sourced from a pre-computed materialized view refreshed every 5 minutes.
   * Get recreation polygon features for BCGW ingestion
   */
  async getBcgwRecreationPolygonsRaw(
    requestParameters: GetBcgwRecreationPolygonsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<BcgwRecreationPolygonsFeatureCollectionDto>> {
    const requestOptions =
      await this.getBcgwRecreationPolygonsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BcgwRecreationPolygonsFeatureCollectionDtoFromJSON(jsonValue),
    );
  }

  /**
   * Returns a paginated GeoJSON FeatureCollection of recreation polygon features intended for ingestion by the BC Geographic Warehouse (BCGW) into the WHSE_FOREST_TENURE.FTEN_RECREATION_POLY_SVW layer. Data is sourced from a pre-computed materialized view refreshed every 5 minutes.
   * Get recreation polygon features for BCGW ingestion
   */
  async getBcgwRecreationPolygons(
    requestParameters: GetBcgwRecreationPolygonsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<BcgwRecreationPolygonsFeatureCollectionDto> {
    const response = await this.getBcgwRecreationPolygonsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
