/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  AgreementHolderClientPublicViewDto,
  BadRequestResponseDto,
  ClientLocationDto,
  ClientPublicViewDto,
  CreateAgreementHolderDto,
  UpdateAgreementHolderDto,
} from '../models/index';
import {
  AgreementHolderClientPublicViewDtoFromJSON,
  AgreementHolderClientPublicViewDtoToJSON,
  BadRequestResponseDtoFromJSON,
  BadRequestResponseDtoToJSON,
  ClientLocationDtoFromJSON,
  ClientLocationDtoToJSON,
  ClientPublicViewDtoFromJSON,
  ClientPublicViewDtoToJSON,
  CreateAgreementHolderDtoFromJSON,
  CreateAgreementHolderDtoToJSON,
  UpdateAgreementHolderDtoFromJSON,
  UpdateAgreementHolderDtoToJSON,
} from '../models/index';

export interface CreateRecreationResourceAgreementHolderRequest {
  recResourceId: string;
  createAgreementHolderDto: CreateAgreementHolderDto;
}

export interface GetPartnerLocationsByClientIdRequest {
  clientId: string;
}

export interface GetPartnersByRecreationResourceIdRequest {
  recResourceId: string;
}

export interface SearchPartnerByClientIdRequest {
  clientId: string;
}

export interface SearchPartnersRequest {
  page?: number;
  size?: number;
  name?: string;
  acronym?: string;
  number?: string;
}

export interface UpdateRecreationResourceAgreementHolderRequest {
  recResourceId: string;
  updateAgreementHolderDto: UpdateAgreementHolderDto;
}

/**
 *
 */
export class PartnersApi extends runtime.BaseAPI {
  /**
   * Creates a new agreement holder record for the recreation resource when a client is assigned.
   * Add agreement holder for a recreation resource
   */
  async createRecreationResourceAgreementHolderRaw(
    requestParameters: CreateRecreationResourceAgreementHolderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AgreementHolderClientPublicViewDto>> {
    if (requestParameters['recResourceId'] == null) {
      throw new runtime.RequiredError(
        'recResourceId',
        'Required parameter "recResourceId" was null or undefined when calling createRecreationResourceAgreementHolder().',
      );
    }

    if (requestParameters['createAgreementHolderDto'] == null) {
      throw new runtime.RequiredError(
        'createAgreementHolderDto',
        'Required parameter "createAgreementHolderDto" was null or undefined when calling createRecreationResourceAgreementHolder().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/partners/recreation-resources/{rec_resource_id}`;
    urlPath = urlPath.replace(
      `{${'rec_resource_id'}}`,
      encodeURIComponent(String(requestParameters['recResourceId'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateAgreementHolderDtoToJSON(
          requestParameters['createAgreementHolderDto'],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AgreementHolderClientPublicViewDtoFromJSON(jsonValue),
    );
  }

  /**
   * Creates a new agreement holder record for the recreation resource when a client is assigned.
   * Add agreement holder for a recreation resource
   */
  async createRecreationResourceAgreementHolder(
    requestParameters: CreateRecreationResourceAgreementHolderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AgreementHolderClientPublicViewDto> {
    const response = await this.createRecreationResourceAgreementHolderRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get partner locations by client id
   */
  async getPartnerLocationsByClientIdRaw(
    requestParameters: GetPartnerLocationsByClientIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ClientLocationDto>>> {
    if (requestParameters['clientId'] == null) {
      throw new runtime.RequiredError(
        'clientId',
        'Required parameter "clientId" was null or undefined when calling getPartnerLocationsByClientId().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/partners/{client_id}`;
    urlPath = urlPath.replace(
      `{${'client_id'}}`,
      encodeURIComponent(String(requestParameters['clientId'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ClientLocationDtoFromJSON),
    );
  }

  /**
   * Get partner locations by client id
   */
  async getPartnerLocationsByClientId(
    requestParameters: GetPartnerLocationsByClientIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ClientLocationDto>> {
    const response = await this.getPartnerLocationsByClientIdRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Looks up the agreement holder for the given recreation resource and returns partner details for the associated client number.
   * Get partners by recreation resource ID
   */
  async getPartnersByRecreationResourceIdRaw(
    requestParameters: GetPartnersByRecreationResourceIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<AgreementHolderClientPublicViewDto>>> {
    if (requestParameters['recResourceId'] == null) {
      throw new runtime.RequiredError(
        'recResourceId',
        'Required parameter "recResourceId" was null or undefined when calling getPartnersByRecreationResourceId().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/partners/recreation-resources/{rec_resource_id}`;
    urlPath = urlPath.replace(
      `{${'rec_resource_id'}}`,
      encodeURIComponent(String(requestParameters['recResourceId'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(AgreementHolderClientPublicViewDtoFromJSON),
    );
  }

  /**
   * Looks up the agreement holder for the given recreation resource and returns partner details for the associated client number.
   * Get partners by recreation resource ID
   */
  async getPartnersByRecreationResourceId(
    requestParameters: GetPartnersByRecreationResourceIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<AgreementHolderClientPublicViewDto>> {
    const response = await this.getPartnersByRecreationResourceIdRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Looks up a single partner by client id using the forest client findByClientNumber API. Returns active and inactive clients.
   * Search for partner by client id
   */
  async searchPartnerByClientIdRaw(
    requestParameters: SearchPartnerByClientIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ClientPublicViewDto>> {
    if (requestParameters['clientId'] == null) {
      throw new runtime.RequiredError(
        'clientId',
        'Required parameter "clientId" was null or undefined when calling searchPartnerByClientId().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['clientId'] != null) {
      queryParameters['client_id'] = requestParameters['clientId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/partners/search`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClientPublicViewDtoFromJSON(jsonValue),
    );
  }

  /**
   * Looks up a single partner by client id using the forest client findByClientNumber API. Returns active and inactive clients.
   * Search for partner by client id
   */
  async searchPartnerByClientId(
    requestParameters: SearchPartnerByClientIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ClientPublicViewDto> {
    const response = await this.searchPartnerByClientIdRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Search for partners based on the provided parameters. It uses a fuzzy match to search for the partner name. The cutout for the fuzzy match is 0.8. The search is case insensitive.
   * Search for partners
   */
  async searchPartnersRaw(
    requestParameters: SearchPartnersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ClientPublicViewDto>>> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    if (requestParameters['name'] != null) {
      queryParameters['name'] = requestParameters['name'];
    }

    if (requestParameters['acronym'] != null) {
      queryParameters['acronym'] = requestParameters['acronym'];
    }

    if (requestParameters['number'] != null) {
      queryParameters['number'] = requestParameters['number'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/partners/search/by`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ClientPublicViewDtoFromJSON),
    );
  }

  /**
   * Search for partners based on the provided parameters. It uses a fuzzy match to search for the partner name. The cutout for the fuzzy match is 0.8. The search is case insensitive.
   * Search for partners
   */
  async searchPartners(
    requestParameters: SearchPartnersRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ClientPublicViewDto>> {
    const response = await this.searchPartnersRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Updates the agreement start date and/or agreement end date for an existing agreement holder record.
   * Edit agreement holder dates for a recreation resource
   */
  async updateRecreationResourceAgreementHolderRaw(
    requestParameters: UpdateRecreationResourceAgreementHolderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AgreementHolderClientPublicViewDto>> {
    if (requestParameters['recResourceId'] == null) {
      throw new runtime.RequiredError(
        'recResourceId',
        'Required parameter "recResourceId" was null or undefined when calling updateRecreationResourceAgreementHolder().',
      );
    }

    if (requestParameters['updateAgreementHolderDto'] == null) {
      throw new runtime.RequiredError(
        'updateAgreementHolderDto',
        'Required parameter "updateAgreementHolderDto" was null or undefined when calling updateRecreationResourceAgreementHolder().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('keycloak', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/partners/recreation-resources/{rec_resource_id}`;
    urlPath = urlPath.replace(
      `{${'rec_resource_id'}}`,
      encodeURIComponent(String(requestParameters['recResourceId'])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateAgreementHolderDtoToJSON(
          requestParameters['updateAgreementHolderDto'],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AgreementHolderClientPublicViewDtoFromJSON(jsonValue),
    );
  }

  /**
   * Updates the agreement start date and/or agreement end date for an existing agreement holder record.
   * Edit agreement holder dates for a recreation resource
   */
  async updateRecreationResourceAgreementHolder(
    requestParameters: UpdateRecreationResourceAgreementHolderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AgreementHolderClientPublicViewDto> {
    const response = await this.updateRecreationResourceAgreementHolderRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
