/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ActAdvisoryUpsertDto
 */
export interface ActAdvisoryUpsertDto {
  /**
   * Recreation resource identifier (REC ID) the advisory applies to.
   */
  rec_resource_id: string;
  /**
   * Act advisory number. Together with rec_resource_id this forms the unique key.
   */
  advisory_number: number;
  /**
   * Advisory title.
   */
  title: string;
  /**
   * Long-form advisory description / body.
   */
  description?: string | null;
  /**
   * Username / identifier of the person who submitted the advisory in Act.
   */
  submitted_by: string;
  /**
   * Display name of the access status.
   */
  access_status_name: string;
  /**
   * Access status grouping label.
   */
  access_status_grouplabel: string;
  /**
   * Access status description.
   */
  access_status_description?: string | null;
  /**
   * Event type for the advisory.
   */
  event_type: string;
  /**
   * Urgency level (e.g. Low / Medium / High).
   */
  urgency: string;
  /**
   * Advisory status (e.g. Published / Draft).
   */
  advisory_status: string;
  /**
   * Whether the advisory affects reservations.
   */
  is_reservations_affected: boolean | null;
  /**
   * Whether the advisory_date should be displayed publicly.
   */
  is_advisory_date_displayed: boolean;
  /**
   * Whether the effective_date should be displayed publicly.
   */
  is_effective_date_displayed: boolean;
  /**
   * Whether the end_date should be displayed publicly.
   */
  is_end_date_displayed: boolean;
  /**
   * Whether the updated_date should be displayed publicly.
   */
  is_updated_date_displayed: boolean | null;
  /**
   * Date the advisory was created in Act (ISO 8601).
   */
  advisory_date: string;
  /**
   * Date the advisory becomes effective (ISO 8601).
   */
  effective_date: string | null;
  /**
   * Date the advisory ends, if applicable (ISO 8601).
   */
  end_date?: string | null;
  /**
   * Date the advisory expires, if applicable (ISO 8601).
   */
  expiry_date?: string | null;
  /**
   * Date the advisory was removed in Act, if applicable.
   */
  removal_date?: string | null;
  /**
   * Date the advisory record was last updated in Act.
   */
  updated_date: string | null;
  /**
   * Date the advisory was last content-modified in Act.
   */
  modified_date: string;
  /**
   * Deprecated alias for `published_date`. Still accepted for backward compatibility; when both fields are provided, `published_date` takes precedence.
   * @deprecated
   */
  published_at?: string | null;
  /**
   * Date the advisory was published, if applicable. Preferred ACT field name; mapped internally to the existing `published_at` storage column.
   */
  published_date?: string | null;
  /**
   * Listing rank used to order advisories in UIs.
   */
  listing_rank?: number;
  /**
   * Urgency sequence used for ordering.
   */
  urgency_sequence?: number;
  /**
   * Access-status precedence used for ordering.
   */
  access_status_precedence?: number;
  /**
   * Event-type precedence used for ordering.
   */
  event_type_precedence?: number;
}

/**
 * Check if a given object implements the ActAdvisoryUpsertDto interface.
 */
export function instanceOfActAdvisoryUpsertDto(
  value: object,
): value is ActAdvisoryUpsertDto {
  if (!('rec_resource_id' in value) || value['rec_resource_id'] === undefined)
    return false;
  if (!('advisory_number' in value) || value['advisory_number'] === undefined)
    return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('submitted_by' in value) || value['submitted_by'] === undefined)
    return false;
  if (
    !('access_status_name' in value) ||
    value['access_status_name'] === undefined
  )
    return false;
  if (
    !('access_status_grouplabel' in value) ||
    value['access_status_grouplabel'] === undefined
  )
    return false;
  if (!('event_type' in value) || value['event_type'] === undefined)
    return false;
  if (!('urgency' in value) || value['urgency'] === undefined) return false;
  if (!('advisory_status' in value) || value['advisory_status'] === undefined)
    return false;
  if (
    !('is_reservations_affected' in value) ||
    value['is_reservations_affected'] === undefined
  )
    return false;
  if (
    !('is_advisory_date_displayed' in value) ||
    value['is_advisory_date_displayed'] === undefined
  )
    return false;
  if (
    !('is_effective_date_displayed' in value) ||
    value['is_effective_date_displayed'] === undefined
  )
    return false;
  if (
    !('is_end_date_displayed' in value) ||
    value['is_end_date_displayed'] === undefined
  )
    return false;
  if (
    !('is_updated_date_displayed' in value) ||
    value['is_updated_date_displayed'] === undefined
  )
    return false;
  if (!('advisory_date' in value) || value['advisory_date'] === undefined)
    return false;
  if (!('effective_date' in value) || value['effective_date'] === undefined)
    return false;
  if (!('updated_date' in value) || value['updated_date'] === undefined)
    return false;
  if (!('modified_date' in value) || value['modified_date'] === undefined)
    return false;
  return true;
}

export function ActAdvisoryUpsertDtoFromJSON(json: any): ActAdvisoryUpsertDto {
  return ActAdvisoryUpsertDtoFromJSONTyped(json, false);
}

export function ActAdvisoryUpsertDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActAdvisoryUpsertDto {
  if (json == null) {
    return json;
  }
  return {
    rec_resource_id: json['rec_resource_id'],
    advisory_number: json['advisory_number'],
    title: json['title'],
    description:
      json['description'] === undefined
        ? undefined
        : json['description'] === null
          ? null
          : json['description'],
    submitted_by: json['submitted_by'],
    access_status_name: json['access_status_name'],
    access_status_grouplabel: json['access_status_grouplabel'],
    access_status_description:
      json['access_status_description'] === undefined
        ? undefined
        : json['access_status_description'] === null
          ? null
          : json['access_status_description'],
    event_type: json['event_type'],
    urgency: json['urgency'],
    advisory_status: json['advisory_status'],
    is_reservations_affected: json['is_reservations_affected'],
    is_advisory_date_displayed: json['is_advisory_date_displayed'],
    is_effective_date_displayed: json['is_effective_date_displayed'],
    is_end_date_displayed: json['is_end_date_displayed'],
    is_updated_date_displayed: json['is_updated_date_displayed'],
    advisory_date: json['advisory_date'],
    effective_date: json['effective_date'],
    end_date:
      json['end_date'] === undefined
        ? undefined
        : json['end_date'] === null
          ? null
          : json['end_date'],
    expiry_date:
      json['expiry_date'] === undefined
        ? undefined
        : json['expiry_date'] === null
          ? null
          : json['expiry_date'],
    removal_date:
      json['removal_date'] === undefined
        ? undefined
        : json['removal_date'] === null
          ? null
          : json['removal_date'],
    updated_date: json['updated_date'],
    modified_date: json['modified_date'],
    published_at:
      json['published_at'] === undefined
        ? undefined
        : json['published_at'] === null
          ? null
          : json['published_at'],
    published_date:
      json['published_date'] === undefined
        ? undefined
        : json['published_date'] === null
          ? null
          : json['published_date'],
    listing_rank:
      json['listing_rank'] == null ? undefined : json['listing_rank'],
    urgency_sequence:
      json['urgency_sequence'] == null ? undefined : json['urgency_sequence'],
    access_status_precedence:
      json['access_status_precedence'] == null
        ? undefined
        : json['access_status_precedence'],
    event_type_precedence:
      json['event_type_precedence'] == null
        ? undefined
        : json['event_type_precedence'],
  };
}

export function ActAdvisoryUpsertDtoToJSON(json: any): ActAdvisoryUpsertDto {
  return ActAdvisoryUpsertDtoToJSONTyped(json, false);
}

export function ActAdvisoryUpsertDtoToJSONTyped(
  value?: ActAdvisoryUpsertDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    rec_resource_id: value['rec_resource_id'],
    advisory_number: value['advisory_number'],
    title: value['title'],
    description: value['description'],
    submitted_by: value['submitted_by'],
    access_status_name: value['access_status_name'],
    access_status_grouplabel: value['access_status_grouplabel'],
    access_status_description: value['access_status_description'],
    event_type: value['event_type'],
    urgency: value['urgency'],
    advisory_status: value['advisory_status'],
    is_reservations_affected: value['is_reservations_affected'],
    is_advisory_date_displayed: value['is_advisory_date_displayed'],
    is_effective_date_displayed: value['is_effective_date_displayed'],
    is_end_date_displayed: value['is_end_date_displayed'],
    is_updated_date_displayed: value['is_updated_date_displayed'],
    advisory_date: value['advisory_date'],
    effective_date: value['effective_date'],
    end_date: value['end_date'],
    expiry_date: value['expiry_date'],
    removal_date: value['removal_date'],
    updated_date: value['updated_date'],
    modified_date: value['modified_date'],
    published_at: value['published_at'],
    published_date: value['published_date'],
    listing_rank: value['listing_rank'],
    urgency_sequence: value['urgency_sequence'],
    access_status_precedence: value['access_status_precedence'],
    event_type_precedence: value['event_type_precedence'],
  };
}
