/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ActAdvisoryUpdateDto
 */
export interface ActAdvisoryUpdateDto {
  /**
   * Advisory title.
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  title?: string;
  /**
   * Long-form advisory description / body.
   * @type {object}
   * @memberof ActAdvisoryUpdateDto
   */
  description?: object | null;
  /**
   * Username / identifier of the person who submitted the advisory in Act.
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  submitted_by?: string;
  /**
   * Display name of the access status.
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  access_status_name?: string;
  /**
   * Access status grouping label.
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  access_status_grouplabel?: string;
  /**
   * Access status description.
   * @type {object}
   * @memberof ActAdvisoryUpdateDto
   */
  access_status_description?: object | null;
  /**
   * Event type for the advisory.
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  event_type?: string;
  /**
   * Urgency level (e.g. Low / Medium / High).
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  urgency?: string;
  /**
   * Advisory status (e.g. Published / Draft).
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  advisory_status?: string;
  /**
   * Whether the advisory affects reservations.
   * @type {boolean}
   * @memberof ActAdvisoryUpdateDto
   */
  is_reservations_affected?: boolean;
  /**
   * Whether the advisory_date should be displayed publicly.
   * @type {boolean}
   * @memberof ActAdvisoryUpdateDto
   */
  is_advisory_date_displayed?: boolean;
  /**
   * Whether the effective_date should be displayed publicly.
   * @type {boolean}
   * @memberof ActAdvisoryUpdateDto
   */
  is_effective_date_displayed?: boolean;
  /**
   * Whether the end_date should be displayed publicly.
   * @type {boolean}
   * @memberof ActAdvisoryUpdateDto
   */
  is_end_date_displayed?: boolean;
  /**
   * Whether the updated_date should be displayed publicly.
   * @type {boolean}
   * @memberof ActAdvisoryUpdateDto
   */
  is_updated_date_displayed?: boolean;
  /**
   * Date the advisory was created in Act (ISO 8601).
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  advisory_date?: string;
  /**
   * Date the advisory becomes effective (ISO 8601).
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  effective_date?: string;
  /**
   * Date the advisory ends, if applicable (ISO 8601).
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  end_date?: string | null;
  /**
   * Date the advisory expires, if applicable (ISO 8601).
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  expiry_date?: string | null;
  /**
   * Date the advisory was removed in Act, if applicable.
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  removal_date?: string | null;
  /**
   * Date the advisory record was last updated in Act.
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  updated_date?: string;
  /**
   * Date the advisory was last content-modified in Act.
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  modified_date?: string;
  /**
   * Date the advisory was published, if applicable.
   * @type {string}
   * @memberof ActAdvisoryUpdateDto
   */
  published_at?: string | null;
  /**
   * Listing rank used to order advisories in UIs.
   * @type {number}
   * @memberof ActAdvisoryUpdateDto
   */
  listing_rank?: number;
  /**
   * Urgency sequence used for ordering.
   * @type {number}
   * @memberof ActAdvisoryUpdateDto
   */
  urgency_sequence?: number;
  /**
   * Access-status precedence used for ordering.
   * @type {number}
   * @memberof ActAdvisoryUpdateDto
   */
  access_status_precedence?: number;
  /**
   * Event-type precedence used for ordering.
   * @type {number}
   * @memberof ActAdvisoryUpdateDto
   */
  event_type_precedence?: number;
}

/**
 * Check if a given object implements the ActAdvisoryUpdateDto interface.
 */
export function instanceOfActAdvisoryUpdateDto(
  value: object,
): value is ActAdvisoryUpdateDto {
  return true;
}

export function ActAdvisoryUpdateDtoFromJSON(json: any): ActAdvisoryUpdateDto {
  return ActAdvisoryUpdateDtoFromJSONTyped(json, false);
}

export function ActAdvisoryUpdateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActAdvisoryUpdateDto {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'] == null ? undefined : json['title'],
    description: json['description'] == null ? undefined : json['description'],
    submitted_by:
      json['submitted_by'] == null ? undefined : json['submitted_by'],
    access_status_name:
      json['access_status_name'] == null
        ? undefined
        : json['access_status_name'],
    access_status_grouplabel:
      json['access_status_grouplabel'] == null
        ? undefined
        : json['access_status_grouplabel'],
    access_status_description:
      json['access_status_description'] == null
        ? undefined
        : json['access_status_description'],
    event_type: json['event_type'] == null ? undefined : json['event_type'],
    urgency: json['urgency'] == null ? undefined : json['urgency'],
    advisory_status:
      json['advisory_status'] == null ? undefined : json['advisory_status'],
    is_reservations_affected:
      json['is_reservations_affected'] == null
        ? undefined
        : json['is_reservations_affected'],
    is_advisory_date_displayed:
      json['is_advisory_date_displayed'] == null
        ? undefined
        : json['is_advisory_date_displayed'],
    is_effective_date_displayed:
      json['is_effective_date_displayed'] == null
        ? undefined
        : json['is_effective_date_displayed'],
    is_end_date_displayed:
      json['is_end_date_displayed'] == null
        ? undefined
        : json['is_end_date_displayed'],
    is_updated_date_displayed:
      json['is_updated_date_displayed'] == null
        ? undefined
        : json['is_updated_date_displayed'],
    advisory_date:
      json['advisory_date'] == null ? undefined : json['advisory_date'],
    effective_date:
      json['effective_date'] == null ? undefined : json['effective_date'],
    end_date: json['end_date'] == null ? undefined : json['end_date'],
    expiry_date: json['expiry_date'] == null ? undefined : json['expiry_date'],
    removal_date:
      json['removal_date'] == null ? undefined : json['removal_date'],
    updated_date:
      json['updated_date'] == null ? undefined : json['updated_date'],
    modified_date:
      json['modified_date'] == null ? undefined : json['modified_date'],
    published_at:
      json['published_at'] == null ? undefined : json['published_at'],
    listing_rank:
      json['listing_rank'] == null ? undefined : json['listing_rank'],
    urgency_sequence:
      json['urgency_sequence'] == null ? undefined : json['urgency_sequence'],
    access_status_precedence:
      json['access_status_precedence'] == null
        ? undefined
        : json['access_status_precedence'],
    event_type_precedence:
      json['event_type_precedence'] == null
        ? undefined
        : json['event_type_precedence'],
  };
}

export function ActAdvisoryUpdateDtoToJSON(json: any): ActAdvisoryUpdateDto {
  return ActAdvisoryUpdateDtoToJSONTyped(json, false);
}

export function ActAdvisoryUpdateDtoToJSONTyped(
  value?: ActAdvisoryUpdateDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    description: value['description'],
    submitted_by: value['submitted_by'],
    access_status_name: value['access_status_name'],
    access_status_grouplabel: value['access_status_grouplabel'],
    access_status_description: value['access_status_description'],
    event_type: value['event_type'],
    urgency: value['urgency'],
    advisory_status: value['advisory_status'],
    is_reservations_affected: value['is_reservations_affected'],
    is_advisory_date_displayed: value['is_advisory_date_displayed'],
    is_effective_date_displayed: value['is_effective_date_displayed'],
    is_end_date_displayed: value['is_end_date_displayed'],
    is_updated_date_displayed: value['is_updated_date_displayed'],
    advisory_date: value['advisory_date'],
    effective_date: value['effective_date'],
    end_date: value['end_date'],
    expiry_date: value['expiry_date'],
    removal_date: value['removal_date'],
    updated_date: value['updated_date'],
    modified_date: value['modified_date'],
    published_at: value['published_at'],
    listing_rank: value['listing_rank'],
    urgency_sequence: value['urgency_sequence'],
    access_status_precedence: value['access_status_precedence'],
    event_type_precedence: value['event_type_precedence'],
  };
}
