/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ActAdvisoryResponseDto
 */
export interface ActAdvisoryResponseDto {
  /**
   * Recreation resource identifier (REC ID) the advisory applies to.
   * @type {string}
   * @memberof ActAdvisoryResponseDto
   */
  rec_resource_id: string;
  /**
   * Act advisory number.
   * @type {number}
   * @memberof ActAdvisoryResponseDto
   */
  advisory_number: number;
  /**
   * The action that was performed.
   * @type {string}
   * @memberof ActAdvisoryResponseDto
   */
  action: ActAdvisoryResponseDtoActionEnum;
  /**
   * Timestamp (ISO 8601) at which the action was performed.
   * @type {string}
   * @memberof ActAdvisoryResponseDto
   */
  timestamp: string;
}

/**
 * @export
 */
export const ActAdvisoryResponseDtoActionEnum = {
  Created: 'created',
  Updated: 'updated',
  Deleted: 'deleted',
} as const;
export type ActAdvisoryResponseDtoActionEnum =
  (typeof ActAdvisoryResponseDtoActionEnum)[keyof typeof ActAdvisoryResponseDtoActionEnum];

/**
 * Check if a given object implements the ActAdvisoryResponseDto interface.
 */
export function instanceOfActAdvisoryResponseDto(
  value: object,
): value is ActAdvisoryResponseDto {
  if (!('rec_resource_id' in value) || value['rec_resource_id'] === undefined)
    return false;
  if (!('advisory_number' in value) || value['advisory_number'] === undefined)
    return false;
  if (!('action' in value) || value['action'] === undefined) return false;
  if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
  return true;
}

export function ActAdvisoryResponseDtoFromJSON(
  json: any,
): ActAdvisoryResponseDto {
  return ActAdvisoryResponseDtoFromJSONTyped(json, false);
}

export function ActAdvisoryResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActAdvisoryResponseDto {
  if (json == null) {
    return json;
  }
  return {
    rec_resource_id: json['rec_resource_id'],
    advisory_number: json['advisory_number'],
    action: json['action'],
    timestamp: json['timestamp'],
  };
}

export function ActAdvisoryResponseDtoToJSON(
  json: any,
): ActAdvisoryResponseDto {
  return ActAdvisoryResponseDtoToJSONTyped(json, false);
}

export function ActAdvisoryResponseDtoToJSONTyped(
  value?: ActAdvisoryResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    rec_resource_id: value['rec_resource_id'],
    advisory_number: value['advisory_number'],
    action: value['action'],
    timestamp: value['timestamp'],
  };
}
