/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSearchResultRowDto } from './AdminSearchResultRowDto';
import {
  AdminSearchResultRowDtoFromJSON,
  AdminSearchResultRowDtoFromJSONTyped,
  AdminSearchResultRowDtoToJSON,
  AdminSearchResultRowDtoToJSONTyped,
} from './AdminSearchResultRowDto';

/**
 *
 * @export
 * @interface AdminSearchResponseDto
 */
export interface AdminSearchResponseDto {
  /**
   * Search result rows
   * @type {Array<AdminSearchResultRowDto>}
   * @memberof AdminSearchResponseDto
   */
  data: Array<AdminSearchResultRowDto>;
  /**
   * Total number of matching resources
   * @type {number}
   * @memberof AdminSearchResponseDto
   */
  total: number;
  /**
   * Current page number
   * @type {number}
   * @memberof AdminSearchResponseDto
   */
  page: number;
  /**
   * Page size used for the response
   * @type {number}
   * @memberof AdminSearchResponseDto
   */
  page_size: number;
}

/**
 * Check if a given object implements the AdminSearchResponseDto interface.
 */
export function instanceOfAdminSearchResponseDto(
  value: object,
): value is AdminSearchResponseDto {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('total' in value) || value['total'] === undefined) return false;
  if (!('page' in value) || value['page'] === undefined) return false;
  if (!('page_size' in value) || value['page_size'] === undefined) return false;
  return true;
}

export function AdminSearchResponseDtoFromJSON(
  json: any,
): AdminSearchResponseDto {
  return AdminSearchResponseDtoFromJSONTyped(json, false);
}

export function AdminSearchResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminSearchResponseDto {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(AdminSearchResultRowDtoFromJSON),
    total: json['total'],
    page: json['page'],
    page_size: json['page_size'],
  };
}

export function AdminSearchResponseDtoToJSON(
  json: any,
): AdminSearchResponseDto {
  return AdminSearchResponseDtoToJSONTyped(json, false);
}

export function AdminSearchResponseDtoToJSONTyped(
  value?: AdminSearchResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(AdminSearchResultRowDtoToJSON),
    total: value['total'],
    page: value['page'],
    page_size: value['page_size'],
  };
}
