/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AgreementHolderClientPublicViewDto
 */
export interface AgreementHolderClientPublicViewDto {
  /**
   *
   */
  clientNumber?: string;
  /**
   *
   */
  clientName?: string;
  /**
   *
   */
  legalFirstName?: string;
  /**
   *
   */
  legalMiddleName?: string;
  /**
   *
   */
  clientStatusCode?: string;
  /**
   *
   */
  clientStatusDescription?: string;
  /**
   *
   */
  clientTypeCode?: string;
  /**
   *
   */
  clientTypeDescription?: string;
  /**
   *
   */
  acronym?: string;
  /**
   *
   */
  agreementStartDate?: string;
  /**
   *
   */
  agreementEndDate?: string;
  /**
   *
   * @type {boolean}
   * @memberof AgreementHolderClientPublicViewDto
   */
  visible_on_public_website?: boolean;
  /**
   *
   * @type {string}
   * @memberof AgreementHolderClientPublicViewDto
   */
  partner_relationship_type_code?: string;
}

/**
 * Check if a given object implements the AgreementHolderClientPublicViewDto interface.
 */
export function instanceOfAgreementHolderClientPublicViewDto(
  value: object,
): value is AgreementHolderClientPublicViewDto {
  return true;
}

export function AgreementHolderClientPublicViewDtoFromJSON(
  json: any,
): AgreementHolderClientPublicViewDto {
  return AgreementHolderClientPublicViewDtoFromJSONTyped(json, false);
}

export function AgreementHolderClientPublicViewDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AgreementHolderClientPublicViewDto {
  if (json == null) {
    return json;
  }
  return {
    clientNumber:
      json['clientNumber'] == null ? undefined : json['clientNumber'],
    clientName: json['clientName'] == null ? undefined : json['clientName'],
    legalFirstName:
      json['legalFirstName'] == null ? undefined : json['legalFirstName'],
    legalMiddleName:
      json['legalMiddleName'] == null ? undefined : json['legalMiddleName'],
    clientStatusCode:
      json['clientStatusCode'] == null ? undefined : json['clientStatusCode'],
    clientStatusDescription:
      json['clientStatusDescription'] == null
        ? undefined
        : json['clientStatusDescription'],
    clientTypeCode:
      json['clientTypeCode'] == null ? undefined : json['clientTypeCode'],
    clientTypeDescription:
      json['clientTypeDescription'] == null
        ? undefined
        : json['clientTypeDescription'],
    acronym: json['acronym'] == null ? undefined : json['acronym'],
    agreementStartDate:
      json['agreementStartDate'] == null
        ? undefined
        : json['agreementStartDate'],
    agreementEndDate:
      json['agreementEndDate'] == null ? undefined : json['agreementEndDate'],
    visible_on_public_website:
      json['visible_on_public_website'] == null
        ? undefined
        : json['visible_on_public_website'],
    partner_relationship_type_code:
      json['partner_relationship_type_code'] == null
        ? undefined
        : json['partner_relationship_type_code'],
  };
}

export function AgreementHolderClientPublicViewDtoToJSON(
  json: any,
): AgreementHolderClientPublicViewDto {
  return AgreementHolderClientPublicViewDtoToJSONTyped(json, false);
}

export function AgreementHolderClientPublicViewDtoToJSONTyped(
  value?: AgreementHolderClientPublicViewDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clientNumber: value['clientNumber'],
    clientName: value['clientName'],
    legalFirstName: value['legalFirstName'],
    legalMiddleName: value['legalMiddleName'],
    clientStatusCode: value['clientStatusCode'],
    clientStatusDescription: value['clientStatusDescription'],
    clientTypeCode: value['clientTypeCode'],
    clientTypeDescription: value['clientTypeDescription'],
    acronym: value['acronym'],
    agreementStartDate: value['agreementStartDate'],
    agreementEndDate: value['agreementEndDate'],
    visible_on_public_website: value['visible_on_public_website'],
    partner_relationship_type_code: value['partner_relationship_type_code'],
  };
}
