/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BcgwRecreationResourceDto } from './BcgwRecreationResourceDto';
import {
  BcgwRecreationResourceDtoFromJSON,
  BcgwRecreationResourceDtoFromJSONTyped,
  BcgwRecreationResourceDtoToJSON,
  BcgwRecreationResourceDtoToJSONTyped,
} from './BcgwRecreationResourceDto';

/**
 *
 * @export
 * @interface BcgwFeatureDto
 */
export interface BcgwFeatureDto {
  /**
   *
   * @type {string}
   * @memberof BcgwFeatureDto
   */
  type: string;
  /**
   * GeoJSON Point geometry (WGS84), null when no site point exists
   * @type {object}
   * @memberof BcgwFeatureDto
   */
  geometry: object | null;
  /**
   *
   * @type {BcgwRecreationResourceDto}
   * @memberof BcgwFeatureDto
   */
  properties: BcgwRecreationResourceDto;
}

/**
 * Check if a given object implements the BcgwFeatureDto interface.
 */
export function instanceOfBcgwFeatureDto(
  value: object,
): value is BcgwFeatureDto {
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('geometry' in value) || value['geometry'] === undefined) return false;
  if (!('properties' in value) || value['properties'] === undefined)
    return false;
  return true;
}

export function BcgwFeatureDtoFromJSON(json: any): BcgwFeatureDto {
  return BcgwFeatureDtoFromJSONTyped(json, false);
}

export function BcgwFeatureDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BcgwFeatureDto {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'],
    geometry: json['geometry'],
    properties: BcgwRecreationResourceDtoFromJSON(json['properties']),
  };
}

export function BcgwFeatureDtoToJSON(json: any): BcgwFeatureDto {
  return BcgwFeatureDtoToJSONTyped(json, false);
}

export function BcgwFeatureDtoToJSONTyped(
  value?: BcgwFeatureDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    geometry: value['geometry'],
    properties: BcgwRecreationResourceDtoToJSON(value['properties']),
  };
}
