/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BcgwRecreationPolygonsDto
 */
export interface BcgwRecreationPolygonsDto {
  /**
   * The number of times a feature has been amended over its lifetime.
   * @type {number}
   * @memberof BcgwRecreationPolygonsDto
   */
  amendment_id: number | null;
  /**
   * The closest town or city to the recreation feature, e.g., KELOWNA, BELLA COOLA.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  site_location: string | null;
  /**
   * For a retired recreation feature, the date and time the feature was retired.
   * @type {Date}
   * @memberof BcgwRecreationPolygonsDto
   */
  retirement_date: Date | null;
  /**
   * Indicates whether this is a resource feature established under the Government Action Regulation.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  resource_feature_ind: BcgwRecreationPolygonsDtoResourceFeatureIndEnum | null;
  /**
   * Indicates if an archaeological impact assessment has been performed for the given project.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  arch_impact_assess_ind: BcgwRecreationPolygonsDtoArchImpactAssessIndEnum | null;
  /**
   * The date on which the recreation project was legally established.
   * @type {Date}
   * @memberof BcgwRecreationPolygonsDto
   */
  project_established_date: Date | null;
  /**
   *
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  recreation_view_ind: BcgwRecreationPolygonsDtoRecreationViewIndEnum | null;
  /**
   * The total number of campsites.
   * @type {number}
   * @memberof BcgwRecreationPolygonsDto
   */
  defined_campsites: number;
  /**
   * The life cycle state of the feature.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  life_cycle_status_code: BcgwRecreationPolygonsDtoLifeCycleStatusCodeEnum | null;
  /**
   * The current status of the recreation tenure, e.g., AR (archived), HI (issued), PI (pending issuance).
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  file_status_code: string | null;
  /**
   * The unique identifier (SKEY) for the Recreation Map Feature.
   * @type {number}
   * @memberof BcgwRecreationPolygonsDto
   */
  rmf_skey: number;
  /**
   * An identifier assigned to the recreation file, e.g., REC230971.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  forest_file_id: string;
  /**
   * An identifier assigned to a section of a recreation feature. Not used for polygon features.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  section_id: string | null;
  /**
   * Code that identifies the type of recreation feature, e.g., IF (interpretive forest), RR (recreation reserve), SIT (recreation site).
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  recreation_map_feature_code: string | null;
  /**
   * Description of the type of recreation feature, e.g., Interpretative Forest, Recreation Reserve.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  project_type: string | null;
  /**
   * The default label used when displaying the feature on a map, consisting of the FOREST FILE ID only, e.g., REC230971.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  map_label: string | null;
  /**
   * The name of the recreation project, e.g., KASLO INTERPRETIVE FOREST.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  project_name: string | null;
  /**
   * Code describing the type of natural or man-made recreation feature, e.g., E5 (mixed forest), H3 (historic site).
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  recreation_feature_code: string | null;
  /**
   * A comma-separated list of codes relating to the recreation districts that the feature is within, e.g., RDCC,RDCS.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  recreation_district_code: string | null;
  /**
   * The code of the natural resource district associated with this feature.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  geographic_district_code: string | null;
  /**
   * The name of the natural resource district associated with this feature.
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  geographic_district_name: string | null;
  /**
   * Spatial feature area in hectares. Calculated in the source system.
   * @type {number}
   * @memberof BcgwRecreationPolygonsDto
   */
  feature_area: number | null;
  /**
   * Spatial perimeter length in kilometres. Calculated in the source system.
   * @type {number}
   * @memberof BcgwRecreationPolygonsDto
   */
  feature_perimeter: number | null;
  /**
   * The system-calculated area of the polygon in square metres (returned as a string, matching BCGW VARCHAR2 type).
   * @type {string}
   * @memberof BcgwRecreationPolygonsDto
   */
  feature_area_sqm: string | null;
  /**
   * The system-calculated perimeter of the polygon in metres.
   * @type {number}
   * @memberof BcgwRecreationPolygonsDto
   */
  feature_length_m: number | null;
}

/**
 * @export
 */
export const BcgwRecreationPolygonsDtoResourceFeatureIndEnum = {
  Y: 'Y',
  N: 'N',
} as const;
export type BcgwRecreationPolygonsDtoResourceFeatureIndEnum =
  (typeof BcgwRecreationPolygonsDtoResourceFeatureIndEnum)[keyof typeof BcgwRecreationPolygonsDtoResourceFeatureIndEnum];

/**
 * @export
 */
export const BcgwRecreationPolygonsDtoArchImpactAssessIndEnum = {
  Y: 'Y',
  N: 'N',
} as const;
export type BcgwRecreationPolygonsDtoArchImpactAssessIndEnum =
  (typeof BcgwRecreationPolygonsDtoArchImpactAssessIndEnum)[keyof typeof BcgwRecreationPolygonsDtoArchImpactAssessIndEnum];

/**
 * @export
 */
export const BcgwRecreationPolygonsDtoRecreationViewIndEnum = {
  Y: 'Y',
  N: 'N',
} as const;
export type BcgwRecreationPolygonsDtoRecreationViewIndEnum =
  (typeof BcgwRecreationPolygonsDtoRecreationViewIndEnum)[keyof typeof BcgwRecreationPolygonsDtoRecreationViewIndEnum];

/**
 * @export
 */
export const BcgwRecreationPolygonsDtoLifeCycleStatusCodeEnum = {
  Pending: 'PENDING',
  Active: 'ACTIVE',
  Retired: 'RETIRED',
} as const;
export type BcgwRecreationPolygonsDtoLifeCycleStatusCodeEnum =
  (typeof BcgwRecreationPolygonsDtoLifeCycleStatusCodeEnum)[keyof typeof BcgwRecreationPolygonsDtoLifeCycleStatusCodeEnum];

/**
 * Check if a given object implements the BcgwRecreationPolygonsDto interface.
 */
export function instanceOfBcgwRecreationPolygonsDto(
  value: object,
): value is BcgwRecreationPolygonsDto {
  if (!('amendment_id' in value) || value['amendment_id'] === undefined)
    return false;
  if (!('site_location' in value) || value['site_location'] === undefined)
    return false;
  if (!('retirement_date' in value) || value['retirement_date'] === undefined)
    return false;
  if (
    !('resource_feature_ind' in value) ||
    value['resource_feature_ind'] === undefined
  )
    return false;
  if (
    !('arch_impact_assess_ind' in value) ||
    value['arch_impact_assess_ind'] === undefined
  )
    return false;
  if (
    !('project_established_date' in value) ||
    value['project_established_date'] === undefined
  )
    return false;
  if (
    !('recreation_view_ind' in value) ||
    value['recreation_view_ind'] === undefined
  )
    return false;
  if (
    !('defined_campsites' in value) ||
    value['defined_campsites'] === undefined
  )
    return false;
  if (
    !('life_cycle_status_code' in value) ||
    value['life_cycle_status_code'] === undefined
  )
    return false;
  if (!('file_status_code' in value) || value['file_status_code'] === undefined)
    return false;
  if (!('rmf_skey' in value) || value['rmf_skey'] === undefined) return false;
  if (!('forest_file_id' in value) || value['forest_file_id'] === undefined)
    return false;
  if (!('section_id' in value) || value['section_id'] === undefined)
    return false;
  if (
    !('recreation_map_feature_code' in value) ||
    value['recreation_map_feature_code'] === undefined
  )
    return false;
  if (!('project_type' in value) || value['project_type'] === undefined)
    return false;
  if (!('map_label' in value) || value['map_label'] === undefined) return false;
  if (!('project_name' in value) || value['project_name'] === undefined)
    return false;
  if (
    !('recreation_feature_code' in value) ||
    value['recreation_feature_code'] === undefined
  )
    return false;
  if (
    !('recreation_district_code' in value) ||
    value['recreation_district_code'] === undefined
  )
    return false;
  if (
    !('geographic_district_code' in value) ||
    value['geographic_district_code'] === undefined
  )
    return false;
  if (
    !('geographic_district_name' in value) ||
    value['geographic_district_name'] === undefined
  )
    return false;
  if (!('feature_area' in value) || value['feature_area'] === undefined)
    return false;
  if (
    !('feature_perimeter' in value) ||
    value['feature_perimeter'] === undefined
  )
    return false;
  if (!('feature_area_sqm' in value) || value['feature_area_sqm'] === undefined)
    return false;
  if (!('feature_length_m' in value) || value['feature_length_m'] === undefined)
    return false;
  return true;
}

export function BcgwRecreationPolygonsDtoFromJSON(
  json: any,
): BcgwRecreationPolygonsDto {
  return BcgwRecreationPolygonsDtoFromJSONTyped(json, false);
}

export function BcgwRecreationPolygonsDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BcgwRecreationPolygonsDto {
  if (json == null) {
    return json;
  }
  return {
    amendment_id: json['amendment_id'],
    site_location: json['site_location'],
    retirement_date:
      json['retirement_date'] == null
        ? null
        : new Date(json['retirement_date']),
    resource_feature_ind: json['resource_feature_ind'],
    arch_impact_assess_ind: json['arch_impact_assess_ind'],
    project_established_date:
      json['project_established_date'] == null
        ? null
        : new Date(json['project_established_date']),
    recreation_view_ind: json['recreation_view_ind'],
    defined_campsites: json['defined_campsites'],
    life_cycle_status_code: json['life_cycle_status_code'],
    file_status_code: json['file_status_code'],
    rmf_skey: json['rmf_skey'],
    forest_file_id: json['forest_file_id'],
    section_id: json['section_id'],
    recreation_map_feature_code: json['recreation_map_feature_code'],
    project_type: json['project_type'],
    map_label: json['map_label'],
    project_name: json['project_name'],
    recreation_feature_code: json['recreation_feature_code'],
    recreation_district_code: json['recreation_district_code'],
    geographic_district_code: json['geographic_district_code'],
    geographic_district_name: json['geographic_district_name'],
    feature_area: json['feature_area'],
    feature_perimeter: json['feature_perimeter'],
    feature_area_sqm: json['feature_area_sqm'],
    feature_length_m: json['feature_length_m'],
  };
}

export function BcgwRecreationPolygonsDtoToJSON(
  json: any,
): BcgwRecreationPolygonsDto {
  return BcgwRecreationPolygonsDtoToJSONTyped(json, false);
}

export function BcgwRecreationPolygonsDtoToJSONTyped(
  value?: BcgwRecreationPolygonsDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amendment_id: value['amendment_id'],
    site_location: value['site_location'],
    retirement_date: (value['retirement_date'] as any)
      .toISOString()
      .substring(0, 10),
    resource_feature_ind: value['resource_feature_ind'],
    arch_impact_assess_ind: value['arch_impact_assess_ind'],
    project_established_date: (value['project_established_date'] as any)
      .toISOString()
      .substring(0, 10),
    recreation_view_ind: value['recreation_view_ind'],
    defined_campsites: value['defined_campsites'],
    life_cycle_status_code: value['life_cycle_status_code'],
    file_status_code: value['file_status_code'],
    rmf_skey: value['rmf_skey'],
    forest_file_id: value['forest_file_id'],
    section_id: value['section_id'],
    recreation_map_feature_code: value['recreation_map_feature_code'],
    project_type: value['project_type'],
    map_label: value['map_label'],
    project_name: value['project_name'],
    recreation_feature_code: value['recreation_feature_code'],
    recreation_district_code: value['recreation_district_code'],
    geographic_district_code: value['geographic_district_code'],
    geographic_district_name: value['geographic_district_name'],
    feature_area: value['feature_area'],
    feature_perimeter: value['feature_perimeter'],
    feature_area_sqm: value['feature_area_sqm'],
    feature_length_m: value['feature_length_m'],
  };
}
