/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BcgwRecreationLinesDto } from './BcgwRecreationLinesDto';
import {
  BcgwRecreationLinesDtoFromJSON,
  BcgwRecreationLinesDtoFromJSONTyped,
  BcgwRecreationLinesDtoToJSON,
  BcgwRecreationLinesDtoToJSONTyped,
} from './BcgwRecreationLinesDto';

/**
 *
 * @export
 * @interface BcgwRecreationLinesFeatureDto
 */
export interface BcgwRecreationLinesFeatureDto {
  /**
   *
   * @type {string}
   * @memberof BcgwRecreationLinesFeatureDto
   */
  type: string;
  /**
   * GeoJSON LineString geometry (WGS84), null when no geometry exists.
   * @type {object}
   * @memberof BcgwRecreationLinesFeatureDto
   */
  geometry: object | null;
  /**
   *
   * @type {BcgwRecreationLinesDto}
   * @memberof BcgwRecreationLinesFeatureDto
   */
  properties: BcgwRecreationLinesDto;
}

/**
 * Check if a given object implements the BcgwRecreationLinesFeatureDto interface.
 */
export function instanceOfBcgwRecreationLinesFeatureDto(
  value: object,
): value is BcgwRecreationLinesFeatureDto {
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('geometry' in value) || value['geometry'] === undefined) return false;
  if (!('properties' in value) || value['properties'] === undefined)
    return false;
  return true;
}

export function BcgwRecreationLinesFeatureDtoFromJSON(
  json: any,
): BcgwRecreationLinesFeatureDto {
  return BcgwRecreationLinesFeatureDtoFromJSONTyped(json, false);
}

export function BcgwRecreationLinesFeatureDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BcgwRecreationLinesFeatureDto {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'],
    geometry: json['geometry'],
    properties: BcgwRecreationLinesDtoFromJSON(json['properties']),
  };
}

export function BcgwRecreationLinesFeatureDtoToJSON(
  json: any,
): BcgwRecreationLinesFeatureDto {
  return BcgwRecreationLinesFeatureDtoToJSONTyped(json, false);
}

export function BcgwRecreationLinesFeatureDtoToJSONTyped(
  value?: BcgwRecreationLinesFeatureDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    geometry: value['geometry'],
    properties: BcgwRecreationLinesDtoToJSON(value['properties']),
  };
}
