/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BcgwPaginationMetaDto } from './BcgwPaginationMetaDto';
import {
  BcgwPaginationMetaDtoFromJSON,
  BcgwPaginationMetaDtoFromJSONTyped,
  BcgwPaginationMetaDtoToJSON,
  BcgwPaginationMetaDtoToJSONTyped,
} from './BcgwPaginationMetaDto';
import type { BcgwRecreationLinesFeatureDto } from './BcgwRecreationLinesFeatureDto';
import {
  BcgwRecreationLinesFeatureDtoFromJSON,
  BcgwRecreationLinesFeatureDtoFromJSONTyped,
  BcgwRecreationLinesFeatureDtoToJSON,
  BcgwRecreationLinesFeatureDtoToJSONTyped,
} from './BcgwRecreationLinesFeatureDto';

/**
 *
 * @export
 * @interface BcgwRecreationLinesFeatureCollectionDto
 */
export interface BcgwRecreationLinesFeatureCollectionDto {
  /**
   *
   * @type {string}
   * @memberof BcgwRecreationLinesFeatureCollectionDto
   */
  type: string;
  /**
   * Array of GeoJSON Feature objects
   * @type {Array<BcgwRecreationLinesFeatureDto>}
   * @memberof BcgwRecreationLinesFeatureCollectionDto
   */
  features: Array<BcgwRecreationLinesFeatureDto>;
  /**
   *
   * @type {BcgwPaginationMetaDto}
   * @memberof BcgwRecreationLinesFeatureCollectionDto
   */
  meta: BcgwPaginationMetaDto;
}

/**
 * Check if a given object implements the BcgwRecreationLinesFeatureCollectionDto interface.
 */
export function instanceOfBcgwRecreationLinesFeatureCollectionDto(
  value: object,
): value is BcgwRecreationLinesFeatureCollectionDto {
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('features' in value) || value['features'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function BcgwRecreationLinesFeatureCollectionDtoFromJSON(
  json: any,
): BcgwRecreationLinesFeatureCollectionDto {
  return BcgwRecreationLinesFeatureCollectionDtoFromJSONTyped(json, false);
}

export function BcgwRecreationLinesFeatureCollectionDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BcgwRecreationLinesFeatureCollectionDto {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'],
    features: (json['features'] as Array<any>).map(
      BcgwRecreationLinesFeatureDtoFromJSON,
    ),
    meta: BcgwPaginationMetaDtoFromJSON(json['meta']),
  };
}

export function BcgwRecreationLinesFeatureCollectionDtoToJSON(
  json: any,
): BcgwRecreationLinesFeatureCollectionDto {
  return BcgwRecreationLinesFeatureCollectionDtoToJSONTyped(json, false);
}

export function BcgwRecreationLinesFeatureCollectionDtoToJSONTyped(
  value?: BcgwRecreationLinesFeatureCollectionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    features: (value['features'] as Array<any>).map(
      BcgwRecreationLinesFeatureDtoToJSON,
    ),
    meta: BcgwPaginationMetaDtoToJSON(value['meta']),
  };
}
