/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BcgwPaginationMetaDto
 */
export interface BcgwPaginationMetaDto {
  /**
   *
   * @type {number}
   * @memberof BcgwPaginationMetaDto
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof BcgwPaginationMetaDto
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof BcgwPaginationMetaDto
   */
  totalPages: number;
  /**
   *
   * @type {number}
   * @memberof BcgwPaginationMetaDto
   */
  pageSize: number;
}

/**
 * Check if a given object implements the BcgwPaginationMetaDto interface.
 */
export function instanceOfBcgwPaginationMetaDto(
  value: object,
): value is BcgwPaginationMetaDto {
  if (!('total' in value) || value['total'] === undefined) return false;
  if (!('page' in value) || value['page'] === undefined) return false;
  if (!('totalPages' in value) || value['totalPages'] === undefined)
    return false;
  if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
  return true;
}

export function BcgwPaginationMetaDtoFromJSON(
  json: any,
): BcgwPaginationMetaDto {
  return BcgwPaginationMetaDtoFromJSONTyped(json, false);
}

export function BcgwPaginationMetaDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BcgwPaginationMetaDto {
  if (json == null) {
    return json;
  }
  return {
    total: json['total'],
    page: json['page'],
    totalPages: json['totalPages'],
    pageSize: json['pageSize'],
  };
}

export function BcgwPaginationMetaDtoToJSON(json: any): BcgwPaginationMetaDto {
  return BcgwPaginationMetaDtoToJSONTyped(json, false);
}

export function BcgwPaginationMetaDtoToJSONTyped(
  value?: BcgwPaginationMetaDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    total: value['total'],
    page: value['page'],
    totalPages: value['totalPages'],
    pageSize: value['pageSize'],
  };
}
