/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  mapValues,
  parseDate,
  parseDateTime,
  serializeDate,
  serializeDateTime,
} from '../runtime';
/**
 *
 * @export
 * @interface BcgwClosuresShortDto
 */
export interface BcgwClosuresShortDto {
  /**
   *
   */
  forest_file_id: string;
  /**
   *
   */
  project_name: string | null;
  /**
   *
   */
  project_type: string | null;
  /**
   *
   */
  closure_ind: BcgwClosuresShortDtoClosureIndEnum;
  /**
   *
   */
  closure_date: Date | null;
  /**
   *
   */
  closure_type: string | null;
  /**
   *
   */
  site_location: string | null;
  /**
   *
   */
  defined_campsites: number;
  /**
   *
   */
  recreation_district_code: string | null;
  /**
   *
   */
  recreation_district_name: string | null;
  /**
   *
   */
  org_unit_name: string | null;
  /**
   *
   */
  closure_comment: string | null;
  /**
   *
   */
  site_description: string | null;
  /**
   *
   */
  driving_directions: string | null;
  /**
   * Latitude in decimal degrees (WGS84)
   */
  latitude: number | null;
  /**
   * Longitude in decimal degrees (WGS84)
   */
  longitude: number | null;
  /**
   * GeoJSON Point geometry (WGS84)
   */
  shape: string | null;
}

/**
 * @export
 */
export const BcgwClosuresShortDtoClosureIndEnum = {
  Y: 'Y',
  N: 'N',
} as const;
export type BcgwClosuresShortDtoClosureIndEnum =
  (typeof BcgwClosuresShortDtoClosureIndEnum)[keyof typeof BcgwClosuresShortDtoClosureIndEnum];

/**
 * Check if a given object implements the BcgwClosuresShortDto interface.
 */
export function instanceOfBcgwClosuresShortDto(
  value: object,
): value is BcgwClosuresShortDto {
  if (!('forest_file_id' in value) || value['forest_file_id'] === undefined)
    return false;
  if (!('project_name' in value) || value['project_name'] === undefined)
    return false;
  if (!('project_type' in value) || value['project_type'] === undefined)
    return false;
  if (!('closure_ind' in value) || value['closure_ind'] === undefined)
    return false;
  if (!('closure_date' in value) || value['closure_date'] === undefined)
    return false;
  if (!('closure_type' in value) || value['closure_type'] === undefined)
    return false;
  if (!('site_location' in value) || value['site_location'] === undefined)
    return false;
  if (
    !('defined_campsites' in value) ||
    value['defined_campsites'] === undefined
  )
    return false;
  if (
    !('recreation_district_code' in value) ||
    value['recreation_district_code'] === undefined
  )
    return false;
  if (
    !('recreation_district_name' in value) ||
    value['recreation_district_name'] === undefined
  )
    return false;
  if (!('org_unit_name' in value) || value['org_unit_name'] === undefined)
    return false;
  if (!('closure_comment' in value) || value['closure_comment'] === undefined)
    return false;
  if (!('site_description' in value) || value['site_description'] === undefined)
    return false;
  if (
    !('driving_directions' in value) ||
    value['driving_directions'] === undefined
  )
    return false;
  if (!('latitude' in value) || value['latitude'] === undefined) return false;
  if (!('longitude' in value) || value['longitude'] === undefined) return false;
  if (!('shape' in value) || value['shape'] === undefined) return false;
  return true;
}

export function BcgwClosuresShortDtoFromJSON(json: any): BcgwClosuresShortDto {
  return BcgwClosuresShortDtoFromJSONTyped(json, false);
}

export function BcgwClosuresShortDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BcgwClosuresShortDto {
  if (json == null) {
    return json;
  }
  return {
    forest_file_id: json['forest_file_id'],
    project_name: json['project_name'],
    project_type: json['project_type'],
    closure_ind: json['closure_ind'],
    closure_date:
      json['closure_date'] == null ? null : parseDate(json['closure_date']),
    closure_type: json['closure_type'],
    site_location: json['site_location'],
    defined_campsites: json['defined_campsites'],
    recreation_district_code: json['recreation_district_code'],
    recreation_district_name: json['recreation_district_name'],
    org_unit_name: json['org_unit_name'],
    closure_comment: json['closure_comment'],
    site_description: json['site_description'],
    driving_directions: json['driving_directions'],
    latitude: json['latitude'],
    longitude: json['longitude'],
    shape: json['shape'],
  };
}

export function BcgwClosuresShortDtoToJSON(json: any): BcgwClosuresShortDto {
  return BcgwClosuresShortDtoToJSONTyped(json, false);
}

export function BcgwClosuresShortDtoToJSONTyped(
  value?: BcgwClosuresShortDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    forest_file_id: value['forest_file_id'],
    project_name: value['project_name'],
    project_type: value['project_type'],
    closure_ind: value['closure_ind'],
    closure_date:
      value['closure_date'] == null
        ? value['closure_date']
        : serializeDate(value['closure_date']),
    closure_type: value['closure_type'],
    site_location: value['site_location'],
    defined_campsites: value['defined_campsites'],
    recreation_district_code: value['recreation_district_code'],
    recreation_district_name: value['recreation_district_name'],
    org_unit_name: value['org_unit_name'],
    closure_comment: value['closure_comment'],
    site_description: value['site_description'],
    driving_directions: value['driving_directions'],
    latitude: value['latitude'],
    longitude: value['longitude'],
    shape: value['shape'],
  };
}
