/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ClientLocationDto
 */
export interface ClientLocationDto {
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  clientNumber?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  clientName?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  legalFirstName?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  legalMiddleName?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  clientStatusCode?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  clientStatusDescription?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  clientTypeCode?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  clientTypeDescription?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  acronym?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  locationCode?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  locationName?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  companyCode?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  address1?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  address2?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  address3?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  city?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  province?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  postalCode?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  country?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  homePhone?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  businessPhone?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  cellPhone?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  faxNumber?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  expired?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  trusted?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  returnedMailDate?: string;
  /**
   *
   * @type {string}
   * @memberof ClientLocationDto
   */
  comment?: string;
}

/**
 * Check if a given object implements the ClientLocationDto interface.
 */
export function instanceOfClientLocationDto(
  value: object,
): value is ClientLocationDto {
  return true;
}

export function ClientLocationDtoFromJSON(json: any): ClientLocationDto {
  return ClientLocationDtoFromJSONTyped(json, false);
}

export function ClientLocationDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClientLocationDto {
  if (json == null) {
    return json;
  }
  return {
    clientNumber:
      json['clientNumber'] == null ? undefined : json['clientNumber'],
    clientName: json['clientName'] == null ? undefined : json['clientName'],
    legalFirstName:
      json['legalFirstName'] == null ? undefined : json['legalFirstName'],
    legalMiddleName:
      json['legalMiddleName'] == null ? undefined : json['legalMiddleName'],
    clientStatusCode:
      json['clientStatusCode'] == null ? undefined : json['clientStatusCode'],
    clientStatusDescription:
      json['clientStatusDescription'] == null
        ? undefined
        : json['clientStatusDescription'],
    clientTypeCode:
      json['clientTypeCode'] == null ? undefined : json['clientTypeCode'],
    clientTypeDescription:
      json['clientTypeDescription'] == null
        ? undefined
        : json['clientTypeDescription'],
    acronym: json['acronym'] == null ? undefined : json['acronym'],
    locationCode:
      json['locationCode'] == null ? undefined : json['locationCode'],
    locationName:
      json['locationName'] == null ? undefined : json['locationName'],
    companyCode: json['companyCode'] == null ? undefined : json['companyCode'],
    address1: json['address1'] == null ? undefined : json['address1'],
    address2: json['address2'] == null ? undefined : json['address2'],
    address3: json['address3'] == null ? undefined : json['address3'],
    city: json['city'] == null ? undefined : json['city'],
    province: json['province'] == null ? undefined : json['province'],
    postalCode: json['postalCode'] == null ? undefined : json['postalCode'],
    country: json['country'] == null ? undefined : json['country'],
    homePhone: json['homePhone'] == null ? undefined : json['homePhone'],
    businessPhone:
      json['businessPhone'] == null ? undefined : json['businessPhone'],
    cellPhone: json['cellPhone'] == null ? undefined : json['cellPhone'],
    faxNumber: json['faxNumber'] == null ? undefined : json['faxNumber'],
    email: json['email'] == null ? undefined : json['email'],
    expired: json['expired'] == null ? undefined : json['expired'],
    trusted: json['trusted'] == null ? undefined : json['trusted'],
    returnedMailDate:
      json['returnedMailDate'] == null ? undefined : json['returnedMailDate'],
    comment: json['comment'] == null ? undefined : json['comment'],
  };
}

export function ClientLocationDtoToJSON(json: any): ClientLocationDto {
  return ClientLocationDtoToJSONTyped(json, false);
}

export function ClientLocationDtoToJSONTyped(
  value?: ClientLocationDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clientNumber: value['clientNumber'],
    clientName: value['clientName'],
    legalFirstName: value['legalFirstName'],
    legalMiddleName: value['legalMiddleName'],
    clientStatusCode: value['clientStatusCode'],
    clientStatusDescription: value['clientStatusDescription'],
    clientTypeCode: value['clientTypeCode'],
    clientTypeDescription: value['clientTypeDescription'],
    acronym: value['acronym'],
    locationCode: value['locationCode'],
    locationName: value['locationName'],
    companyCode: value['companyCode'],
    address1: value['address1'],
    address2: value['address2'],
    address3: value['address3'],
    city: value['city'],
    province: value['province'],
    postalCode: value['postalCode'],
    country: value['country'],
    homePhone: value['homePhone'],
    businessPhone: value['businessPhone'],
    cellPhone: value['cellPhone'],
    faxNumber: value['faxNumber'],
    email: value['email'],
    expired: value['expired'],
    trusted: value['trusted'],
    returnedMailDate: value['returnedMailDate'],
    comment: value['comment'],
  };
}
