/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConsentFormDownloadResponseDto
 */
export interface ConsentFormDownloadResponseDto {
  /**
   * Presigned URL for downloading the consent form PDF
   * @type {string}
   * @memberof ConsentFormDownloadResponseDto
   */
  url: string;
}

/**
 * Check if a given object implements the ConsentFormDownloadResponseDto interface.
 */
export function instanceOfConsentFormDownloadResponseDto(
  value: object,
): value is ConsentFormDownloadResponseDto {
  if (!('url' in value) || value['url'] === undefined) return false;
  return true;
}

export function ConsentFormDownloadResponseDtoFromJSON(
  json: any,
): ConsentFormDownloadResponseDto {
  return ConsentFormDownloadResponseDtoFromJSONTyped(json, false);
}

export function ConsentFormDownloadResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConsentFormDownloadResponseDto {
  if (json == null) {
    return json;
  }
  return {
    url: json['url'],
  };
}

export function ConsentFormDownloadResponseDtoToJSON(
  json: any,
): ConsentFormDownloadResponseDto {
  return ConsentFormDownloadResponseDtoToJSONTyped(json, false);
}

export function ConsentFormDownloadResponseDtoToJSONTyped(
  value?: ConsentFormDownloadResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    url: value['url'],
  };
}
