/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConsentFormDto
 */
export interface ConsentFormDto {
  /**
   * Date the photo was taken (ISO date string)
   * @type {string}
   * @memberof ConsentFormDto
   */
  date_taken?: string;
  /**
   * Whether the image contains personally identifiable information
   * @type {boolean}
   * @memberof ConsentFormDto
   */
  contains_pii?: boolean;
  /**
   * Type of photographer (database code)
   * @type {string}
   * @memberof ConsentFormDto
   */
  photographer_type?: string;
  /**
   * Name of the photographer for attribution
   * @type {string}
   * @memberof ConsentFormDto
   */
  photographer_name?: string;
  /**
   * Consent form PDF file
   * @type {Blob}
   * @memberof ConsentFormDto
   */
  consent_form?: Blob;
}

/**
 * Check if a given object implements the ConsentFormDto interface.
 */
export function instanceOfConsentFormDto(
  value: object,
): value is ConsentFormDto {
  return true;
}

export function ConsentFormDtoFromJSON(json: any): ConsentFormDto {
  return ConsentFormDtoFromJSONTyped(json, false);
}

export function ConsentFormDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConsentFormDto {
  if (json == null) {
    return json;
  }
  return {
    date_taken: json['date_taken'] == null ? undefined : json['date_taken'],
    contains_pii:
      json['contains_pii'] == null ? undefined : json['contains_pii'],
    photographer_type:
      json['photographer_type'] == null ? undefined : json['photographer_type'],
    photographer_name:
      json['photographer_name'] == null ? undefined : json['photographer_name'],
    consent_form:
      json['consent_form'] == null ? undefined : json['consent_form'],
  };
}

export function ConsentFormDtoToJSON(json: any): ConsentFormDto {
  return ConsentFormDtoToJSONTyped(json, false);
}

export function ConsentFormDtoToJSONTyped(
  value?: ConsentFormDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    date_taken: value['date_taken'],
    contains_pii: value['contains_pii'],
    photographer_type: value['photographer_type'],
    photographer_name: value['photographer_name'],
    consent_form: value['consent_form'],
  };
}
