/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateAgreementHolderDto
 */
export interface CreateAgreementHolderDto {
  /**
   * Agreement start date in YYYY-MM-DD format
   */
  agreementStartDate?: string;
  /**
   * Agreement end date in YYYY-MM-DD format
   */
  agreementEndDate?: string;
  /**
   * Client number assigned to the recreation resource
   */
  clientNumber: string;
  /**
   * Whether the agreement holder is visible on the public website
   * @type {boolean}
   * @memberof CreateAgreementHolderDto
   */
  visible_on_public_website?: boolean;
  /**
   * Relationship type code for the agreement holder
   * @type {string}
   * @memberof CreateAgreementHolderDto
   */
  partner_relationship_type_code?: string;
}

/**
 * Check if a given object implements the CreateAgreementHolderDto interface.
 */
export function instanceOfCreateAgreementHolderDto(
  value: object,
): value is CreateAgreementHolderDto {
  if (!('clientNumber' in value) || value['clientNumber'] === undefined)
    return false;
  return true;
}

export function CreateAgreementHolderDtoFromJSON(
  json: any,
): CreateAgreementHolderDto {
  return CreateAgreementHolderDtoFromJSONTyped(json, false);
}

export function CreateAgreementHolderDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAgreementHolderDto {
  if (json == null) {
    return json;
  }
  return {
    agreementStartDate:
      json['agreementStartDate'] == null
        ? undefined
        : json['agreementStartDate'],
    agreementEndDate:
      json['agreementEndDate'] == null ? undefined : json['agreementEndDate'],
    clientNumber: json['clientNumber'],
    visible_on_public_website:
      json['visible_on_public_website'] == null
        ? undefined
        : json['visible_on_public_website'],
    partner_relationship_type_code:
      json['partner_relationship_type_code'] == null
        ? undefined
        : json['partner_relationship_type_code'],
  };
}

export function CreateAgreementHolderDtoToJSON(
  json: any,
): CreateAgreementHolderDto {
  return CreateAgreementHolderDtoToJSONTyped(json, false);
}

export function CreateAgreementHolderDtoToJSONTyped(
  value?: CreateAgreementHolderDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    agreementStartDate: value['agreementStartDate'],
    agreementEndDate: value['agreementEndDate'],
    clientNumber: value['clientNumber'],
    visible_on_public_website: value['visible_on_public_website'],
    partner_relationship_type_code: value['partner_relationship_type_code'],
  };
}
