/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExhibitADocDto
 */
export interface ExhibitADocDto {
  /**
   * Document UUID
   * @type {string}
   * @memberof ExhibitADocDto
   */
  document_id: string;
  /**
   * Recreation Resource ID
   * @type {string}
   * @memberof ExhibitADocDto
   */
  rec_resource_id: string;
  /**
   * File name without extension
   * @type {string}
   * @memberof ExhibitADocDto
   */
  file_name: string;
  /**
   * File extension
   * @type {string}
   * @memberof ExhibitADocDto
   */
  extension: string;
  /**
   * File size in bytes
   * @type {number}
   * @memberof ExhibitADocDto
   */
  file_size?: number;
  /**
   * S3 object key
   * @type {string}
   * @memberof ExhibitADocDto
   */
  s3_key: string;
  /**
   * Presigned download URL
   * @type {string}
   * @memberof ExhibitADocDto
   */
  url: string;
  /**
   * When the document was created
   * @type {Date}
   * @memberof ExhibitADocDto
   */
  created_at?: Date;
}

/**
 * Check if a given object implements the ExhibitADocDto interface.
 */
export function instanceOfExhibitADocDto(
  value: object,
): value is ExhibitADocDto {
  if (!('document_id' in value) || value['document_id'] === undefined)
    return false;
  if (!('rec_resource_id' in value) || value['rec_resource_id'] === undefined)
    return false;
  if (!('file_name' in value) || value['file_name'] === undefined) return false;
  if (!('extension' in value) || value['extension'] === undefined) return false;
  if (!('s3_key' in value) || value['s3_key'] === undefined) return false;
  if (!('url' in value) || value['url'] === undefined) return false;
  return true;
}

export function ExhibitADocDtoFromJSON(json: any): ExhibitADocDto {
  return ExhibitADocDtoFromJSONTyped(json, false);
}

export function ExhibitADocDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExhibitADocDto {
  if (json == null) {
    return json;
  }
  return {
    document_id: json['document_id'],
    rec_resource_id: json['rec_resource_id'],
    file_name: json['file_name'],
    extension: json['extension'],
    file_size: json['file_size'] == null ? undefined : json['file_size'],
    s3_key: json['s3_key'],
    url: json['url'],
    created_at:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
  };
}

export function ExhibitADocDtoToJSON(json: any): ExhibitADocDto {
  return ExhibitADocDtoToJSONTyped(json, false);
}

export function ExhibitADocDtoToJSONTyped(
  value?: ExhibitADocDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    document_id: value['document_id'],
    rec_resource_id: value['rec_resource_id'],
    file_name: value['file_name'],
    extension: value['extension'],
    file_size: value['file_size'],
    s3_key: value['s3_key'],
    url: value['url'],
    created_at:
      value['created_at'] == null
        ? undefined
        : value['created_at'].toISOString(),
  };
}
