/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExportPreviewResponseDto
 */
export interface ExportPreviewResponseDto {
  /**
   * Column names returned by the preview query
   * @type {Array<string>}
   * @memberof ExportPreviewResponseDto
   */
  columns: Array<string>;
  /**
   * Preview rows keyed by column name
   * @type {Array<{ [key: string]: string | null; }>}
   * @memberof ExportPreviewResponseDto
   */
  rows: Array<{ [key: string]: string | null }>;
}

/**
 * Check if a given object implements the ExportPreviewResponseDto interface.
 */
export function instanceOfExportPreviewResponseDto(
  value: object,
): value is ExportPreviewResponseDto {
  if (!('columns' in value) || value['columns'] === undefined) return false;
  if (!('rows' in value) || value['rows'] === undefined) return false;
  return true;
}

export function ExportPreviewResponseDtoFromJSON(
  json: any,
): ExportPreviewResponseDto {
  return ExportPreviewResponseDtoFromJSONTyped(json, false);
}

export function ExportPreviewResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExportPreviewResponseDto {
  if (json == null) {
    return json;
  }
  return {
    columns: json['columns'],
    rows: json['rows'],
  };
}

export function ExportPreviewResponseDtoToJSON(
  json: any,
): ExportPreviewResponseDto {
  return ExportPreviewResponseDtoToJSONTyped(json, false);
}

export function ExportPreviewResponseDtoToJSONTyped(
  value?: ExportPreviewResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    columns: value['columns'],
    rows: value['rows'],
  };
}
