/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptionDto } from './OptionDto';
import {
  OptionDtoFromJSON,
  OptionDtoFromJSONTyped,
  OptionDtoToJSON,
  OptionDtoToJSONTyped,
} from './OptionDto';

/**
 *
 * @export
 * @interface OptionsByTypeDto
 */
export interface OptionsByTypeDto {
  /**
   * Option type
   * @type {string}
   * @memberof OptionsByTypeDto
   */
  type: OptionsByTypeDtoTypeEnum;
  /**
   * Options for the provided type
   * @type {Array<OptionDto>}
   * @memberof OptionsByTypeDto
   */
  options: Array<OptionDto>;
}

/**
 * @export
 */
export const OptionsByTypeDtoTypeEnum = {
  Activities: 'activities',
  Access: 'access',
  SubAccess: 'sub-access',
  Maintenance: 'maintenance',
  ResourceType: 'resourceType',
  FeeType: 'feeType',
  FeatureCode: 'featureCode',
  RecreationStatus: 'recreationStatus',
  Structure: 'structure',
  ControlAccessCode: 'controlAccessCode',
  RiskRatingCode: 'riskRatingCode',
  District: 'district',
  PhotographerType: 'photographerType',
} as const;
export type OptionsByTypeDtoTypeEnum =
  (typeof OptionsByTypeDtoTypeEnum)[keyof typeof OptionsByTypeDtoTypeEnum];

/**
 * Check if a given object implements the OptionsByTypeDto interface.
 */
export function instanceOfOptionsByTypeDto(
  value: object,
): value is OptionsByTypeDto {
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('options' in value) || value['options'] === undefined) return false;
  return true;
}

export function OptionsByTypeDtoFromJSON(json: any): OptionsByTypeDto {
  return OptionsByTypeDtoFromJSONTyped(json, false);
}

export function OptionsByTypeDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OptionsByTypeDto {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'],
    options: (json['options'] as Array<any>).map(OptionDtoFromJSON),
  };
}

export function OptionsByTypeDtoToJSON(json: any): OptionsByTypeDto {
  return OptionsByTypeDtoToJSONTyped(json, false);
}

export function OptionsByTypeDtoToJSONTyped(
  value?: OptionsByTypeDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    options: (value['options'] as Array<any>).map(OptionDtoToJSON),
  };
}
