/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OptionDto
 */
export interface OptionDto {
  /**
   * Unique identifier for the option
   * @type {string}
   * @memberof OptionDto
   */
  id: string;
  /**
   * Human-readable label for the option
   * @type {string}
   * @memberof OptionDto
   */
  label: string;
  /**
   * Child options for hierarchical data (e.g., sub-access codes for access codes)
   * @type {Array<OptionDto>}
   * @memberof OptionDto
   */
  children?: Array<OptionDto>;
  /**
   * Indicates if the option is archived
   * @type {boolean}
   * @memberof OptionDto
   */
  is_archived?: boolean;
}

/**
 * Check if a given object implements the OptionDto interface.
 */
export function instanceOfOptionDto(value: object): value is OptionDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  return true;
}

export function OptionDtoFromJSON(json: any): OptionDto {
  return OptionDtoFromJSONTyped(json, false);
}

export function OptionDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OptionDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    label: json['label'],
    children:
      json['children'] == null
        ? undefined
        : (json['children'] as Array<any>).map(OptionDtoFromJSON),
    is_archived: json['is_archived'] == null ? undefined : json['is_archived'],
  };
}

export function OptionDtoToJSON(json: any): OptionDto {
  return OptionDtoToJSONTyped(json, false);
}

export function OptionDtoToJSONTyped(
  value?: OptionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    label: value['label'],
    children:
      value['children'] == null
        ? undefined
        : (value['children'] as Array<any>).map(OptionDtoToJSON),
    is_archived: value['is_archived'],
  };
}
