/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PendingMapFeatureRequestRowDto
 */
export interface PendingMapFeatureRequestRowDto {
  /**
   * Recreation resource identifier for the request
   * @type {string}
   * @memberof PendingMapFeatureRequestRowDto
   */
  rec_resource_id: string;
  /**
   * Resource name when available
   * @type {string}
   * @memberof PendingMapFeatureRequestRowDto
   */
  name?: string | null;
  /**
   * Recreation district description when available
   * @type {string}
   * @memberof PendingMapFeatureRequestRowDto
   */
  district_description?: string | null;
  /**
   * Recreation district description when available
   * @type {string}
   * @memberof PendingMapFeatureRequestRowDto
   */
  recreation_district?: string | null;
  /**
   * Natural resource district name when available
   * @type {string}
   * @memberof PendingMapFeatureRequestRowDto
   */
  natural_resource_district?: string | null;
  /**
   * Recreation resource type description(s) when available
   * @type {string}
   * @memberof PendingMapFeatureRequestRowDto
   */
  recreation_type?: string | null;
  /**
   * Request amend status code
   * @type {string}
   * @memberof PendingMapFeatureRequestRowDto
   */
  amend_status_code: string;
  /**
   * Number of map feature rows included in the request
   * @type {number}
   * @memberof PendingMapFeatureRequestRowDto
   */
  feature_count: number;
  /**
   * Latest request creation timestamp in ISO-8601 format
   * @type {string}
   * @memberof PendingMapFeatureRequestRowDto
   */
  requested_at?: string | null;
  /**
   * Distinct geometry types included in the request
   * @type {Array<string>}
   * @memberof PendingMapFeatureRequestRowDto
   */
  geometry_types: Array<string>;
}

/**
 * Check if a given object implements the PendingMapFeatureRequestRowDto interface.
 */
export function instanceOfPendingMapFeatureRequestRowDto(
  value: object,
): value is PendingMapFeatureRequestRowDto {
  if (!('rec_resource_id' in value) || value['rec_resource_id'] === undefined)
    return false;
  if (
    !('amend_status_code' in value) ||
    value['amend_status_code'] === undefined
  )
    return false;
  if (!('feature_count' in value) || value['feature_count'] === undefined)
    return false;
  if (!('geometry_types' in value) || value['geometry_types'] === undefined)
    return false;
  return true;
}

export function PendingMapFeatureRequestRowDtoFromJSON(
  json: any,
): PendingMapFeatureRequestRowDto {
  return PendingMapFeatureRequestRowDtoFromJSONTyped(json, false);
}

export function PendingMapFeatureRequestRowDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PendingMapFeatureRequestRowDto {
  if (json == null) {
    return json;
  }
  return {
    rec_resource_id: json['rec_resource_id'],
    name: json['name'] == null ? undefined : json['name'],
    district_description:
      json['district_description'] == null
        ? undefined
        : json['district_description'],
    recreation_district:
      json['recreation_district'] == null
        ? undefined
        : json['recreation_district'],
    natural_resource_district:
      json['natural_resource_district'] == null
        ? undefined
        : json['natural_resource_district'],
    recreation_type:
      json['recreation_type'] == null ? undefined : json['recreation_type'],
    amend_status_code: json['amend_status_code'],
    feature_count: json['feature_count'],
    requested_at:
      json['requested_at'] == null ? undefined : json['requested_at'],
    geometry_types: json['geometry_types'],
  };
}

export function PendingMapFeatureRequestRowDtoToJSON(
  json: any,
): PendingMapFeatureRequestRowDto {
  return PendingMapFeatureRequestRowDtoToJSONTyped(json, false);
}

export function PendingMapFeatureRequestRowDtoToJSONTyped(
  value?: PendingMapFeatureRequestRowDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    rec_resource_id: value['rec_resource_id'],
    name: value['name'],
    district_description: value['district_description'],
    recreation_district: value['recreation_district'],
    natural_resource_district: value['natural_resource_district'],
    recreation_type: value['recreation_type'],
    amend_status_code: value['amend_status_code'],
    feature_count: value['feature_count'],
    requested_at: value['requested_at'],
    geometry_types: value['geometry_types'],
  };
}
