/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PresignDocUploadResponseDto
 */
export interface PresignDocUploadResponseDto {
  /**
   * Allocated document ID (UUID)
   * @type {string}
   * @memberof PresignDocUploadResponseDto
   */
  document_id: string;
  /**
   * S3 object key for the document
   * @type {string}
   * @memberof PresignDocUploadResponseDto
   */
  key: string;
  /**
   * Presigned PUT URL for uploading to S3
   * @type {string}
   * @memberof PresignDocUploadResponseDto
   */
  url: string;
}

/**
 * Check if a given object implements the PresignDocUploadResponseDto interface.
 */
export function instanceOfPresignDocUploadResponseDto(
  value: object,
): value is PresignDocUploadResponseDto {
  if (!('document_id' in value) || value['document_id'] === undefined)
    return false;
  if (!('key' in value) || value['key'] === undefined) return false;
  if (!('url' in value) || value['url'] === undefined) return false;
  return true;
}

export function PresignDocUploadResponseDtoFromJSON(
  json: any,
): PresignDocUploadResponseDto {
  return PresignDocUploadResponseDtoFromJSONTyped(json, false);
}

export function PresignDocUploadResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PresignDocUploadResponseDto {
  if (json == null) {
    return json;
  }
  return {
    document_id: json['document_id'],
    key: json['key'],
    url: json['url'],
  };
}

export function PresignDocUploadResponseDtoToJSON(
  json: any,
): PresignDocUploadResponseDto {
  return PresignDocUploadResponseDtoToJSONTyped(json, false);
}

export function PresignDocUploadResponseDtoToJSONTyped(
  value?: PresignDocUploadResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    document_id: value['document_id'],
    key: value['key'],
    url: value['url'],
  };
}
