/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationResourceReservationInfoDto
 */
export interface RecreationResourceReservationInfoDto {
  /**
   * Rec resource id for the resource this geospatial data belongs to
   * @type {string}
   * @memberof RecreationResourceReservationInfoDto
   */
  rec_resource_id: string;
  /**
   * Reservation website of designed resource
   * @type {string}
   * @memberof RecreationResourceReservationInfoDto
   */
  reservation_website?: string;
  /**
   * Reservation phone number of designed resource
   * @type {string}
   * @memberof RecreationResourceReservationInfoDto
   */
  reservation_phone_number?: string;
  /**
   * Reservation email of designed resource
   * @type {string}
   * @memberof RecreationResourceReservationInfoDto
   */
  reservation_email?: string;
}

/**
 * Check if a given object implements the RecreationResourceReservationInfoDto interface.
 */
export function instanceOfRecreationResourceReservationInfoDto(
  value: object,
): value is RecreationResourceReservationInfoDto {
  if (!('rec_resource_id' in value) || value['rec_resource_id'] === undefined)
    return false;
  return true;
}

export function RecreationResourceReservationInfoDtoFromJSON(
  json: any,
): RecreationResourceReservationInfoDto {
  return RecreationResourceReservationInfoDtoFromJSONTyped(json, false);
}

export function RecreationResourceReservationInfoDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationResourceReservationInfoDto {
  if (json == null) {
    return json;
  }
  return {
    rec_resource_id: json['rec_resource_id'],
    reservation_website:
      json['reservation_website'] == null
        ? undefined
        : json['reservation_website'],
    reservation_phone_number:
      json['reservation_phone_number'] == null
        ? undefined
        : json['reservation_phone_number'],
    reservation_email:
      json['reservation_email'] == null ? undefined : json['reservation_email'],
  };
}

export function RecreationResourceReservationInfoDtoToJSON(
  json: any,
): RecreationResourceReservationInfoDto {
  return RecreationResourceReservationInfoDtoToJSONTyped(json, false);
}

export function RecreationResourceReservationInfoDtoToJSONTyped(
  value?: RecreationResourceReservationInfoDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    rec_resource_id: value['rec_resource_id'],
    reservation_website: value['reservation_website'],
    reservation_phone_number: value['reservation_phone_number'],
    reservation_email: value['reservation_email'],
  };
}
