/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationAssetRepairDto
 */
export interface RecreationAssetRepairDto {
  /**
   * Remedial repair classification code (FK to recreation_remed_repair_code)
   * @type {string}
   * @memberof RecreationAssetRepairDto
   */
  recreation_remed_repair_code?: string | null;
  /**
   * Estimated financial cost for repair
   * @type {number}
   * @memberof RecreationAssetRepairDto
   */
  estimated_repair_cost?: number | null;
  /**
   * Final actual cost incurred
   * @type {number}
   * @memberof RecreationAssetRepairDto
   */
  actual_repair_cost?: number | null;
  /**
   * Date completed (YYYY-MM-DD)
   * @type {string}
   * @memberof RecreationAssetRepairDto
   */
  repair_completed_date?: string | null;
  /**
   * Urgency/priority of repair
   * @type {string}
   * @memberof RecreationAssetRepairDto
   */
  urgency?: string | null;
  /**
   * Trail segment start reference
   * @type {string}
   * @memberof RecreationAssetRepairDto
   */
  trail_segment_start?: string | null;
  /**
   * Trail segment end reference
   * @type {string}
   * @memberof RecreationAssetRepairDto
   */
  trail_segment_end?: string | null;
  /**
   * Unique surrogate identifier for the repair log entry
   * @type {number}
   * @memberof RecreationAssetRepairDto
   */
  repair_id: number;
  /**
   * FK linking to the individual asset being repaired
   * @type {number}
   * @memberof RecreationAssetRepairDto
   */
  asset_id: number;
  /**
   * Timestamp when record was created
   * @type {string}
   * @memberof RecreationAssetRepairDto
   */
  created_at?: string | null;
  /**
   * User identifier who created the record
   * @type {string}
   * @memberof RecreationAssetRepairDto
   */
  created_by?: string | null;
  /**
   * Timestamp when record was last updated
   * @type {string}
   * @memberof RecreationAssetRepairDto
   */
  updated_at?: string | null;
  /**
   * User identifier who last updated the record
   * @type {string}
   * @memberof RecreationAssetRepairDto
   */
  updated_by?: string | null;
}

/**
 * Check if a given object implements the RecreationAssetRepairDto interface.
 */
export function instanceOfRecreationAssetRepairDto(
  value: object,
): value is RecreationAssetRepairDto {
  if (!('repair_id' in value) || value['repair_id'] === undefined) return false;
  if (!('asset_id' in value) || value['asset_id'] === undefined) return false;
  return true;
}

export function RecreationAssetRepairDtoFromJSON(
  json: any,
): RecreationAssetRepairDto {
  return RecreationAssetRepairDtoFromJSONTyped(json, false);
}

export function RecreationAssetRepairDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationAssetRepairDto {
  if (json == null) {
    return json;
  }
  return {
    recreation_remed_repair_code:
      json['recreation_remed_repair_code'] == null
        ? undefined
        : json['recreation_remed_repair_code'],
    estimated_repair_cost:
      json['estimated_repair_cost'] == null
        ? undefined
        : json['estimated_repair_cost'],
    actual_repair_cost:
      json['actual_repair_cost'] == null
        ? undefined
        : json['actual_repair_cost'],
    repair_completed_date:
      json['repair_completed_date'] == null
        ? undefined
        : json['repair_completed_date'],
    urgency: json['urgency'] == null ? undefined : json['urgency'],
    trail_segment_start:
      json['trail_segment_start'] == null
        ? undefined
        : json['trail_segment_start'],
    trail_segment_end:
      json['trail_segment_end'] == null ? undefined : json['trail_segment_end'],
    repair_id: json['repair_id'],
    asset_id: json['asset_id'],
    created_at: json['created_at'] == null ? undefined : json['created_at'],
    created_by: json['created_by'] == null ? undefined : json['created_by'],
    updated_at: json['updated_at'] == null ? undefined : json['updated_at'],
    updated_by: json['updated_by'] == null ? undefined : json['updated_by'],
  };
}

export function RecreationAssetRepairDtoToJSON(
  json: any,
): RecreationAssetRepairDto {
  return RecreationAssetRepairDtoToJSONTyped(json, false);
}

export function RecreationAssetRepairDtoToJSONTyped(
  value?: RecreationAssetRepairDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    recreation_remed_repair_code: value['recreation_remed_repair_code'],
    estimated_repair_cost: value['estimated_repair_cost'],
    actual_repair_cost: value['actual_repair_cost'],
    repair_completed_date: value['repair_completed_date'],
    urgency: value['urgency'],
    trail_segment_start: value['trail_segment_start'],
    trail_segment_end: value['trail_segment_end'],
    repair_id: value['repair_id'],
    asset_id: value['asset_id'],
    created_at: value['created_at'],
    created_by: value['created_by'],
    updated_at: value['updated_at'],
    updated_by: value['updated_by'],
  };
}
