/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RecreationResourceDocBodyDto
 */
export interface RecreationResourceDocBodyDto {
  /**
   * Doc title
   * @type {string}
   * @memberof RecreationResourceDocBodyDto
   */
  title: string;
}

/**
 * Check if a given object implements the RecreationResourceDocBodyDto interface.
 */
export function instanceOfRecreationResourceDocBodyDto(
  value: object,
): value is RecreationResourceDocBodyDto {
  if (!("title" in value) || value["title"] === undefined) return false;
  return true;
}

export function RecreationResourceDocBodyDtoFromJSON(
  json: any,
): RecreationResourceDocBodyDto {
  return RecreationResourceDocBodyDtoFromJSONTyped(json, false);
}

export function RecreationResourceDocBodyDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationResourceDocBodyDto {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"],
  };
}

export function RecreationResourceDocBodyDtoToJSON(
  json: any,
): RecreationResourceDocBodyDto {
  return RecreationResourceDocBodyDtoToJSONTyped(json, false);
}

export function RecreationResourceDocBodyDtoToJSONTyped(
  value?: RecreationResourceDocBodyDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
  };
}
