/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationResourceGeospatialDto
 */
export interface RecreationResourceGeospatialDto {
  /**
   * Rec resource id for the resource this geospatial data belongs to
   * @type {string}
   * @memberof RecreationResourceGeospatialDto
   */
  rec_resource_id: string;
  /**
   * Array of GeoJSON geometry strings representing spatial features (polygons, lines) for the recreation resource
   * @type {Array<string>}
   * @memberof RecreationResourceGeospatialDto
   */
  spatial_feature_geometry?: Array<string>;
  /**
   * GeoJSON geometry string representing the point location of the recreation site
   * @type {string}
   * @memberof RecreationResourceGeospatialDto
   */
  site_point_geometry?: string;
  /**
   * UTM (Universal Transverse Mercator) zone number for the site location
   * @type {number}
   * @memberof RecreationResourceGeospatialDto
   */
  utm_zone?: number | null;
  /**
   * UTM easting coordinate (meters east of the UTM zone central meridian)
   * @type {number}
   * @memberof RecreationResourceGeospatialDto
   */
  utm_easting?: number | null;
  /**
   * UTM northing coordinate (meters north of the equator in northern hemisphere)
   * @type {number}
   * @memberof RecreationResourceGeospatialDto
   */
  utm_northing?: number | null;
  /**
   * Latitude in decimal degrees (WGS84 coordinate system, EPSG:4326)
   * @type {number}
   * @memberof RecreationResourceGeospatialDto
   */
  latitude?: number | null;
  /**
   * Longitude in decimal degrees (WGS84 coordinate system, EPSG:4326)
   * @type {number}
   * @memberof RecreationResourceGeospatialDto
   */
  longitude?: number | null;
}

/**
 * Check if a given object implements the RecreationResourceGeospatialDto interface.
 */
export function instanceOfRecreationResourceGeospatialDto(
  value: object,
): value is RecreationResourceGeospatialDto {
  if (!('rec_resource_id' in value) || value['rec_resource_id'] === undefined)
    return false;
  return true;
}

export function RecreationResourceGeospatialDtoFromJSON(
  json: any,
): RecreationResourceGeospatialDto {
  return RecreationResourceGeospatialDtoFromJSONTyped(json, false);
}

export function RecreationResourceGeospatialDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationResourceGeospatialDto {
  if (json == null) {
    return json;
  }
  return {
    rec_resource_id: json['rec_resource_id'],
    spatial_feature_geometry:
      json['spatial_feature_geometry'] == null
        ? undefined
        : json['spatial_feature_geometry'],
    site_point_geometry:
      json['site_point_geometry'] == null
        ? undefined
        : json['site_point_geometry'],
    utm_zone: json['utm_zone'] == null ? undefined : json['utm_zone'],
    utm_easting: json['utm_easting'] == null ? undefined : json['utm_easting'],
    utm_northing:
      json['utm_northing'] == null ? undefined : json['utm_northing'],
    latitude: json['latitude'] == null ? undefined : json['latitude'],
    longitude: json['longitude'] == null ? undefined : json['longitude'],
  };
}

export function RecreationResourceGeospatialDtoToJSON(
  json: any,
): RecreationResourceGeospatialDto {
  return RecreationResourceGeospatialDtoToJSONTyped(json, false);
}

export function RecreationResourceGeospatialDtoToJSONTyped(
  value?: RecreationResourceGeospatialDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    rec_resource_id: value['rec_resource_id'],
    spatial_feature_geometry: value['spatial_feature_geometry'],
    site_point_geometry: value['site_point_geometry'],
    utm_zone: value['utm_zone'],
    utm_easting: value['utm_easting'],
    utm_northing: value['utm_northing'],
    latitude: value['latitude'],
    longitude: value['longitude'],
  };
}
