/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationRiskRatingDto
 */
export interface RecreationRiskRatingDto {
  /**
   * Risk rating code
   * @type {string}
   * @memberof RecreationRiskRatingDto
   */
  risk_rating_code: string;
  /**
   * Description of the risk rating
   * @type {string}
   * @memberof RecreationRiskRatingDto
   */
  description: string;
}

/**
 * Check if a given object implements the RecreationRiskRatingDto interface.
 */
export function instanceOfRecreationRiskRatingDto(
  value: object,
): value is RecreationRiskRatingDto {
  if (!('risk_rating_code' in value) || value['risk_rating_code'] === undefined)
    return false;
  if (!('description' in value) || value['description'] === undefined)
    return false;
  return true;
}

export function RecreationRiskRatingDtoFromJSON(
  json: any,
): RecreationRiskRatingDto {
  return RecreationRiskRatingDtoFromJSONTyped(json, false);
}

export function RecreationRiskRatingDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationRiskRatingDto {
  if (json == null) {
    return json;
  }
  return {
    risk_rating_code: json['risk_rating_code'],
    description: json['description'],
  };
}

export function RecreationRiskRatingDtoToJSON(
  json: any,
): RecreationRiskRatingDto {
  return RecreationRiskRatingDtoToJSONTyped(json, false);
}

export function RecreationRiskRatingDtoToJSONTyped(
  value?: RecreationRiskRatingDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    risk_rating_code: value['risk_rating_code'],
    description: value['description'],
  };
}
