/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateAssetFieldsDto } from './UpdateAssetFieldsDto';
import {
  UpdateAssetFieldsDtoFromJSON,
  UpdateAssetFieldsDtoFromJSONTyped,
  UpdateAssetFieldsDtoToJSON,
  UpdateAssetFieldsDtoToJSONTyped,
} from './UpdateAssetFieldsDto';

/**
 *
 * @export
 * @interface RecreationAssetBulkUpdateDto
 */
export interface RecreationAssetBulkUpdateDto {
  /**
   * List of asset IDs to update
   * @type {Array<string>}
   * @memberof RecreationAssetBulkUpdateDto
   */
  asset_ids: Array<string>;
  /**
   * Fields to update for the specified assets
   * @type {UpdateAssetFieldsDto}
   * @memberof RecreationAssetBulkUpdateDto
   */
  update_fields: UpdateAssetFieldsDto;
}

/**
 * Check if a given object implements the RecreationAssetBulkUpdateDto interface.
 */
export function instanceOfRecreationAssetBulkUpdateDto(
  value: object,
): value is RecreationAssetBulkUpdateDto {
  if (!('asset_ids' in value) || value['asset_ids'] === undefined) return false;
  if (!('update_fields' in value) || value['update_fields'] === undefined)
    return false;
  return true;
}

export function RecreationAssetBulkUpdateDtoFromJSON(
  json: any,
): RecreationAssetBulkUpdateDto {
  return RecreationAssetBulkUpdateDtoFromJSONTyped(json, false);
}

export function RecreationAssetBulkUpdateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationAssetBulkUpdateDto {
  if (json == null) {
    return json;
  }
  return {
    asset_ids: json['asset_ids'],
    update_fields: UpdateAssetFieldsDtoFromJSON(json['update_fields']),
  };
}

export function RecreationAssetBulkUpdateDtoToJSON(
  json: any,
): RecreationAssetBulkUpdateDto {
  return RecreationAssetBulkUpdateDtoToJSONTyped(json, false);
}

export function RecreationAssetBulkUpdateDtoToJSONTyped(
  value?: RecreationAssetBulkUpdateDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    asset_ids: value['asset_ids'],
    update_fields: UpdateAssetFieldsDtoToJSON(value['update_fields']),
  };
}
