/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationRepairCodeDto
 */
export interface RecreationRepairCodeDto {
  /**
   * Surrogate primary key for the remedial repair code
   * @type {string}
   * @memberof RecreationRepairCodeDto
   */
  recreation_remed_repair_code: string;
  /**
   * Description of the repair code
   * @type {string}
   * @memberof RecreationRepairCodeDto
   */
  description?: string;
}

/**
 * Check if a given object implements the RecreationRepairCodeDto interface.
 */
export function instanceOfRecreationRepairCodeDto(
  value: object,
): value is RecreationRepairCodeDto {
  if (
    !('recreation_remed_repair_code' in value) ||
    value['recreation_remed_repair_code'] === undefined
  )
    return false;
  return true;
}

export function RecreationRepairCodeDtoFromJSON(
  json: any,
): RecreationRepairCodeDto {
  return RecreationRepairCodeDtoFromJSONTyped(json, false);
}

export function RecreationRepairCodeDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationRepairCodeDto {
  if (json == null) {
    return json;
  }
  return {
    recreation_remed_repair_code: json['recreation_remed_repair_code'],
    description: json['description'] == null ? undefined : json['description'],
  };
}

export function RecreationRepairCodeDtoToJSON(
  json: any,
): RecreationRepairCodeDto {
  return RecreationRepairCodeDtoToJSONTyped(json, false);
}

export function RecreationRepairCodeDtoToJSONTyped(
  value?: RecreationRepairCodeDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    recreation_remed_repair_code: value['recreation_remed_repair_code'],
    description: value['description'],
  };
}
