/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationStructureDto
 */
export interface RecreationStructureDto {
  /**
   * Indicates if the recreation resource has at least one toilet
   * @type {boolean}
   * @memberof RecreationStructureDto
   */
  has_toilet: boolean;
  /**
   * Indicates if the recreation resource has at least one table
   * @type {boolean}
   * @memberof RecreationStructureDto
   */
  has_table: boolean;
}

/**
 * Check if a given object implements the RecreationStructureDto interface.
 */
export function instanceOfRecreationStructureDto(
  value: object,
): value is RecreationStructureDto {
  if (!('has_toilet' in value) || value['has_toilet'] === undefined)
    return false;
  if (!('has_table' in value) || value['has_table'] === undefined) return false;
  return true;
}

export function RecreationStructureDtoFromJSON(
  json: any,
): RecreationStructureDto {
  return RecreationStructureDtoFromJSONTyped(json, false);
}

export function RecreationStructureDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationStructureDto {
  if (json == null) {
    return json;
  }
  return {
    has_toilet: json['has_toilet'],
    has_table: json['has_table'],
  };
}

export function RecreationStructureDtoToJSON(
  json: any,
): RecreationStructureDto {
  return RecreationStructureDtoToJSONTyped(json, false);
}

export function RecreationStructureDtoToJSONTyped(
  value?: RecreationStructureDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    has_toilet: value['has_toilet'],
    has_table: value['has_table'],
  };
}
