/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecreationResourceImageVariantDto } from './RecreationResourceImageVariantDto';
import {
  RecreationResourceImageVariantDtoFromJSON,
  RecreationResourceImageVariantDtoFromJSONTyped,
  RecreationResourceImageVariantDtoToJSON,
  RecreationResourceImageVariantDtoToJSONTyped,
} from './RecreationResourceImageVariantDto';

/**
 *
 * @export
 * @interface RecreationResourceImageDto
 */
export interface RecreationResourceImageDto {
  /**
   * Reference ID for the image
   * @type {string}
   * @memberof RecreationResourceImageDto
   */
  ref_id: string;
  /**
   * Image ID (UUID)
   * @type {string}
   * @memberof RecreationResourceImageDto
   */
  image_id?: string;
  /**
   * Image file name
   * @type {string}
   * @memberof RecreationResourceImageDto
   */
  file_name: string;
  /**
   * Available image variants
   * @type {Array<RecreationResourceImageVariantDto>}
   * @memberof RecreationResourceImageDto
   */
  recreation_resource_image_variants?: Array<RecreationResourceImageVariantDto>;
  /**
   * File upload date
   * @type {string}
   * @memberof RecreationResourceImageDto
   */
  created_at: string;
  /**
   * Size of the original image in bytes
   * @type {number}
   * @memberof RecreationResourceImageDto
   */
  file_size?: number;
  /**
   * Date the photo was taken
   * @type {string}
   * @memberof RecreationResourceImageDto
   */
  date_taken?: string;
  /**
   * Photographer type code
   * @type {string}
   * @memberof RecreationResourceImageDto
   */
  photographer_type?: string;
  /**
   * Photographer type description
   * @type {string}
   * @memberof RecreationResourceImageDto
   */
  photographer_type_description?: string;
  /**
   * Photographer name for attribution
   * @type {string}
   * @memberof RecreationResourceImageDto
   */
  photographer_name?: string;
  /**
   * Whether the image contains personally identifiable information
   * @type {boolean}
   * @memberof RecreationResourceImageDto
   */
  contains_pii?: boolean;
  /**
   * Display name for photographer (photographer_name, or updated_by, or created_by)
   * @type {string}
   * @memberof RecreationResourceImageDto
   */
  photographer_display_name?: string;
}

/**
 * Check if a given object implements the RecreationResourceImageDto interface.
 */
export function instanceOfRecreationResourceImageDto(
  value: object,
): value is RecreationResourceImageDto {
  if (!('ref_id' in value) || value['ref_id'] === undefined) return false;
  if (!('file_name' in value) || value['file_name'] === undefined) return false;
  if (!('created_at' in value) || value['created_at'] === undefined)
    return false;
  return true;
}

export function RecreationResourceImageDtoFromJSON(
  json: any,
): RecreationResourceImageDto {
  return RecreationResourceImageDtoFromJSONTyped(json, false);
}

export function RecreationResourceImageDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationResourceImageDto {
  if (json == null) {
    return json;
  }
  return {
    ref_id: json['ref_id'],
    image_id: json['image_id'] == null ? undefined : json['image_id'],
    file_name: json['file_name'],
    recreation_resource_image_variants:
      json['recreation_resource_image_variants'] == null
        ? undefined
        : (json['recreation_resource_image_variants'] as Array<any>).map(
            RecreationResourceImageVariantDtoFromJSON,
          ),
    created_at: json['created_at'],
    file_size: json['file_size'] == null ? undefined : json['file_size'],
    date_taken: json['date_taken'] == null ? undefined : json['date_taken'],
    photographer_type:
      json['photographer_type'] == null ? undefined : json['photographer_type'],
    photographer_type_description:
      json['photographer_type_description'] == null
        ? undefined
        : json['photographer_type_description'],
    photographer_name:
      json['photographer_name'] == null ? undefined : json['photographer_name'],
    contains_pii:
      json['contains_pii'] == null ? undefined : json['contains_pii'],
    photographer_display_name:
      json['photographer_display_name'] == null
        ? undefined
        : json['photographer_display_name'],
  };
}

export function RecreationResourceImageDtoToJSON(
  json: any,
): RecreationResourceImageDto {
  return RecreationResourceImageDtoToJSONTyped(json, false);
}

export function RecreationResourceImageDtoToJSONTyped(
  value?: RecreationResourceImageDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ref_id: value['ref_id'],
    image_id: value['image_id'],
    file_name: value['file_name'],
    recreation_resource_image_variants:
      value['recreation_resource_image_variants'] == null
        ? undefined
        : (value['recreation_resource_image_variants'] as Array<any>).map(
            RecreationResourceImageVariantDtoToJSON,
          ),
    created_at: value['created_at'],
    file_size: value['file_size'],
    date_taken: value['date_taken'],
    photographer_type: value['photographer_type'],
    photographer_type_description: value['photographer_type_description'],
    photographer_name: value['photographer_name'],
    contains_pii: value['contains_pii'],
    photographer_display_name: value['photographer_display_name'],
  };
}
