/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  mapValues,
  parseDate,
  parseDateTime,
  serializeDate,
  serializeDateTime,
} from '../runtime';
/**
 *
 * @export
 * @interface RecreationResourceAdvisoryDto
 */
export interface RecreationResourceAdvisoryDto {
  /**
   * Advisory number
   */
  advisory_number: number;
  /**
   * Event type
   */
  event_type: string;
  /**
   * Access status name
   */
  access_status_name: string;
  /**
   * Advisory status
   */
  advisory_status: string;
  /**
   * Urgency level
   */
  urgency: string;
  /**
   * Advisory date (posted date)
   */
  advisory_date: Date;
  /**
   * Effective date (event start)
   */
  effective_date?: Date | null;
  /**
   * End date (event end)
   */
  end_date?: Date | null;
  /**
   * Expiry date
   */
  expiry_date?: Date | null;
  /**
   * Last updated date
   */
  updated_date?: Date | null;
  /**
   * Published at date
   */
  published_at?: Date | null;
  /**
   * Submitted by (published by)
   */
  submitted_by: string;
  /**
   * Whether to display the advisory date
   */
  is_advisory_date_displayed: boolean;
  /**
   * Whether to display the effective date
   */
  is_effective_date_displayed: boolean;
  /**
   * Whether to display the end date
   */
  is_end_date_displayed: boolean;
  /**
   * Whether to display the last updated date
   */
  is_updated_date_displayed: boolean;
}

/**
 * Check if a given object implements the RecreationResourceAdvisoryDto interface.
 */
export function instanceOfRecreationResourceAdvisoryDto(
  value: object,
): value is RecreationResourceAdvisoryDto {
  if (!('advisory_number' in value) || value['advisory_number'] === undefined)
    return false;
  if (!('event_type' in value) || value['event_type'] === undefined)
    return false;
  if (
    !('access_status_name' in value) ||
    value['access_status_name'] === undefined
  )
    return false;
  if (!('advisory_status' in value) || value['advisory_status'] === undefined)
    return false;
  if (!('urgency' in value) || value['urgency'] === undefined) return false;
  if (!('advisory_date' in value) || value['advisory_date'] === undefined)
    return false;
  if (!('submitted_by' in value) || value['submitted_by'] === undefined)
    return false;
  if (
    !('is_advisory_date_displayed' in value) ||
    value['is_advisory_date_displayed'] === undefined
  )
    return false;
  if (
    !('is_effective_date_displayed' in value) ||
    value['is_effective_date_displayed'] === undefined
  )
    return false;
  if (
    !('is_end_date_displayed' in value) ||
    value['is_end_date_displayed'] === undefined
  )
    return false;
  if (
    !('is_updated_date_displayed' in value) ||
    value['is_updated_date_displayed'] === undefined
  )
    return false;
  return true;
}

export function RecreationResourceAdvisoryDtoFromJSON(
  json: any,
): RecreationResourceAdvisoryDto {
  return RecreationResourceAdvisoryDtoFromJSONTyped(json, false);
}

export function RecreationResourceAdvisoryDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationResourceAdvisoryDto {
  if (json == null) {
    return json;
  }
  return {
    advisory_number: json['advisory_number'],
    event_type: json['event_type'],
    access_status_name: json['access_status_name'],
    advisory_status: json['advisory_status'],
    urgency: json['urgency'],
    advisory_date:
      json['advisory_date'] == null
        ? json['advisory_date']
        : parseDateTime(json['advisory_date']),
    effective_date:
      json['effective_date'] === undefined
        ? undefined
        : json['effective_date'] === null
          ? null
          : parseDateTime(json['effective_date']),
    end_date:
      json['end_date'] === undefined
        ? undefined
        : json['end_date'] === null
          ? null
          : parseDateTime(json['end_date']),
    expiry_date:
      json['expiry_date'] === undefined
        ? undefined
        : json['expiry_date'] === null
          ? null
          : parseDateTime(json['expiry_date']),
    updated_date:
      json['updated_date'] === undefined
        ? undefined
        : json['updated_date'] === null
          ? null
          : parseDateTime(json['updated_date']),
    published_at:
      json['published_at'] === undefined
        ? undefined
        : json['published_at'] === null
          ? null
          : parseDateTime(json['published_at']),
    submitted_by: json['submitted_by'],
    is_advisory_date_displayed: json['is_advisory_date_displayed'],
    is_effective_date_displayed: json['is_effective_date_displayed'],
    is_end_date_displayed: json['is_end_date_displayed'],
    is_updated_date_displayed: json['is_updated_date_displayed'],
  };
}

export function RecreationResourceAdvisoryDtoToJSON(
  json: any,
): RecreationResourceAdvisoryDto {
  return RecreationResourceAdvisoryDtoToJSONTyped(json, false);
}

export function RecreationResourceAdvisoryDtoToJSONTyped(
  value?: RecreationResourceAdvisoryDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    advisory_number: value['advisory_number'],
    event_type: value['event_type'],
    access_status_name: value['access_status_name'],
    advisory_status: value['advisory_status'],
    urgency: value['urgency'],
    advisory_date:
      value['advisory_date'] == null
        ? value['advisory_date']
        : serializeDateTime(value['advisory_date']),
    effective_date:
      value['effective_date'] == null
        ? value['effective_date']
        : serializeDateTime(value['effective_date']),
    end_date:
      value['end_date'] == null
        ? value['end_date']
        : serializeDateTime(value['end_date']),
    expiry_date:
      value['expiry_date'] == null
        ? value['expiry_date']
        : serializeDateTime(value['expiry_date']),
    updated_date:
      value['updated_date'] == null
        ? value['updated_date']
        : serializeDateTime(value['updated_date']),
    published_at:
      value['published_at'] == null
        ? value['published_at']
        : serializeDateTime(value['published_at']),
    submitted_by: value['submitted_by'],
    is_advisory_date_displayed: value['is_advisory_date_displayed'],
    is_effective_date_displayed: value['is_effective_date_displayed'],
    is_end_date_displayed: value['is_end_date_displayed'],
    is_updated_date_displayed: value['is_updated_date_displayed'],
  };
}
