/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationSubAccessCodeDto
 */
export interface RecreationSubAccessCodeDto {
  /**
   * Unique code identifying the sub-access method
   * @type {string}
   * @memberof RecreationSubAccessCodeDto
   */
  code: string;
  /**
   * Description of the sub-access method
   * @type {string}
   * @memberof RecreationSubAccessCodeDto
   */
  description: string;
}

/**
 * Check if a given object implements the RecreationSubAccessCodeDto interface.
 */
export function instanceOfRecreationSubAccessCodeDto(
  value: object,
): value is RecreationSubAccessCodeDto {
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined)
    return false;
  return true;
}

export function RecreationSubAccessCodeDtoFromJSON(
  json: any,
): RecreationSubAccessCodeDto {
  return RecreationSubAccessCodeDtoFromJSONTyped(json, false);
}

export function RecreationSubAccessCodeDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationSubAccessCodeDto {
  if (json == null) {
    return json;
  }
  return {
    code: json['code'],
    description: json['description'],
  };
}

export function RecreationSubAccessCodeDtoToJSON(
  json: any,
): RecreationSubAccessCodeDto {
  return RecreationSubAccessCodeDtoToJSONTyped(json, false);
}

export function RecreationSubAccessCodeDtoToJSONTyped(
  value?: RecreationSubAccessCodeDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value['code'],
    description: value['description'],
  };
}
