/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SuggestionDto
 */
export interface SuggestionDto {
  /**
   * Name of the recreation resource
   * @type {object}
   * @memberof SuggestionDto
   */
  name: object;
  /**
   * Unique resource ID
   * @type {object}
   * @memberof SuggestionDto
   */
  rec_resource_id: object;
  /**
   * Type of recreation resource (e.g., Recreation site, Recreation trail, etc.)
   * @type {object}
   * @memberof SuggestionDto
   */
  recreation_resource_type: object;
  /**
   * Resource type code (e.g., RR, IF, etc.)
   * @type {object}
   * @memberof SuggestionDto
   */
  recreation_resource_type_code: object;
  /**
   * Description of the district (e.g., Chilliwack, Okanagan, etc.)
   * @type {object}
   * @memberof SuggestionDto
   */
  district_description: object;
}

/**
 * Check if a given object implements the SuggestionDto interface.
 */
export function instanceOfSuggestionDto(value: object): value is SuggestionDto {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("rec_resource_id" in value) || value["rec_resource_id"] === undefined)
    return false;
  if (
    !("recreation_resource_type" in value) ||
    value["recreation_resource_type"] === undefined
  )
    return false;
  if (
    !("recreation_resource_type_code" in value) ||
    value["recreation_resource_type_code"] === undefined
  )
    return false;
  if (
    !("district_description" in value) ||
    value["district_description"] === undefined
  )
    return false;
  return true;
}

export function SuggestionDtoFromJSON(json: any): SuggestionDto {
  return SuggestionDtoFromJSONTyped(json, false);
}

export function SuggestionDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SuggestionDto {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    rec_resource_id: json["rec_resource_id"],
    recreation_resource_type: json["recreation_resource_type"],
    recreation_resource_type_code: json["recreation_resource_type_code"],
    district_description: json["district_description"],
  };
}

export function SuggestionDtoToJSON(json: any): SuggestionDto {
  return SuggestionDtoToJSONTyped(json, false);
}

export function SuggestionDtoToJSONTyped(
  value?: SuggestionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    rec_resource_id: value["rec_resource_id"],
    recreation_resource_type: value["recreation_resource_type"],
    recreation_resource_type_code: value["recreation_resource_type_code"],
    district_description: value["district_description"],
  };
}
