/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateRecreationFeeDto
 */
export interface UpdateRecreationFeeDto {
  /**
   * Unique identifier for the fee
   * @type {string}
   * @memberof UpdateRecreationFeeDto
   */
  fee_id: string;
  /**
   * Start date for the fee applicability (YYYY-MM-DD)
   * @type {object}
   * @memberof UpdateRecreationFeeDto
   */
  fee_start_date?: object | null;
  /**
   * End date for the fee applicability (YYYY-MM-DD)
   * @type {object}
   * @memberof UpdateRecreationFeeDto
   */
  fee_end_date?: object | null;
  /**
   * Indicates if the fee applies on Monday
   * @type {string}
   * @memberof UpdateRecreationFeeDto
   */
  monday_ind?: string;
  /**
   * Indicates if the fee applies on Tuesday
   * @type {string}
   * @memberof UpdateRecreationFeeDto
   */
  tuesday_ind?: string;
  /**
   * Indicates if the fee applies on Wednesday
   * @type {string}
   * @memberof UpdateRecreationFeeDto
   */
  wednesday_ind?: string;
  /**
   * Indicates if the fee applies on Thursday
   * @type {string}
   * @memberof UpdateRecreationFeeDto
   */
  thursday_ind?: string;
  /**
   * Indicates if the fee applies on Friday
   * @type {string}
   * @memberof UpdateRecreationFeeDto
   */
  friday_ind?: string;
  /**
   * Indicates if the fee applies on Saturday
   * @type {string}
   * @memberof UpdateRecreationFeeDto
   */
  saturday_ind?: string;
  /**
   * Indicates if the fee applies on Sunday
   * @type {string}
   * @memberof UpdateRecreationFeeDto
   */
  sunday_ind?: string;
}

/**
 * Check if a given object implements the UpdateRecreationFeeDto interface.
 */
export function instanceOfUpdateRecreationFeeDto(
  value: object,
): value is UpdateRecreationFeeDto {
  if (!('fee_id' in value) || value['fee_id'] === undefined) return false;
  return true;
}

export function UpdateRecreationFeeDtoFromJSON(
  json: any,
): UpdateRecreationFeeDto {
  return UpdateRecreationFeeDtoFromJSONTyped(json, false);
}

export function UpdateRecreationFeeDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateRecreationFeeDto {
  if (json == null) {
    return json;
  }
  return {
    fee_id: json['fee_id'],
    fee_start_date:
      json['fee_start_date'] == null ? undefined : json['fee_start_date'],
    fee_end_date:
      json['fee_end_date'] == null ? undefined : json['fee_end_date'],
    monday_ind: json['monday_ind'] == null ? undefined : json['monday_ind'],
    tuesday_ind: json['tuesday_ind'] == null ? undefined : json['tuesday_ind'],
    wednesday_ind:
      json['wednesday_ind'] == null ? undefined : json['wednesday_ind'],
    thursday_ind:
      json['thursday_ind'] == null ? undefined : json['thursday_ind'],
    friday_ind: json['friday_ind'] == null ? undefined : json['friday_ind'],
    saturday_ind:
      json['saturday_ind'] == null ? undefined : json['saturday_ind'],
    sunday_ind: json['sunday_ind'] == null ? undefined : json['sunday_ind'],
  };
}

export function UpdateRecreationFeeDtoToJSON(
  json: any,
): UpdateRecreationFeeDto {
  return UpdateRecreationFeeDtoToJSONTyped(json, false);
}

export function UpdateRecreationFeeDtoToJSONTyped(
  value?: UpdateRecreationFeeDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    fee_id: value['fee_id'],
    fee_start_date: value['fee_start_date'],
    fee_end_date: value['fee_end_date'],
    monday_ind: value['monday_ind'],
    tuesday_ind: value['tuesday_ind'],
    wednesday_ind: value['wednesday_ind'],
    thursday_ind: value['thursday_ind'],
    friday_ind: value['friday_ind'],
    saturday_ind: value['saturday_ind'],
    sunday_ind: value['sunday_ind'],
  };
}
