/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateActivitiesDto
 */
export interface UpdateActivitiesDto {
  /**
   * Array of recreation activity codes
   * @type {Array<number>}
   * @memberof UpdateActivitiesDto
   */
  activity_codes: Array<number>;
}

/**
 * Check if a given object implements the UpdateActivitiesDto interface.
 */
export function instanceOfUpdateActivitiesDto(
  value: object,
): value is UpdateActivitiesDto {
  if (!('activity_codes' in value) || value['activity_codes'] === undefined)
    return false;
  return true;
}

export function UpdateActivitiesDtoFromJSON(json: any): UpdateActivitiesDto {
  return UpdateActivitiesDtoFromJSONTyped(json, false);
}

export function UpdateActivitiesDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateActivitiesDto {
  if (json == null) {
    return json;
  }
  return {
    activity_codes: json['activity_codes'],
  };
}

export function UpdateActivitiesDtoToJSON(json: any): UpdateActivitiesDto {
  return UpdateActivitiesDtoToJSONTyped(json, false);
}

export function UpdateActivitiesDtoToJSONTyped(
  value?: UpdateActivitiesDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    activity_codes: value['activity_codes'],
  };
}
