/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation.  ## Act integration Endpoints tagged **act** are the secure CUD (Create / Update / Delete) API consumed by the external Act system to push real-time advisory changes into `rst.act_advisories_flat`.  **Authentication:** OAuth2 *Client Credentials* grant flow via CSS (Common Hosted Single Sign-On).  1. The Act team retrieves their Client ID / Client Secret from the CSS dashboard. 2. They exchange those credentials at the CSS token endpoint to receive a short-lived bearer token (`https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token`). 3. They include the token on every request as `Authorization: Bearer <token>`. 4. Tokens must carry the `act-service` client role. Missing, malformed, or expired tokens are rejected with **401**; tokens without the role are rejected with **403**.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateTrailDto
 */
export interface UpdateTrailDto {
  /**
   * Difficulty classification of the trail
   * @type {string}
   * @memberof UpdateTrailDto
   */
  trail_type?: UpdateTrailDtoTrailTypeEnum | null;
  /**
   * Name of the trail
   * @type {string}
   * @memberof UpdateTrailDto
   */
  name?: string;
  /**
   * Description of the trail
   * @type {object}
   * @memberof UpdateTrailDto
   */
  description?: object | null;
}

/**
 * @export
 */
export const UpdateTrailDtoTrailTypeEnum = {
  Green: 'GREEN',
  Blue: 'BLUE',
  Black: 'BLACK',
} as const;
export type UpdateTrailDtoTrailTypeEnum =
  (typeof UpdateTrailDtoTrailTypeEnum)[keyof typeof UpdateTrailDtoTrailTypeEnum];

/**
 * Check if a given object implements the UpdateTrailDto interface.
 */
export function instanceOfUpdateTrailDto(
  value: object,
): value is UpdateTrailDto {
  return true;
}

export function UpdateTrailDtoFromJSON(json: any): UpdateTrailDto {
  return UpdateTrailDtoFromJSONTyped(json, false);
}

export function UpdateTrailDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateTrailDto {
  if (json == null) {
    return json;
  }
  return {
    trail_type: json['trail_type'] == null ? undefined : json['trail_type'],
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
  };
}

export function UpdateTrailDtoToJSON(json: any): UpdateTrailDto {
  return UpdateTrailDtoToJSONTyped(json, false);
}

export function UpdateTrailDtoToJSONTyped(
  value?: UpdateTrailDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    trail_type: value['trail_type'],
    name: value['name'],
    description: value['description'],
  };
}
