/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateRecreationAccessCodeDto } from './UpdateRecreationAccessCodeDto';
import {
  UpdateRecreationAccessCodeDtoFromJSON,
  UpdateRecreationAccessCodeDtoFromJSONTyped,
  UpdateRecreationAccessCodeDtoToJSON,
  UpdateRecreationAccessCodeDtoToJSONTyped,
} from './UpdateRecreationAccessCodeDto';

/**
 *
 * @export
 * @interface UpdateRecreationResourceDto
 */
export interface UpdateRecreationResourceDto {
  /**
   * Maintenance standard code
   * @type {string}
   * @memberof UpdateRecreationResourceDto
   */
  maintenance_standard_code?: string;
  /**
   * Control access code (stored in recreation_control_access_code table)
   * @type {string}
   * @memberof UpdateRecreationResourceDto
   */
  control_access_code?: string;
  /**
   * List of access codes with their sub-access codes
   * @type {Array<UpdateRecreationAccessCodeDto>}
   * @memberof UpdateRecreationResourceDto
   */
  accessCodes?: Array<UpdateRecreationAccessCodeDto>;
  /**
   * Status code (open or closed)
   * @type {number}
   * @memberof UpdateRecreationResourceDto
   */
  status_code?: number;
}

/**
 * Check if a given object implements the UpdateRecreationResourceDto interface.
 */
export function instanceOfUpdateRecreationResourceDto(
  value: object,
): value is UpdateRecreationResourceDto {
  return true;
}

export function UpdateRecreationResourceDtoFromJSON(
  json: any,
): UpdateRecreationResourceDto {
  return UpdateRecreationResourceDtoFromJSONTyped(json, false);
}

export function UpdateRecreationResourceDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateRecreationResourceDto {
  if (json == null) {
    return json;
  }
  return {
    maintenance_standard_code:
      json['maintenance_standard_code'] == null
        ? undefined
        : json['maintenance_standard_code'],
    control_access_code:
      json['control_access_code'] == null
        ? undefined
        : json['control_access_code'],
    accessCodes:
      json['accessCodes'] == null
        ? undefined
        : (json['accessCodes'] as Array<any>).map(
            UpdateRecreationAccessCodeDtoFromJSON,
          ),
    status_code: json['status_code'] == null ? undefined : json['status_code'],
  };
}

export function UpdateRecreationResourceDtoToJSON(
  json: any,
): UpdateRecreationResourceDto {
  return UpdateRecreationResourceDtoToJSONTyped(json, false);
}

export function UpdateRecreationResourceDtoToJSONTyped(
  value?: UpdateRecreationResourceDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    maintenance_standard_code: value['maintenance_standard_code'],
    control_access_code: value['control_access_code'],
    accessCodes:
      value['accessCodes'] == null
        ? undefined
        : (value['accessCodes'] as Array<any>).map(
            UpdateRecreationAccessCodeDtoToJSON,
          ),
    status_code: value['status_code'],
  };
}
