/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateImageConsentDto
 */
export interface UpdateImageConsentDto {
  /**
   * Date the photo was taken (ISO date string)
   * @type {string}
   * @memberof UpdateImageConsentDto
   */
  date_taken?: string;
  /**
   * Whether the image contains personally identifiable information
   * @type {boolean}
   * @memberof UpdateImageConsentDto
   */
  contains_pii?: boolean;
  /**
   * Type of photographer (database code)
   * @type {string}
   * @memberof UpdateImageConsentDto
   */
  photographer_type?: string;
  /**
   * Name of the photographer for attribution
   * @type {string}
   * @memberof UpdateImageConsentDto
   */
  photographer_name?: string;
  /**
   * Consent form PDF file
   * @type {Blob}
   * @memberof UpdateImageConsentDto
   */
  consent_form?: Blob;
  /**
   * Display name for the image
   * @type {string}
   * @memberof UpdateImageConsentDto
   */
  file_name?: string;
}

/**
 * Check if a given object implements the UpdateImageConsentDto interface.
 */
export function instanceOfUpdateImageConsentDto(
  value: object,
): value is UpdateImageConsentDto {
  return true;
}

export function UpdateImageConsentDtoFromJSON(
  json: any,
): UpdateImageConsentDto {
  return UpdateImageConsentDtoFromJSONTyped(json, false);
}

export function UpdateImageConsentDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateImageConsentDto {
  if (json == null) {
    return json;
  }
  return {
    date_taken: json['date_taken'] == null ? undefined : json['date_taken'],
    contains_pii:
      json['contains_pii'] == null ? undefined : json['contains_pii'],
    photographer_type:
      json['photographer_type'] == null ? undefined : json['photographer_type'],
    photographer_name:
      json['photographer_name'] == null ? undefined : json['photographer_name'],
    consent_form:
      json['consent_form'] == null ? undefined : json['consent_form'],
    file_name: json['file_name'] == null ? undefined : json['file_name'],
  };
}

export function UpdateImageConsentDtoToJSON(json: any): UpdateImageConsentDto {
  return UpdateImageConsentDtoToJSONTyped(json, false);
}

export function UpdateImageConsentDtoToJSONTyped(
  value?: UpdateImageConsentDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    date_taken: value['date_taken'],
    contains_pii: value['contains_pii'],
    photographer_type: value['photographer_type'],
    photographer_name: value['photographer_name'],
    consent_form: value['consent_form'],
    file_name: value['file_name'],
  };
}
