/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecResourceIdRouteImport } from './routes/rec-resource/$id'
import { Route as RecResourceIdIndexRouteImport } from './routes/rec-resource/$id/index'
import { Route as RecResourceIdFilesRouteImport } from './routes/rec-resource/$id/files'
import { Route as RecResourceIdFeesRouteImport } from './routes/rec-resource/$id/fees'
import { Route as RecResourceIdOverviewIndexRouteImport } from './routes/rec-resource/$id/overview/index'
import { Route as RecResourceIdGeospatialIndexRouteImport } from './routes/rec-resource/$id/geospatial/index'
import { Route as RecResourceIdActivitiesIndexRouteImport } from './routes/rec-resource/$id/activities/index'
import { Route as RecResourceIdOverviewEditRouteImport } from './routes/rec-resource/$id/overview/edit'
import { Route as RecResourceIdGeospatialEditRouteImport } from './routes/rec-resource/$id/geospatial/edit'
import { Route as RecResourceIdActivitiesEditRouteImport } from './routes/rec-resource/$id/activities/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecResourceIdRoute = RecResourceIdRouteImport.update({
  id: '/rec-resource/$id',
  path: '/rec-resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecResourceIdIndexRoute = RecResourceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecResourceIdRoute,
} as any)
const RecResourceIdFilesRoute = RecResourceIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => RecResourceIdRoute,
} as any)
const RecResourceIdFeesRoute = RecResourceIdFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => RecResourceIdRoute,
} as any)
const RecResourceIdOverviewIndexRoute =
  RecResourceIdOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => RecResourceIdRoute,
  } as any)
const RecResourceIdGeospatialIndexRoute =
  RecResourceIdGeospatialIndexRouteImport.update({
    id: '/geospatial/',
    path: '/geospatial/',
    getParentRoute: () => RecResourceIdRoute,
  } as any)
const RecResourceIdActivitiesIndexRoute =
  RecResourceIdActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => RecResourceIdRoute,
  } as any)
const RecResourceIdOverviewEditRoute =
  RecResourceIdOverviewEditRouteImport.update({
    id: '/overview/edit',
    path: '/overview/edit',
    getParentRoute: () => RecResourceIdRoute,
  } as any)
const RecResourceIdGeospatialEditRoute =
  RecResourceIdGeospatialEditRouteImport.update({
    id: '/geospatial/edit',
    path: '/geospatial/edit',
    getParentRoute: () => RecResourceIdRoute,
  } as any)
const RecResourceIdActivitiesEditRoute =
  RecResourceIdActivitiesEditRouteImport.update({
    id: '/activities/edit',
    path: '/activities/edit',
    getParentRoute: () => RecResourceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rec-resource/$id': typeof RecResourceIdRouteWithChildren
  '/rec-resource/$id/fees': typeof RecResourceIdFeesRoute
  '/rec-resource/$id/files': typeof RecResourceIdFilesRoute
  '/rec-resource/$id/': typeof RecResourceIdIndexRoute
  '/rec-resource/$id/activities/edit': typeof RecResourceIdActivitiesEditRoute
  '/rec-resource/$id/geospatial/edit': typeof RecResourceIdGeospatialEditRoute
  '/rec-resource/$id/overview/edit': typeof RecResourceIdOverviewEditRoute
  '/rec-resource/$id/activities': typeof RecResourceIdActivitiesIndexRoute
  '/rec-resource/$id/geospatial': typeof RecResourceIdGeospatialIndexRoute
  '/rec-resource/$id/overview': typeof RecResourceIdOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rec-resource/$id/fees': typeof RecResourceIdFeesRoute
  '/rec-resource/$id/files': typeof RecResourceIdFilesRoute
  '/rec-resource/$id': typeof RecResourceIdIndexRoute
  '/rec-resource/$id/activities/edit': typeof RecResourceIdActivitiesEditRoute
  '/rec-resource/$id/geospatial/edit': typeof RecResourceIdGeospatialEditRoute
  '/rec-resource/$id/overview/edit': typeof RecResourceIdOverviewEditRoute
  '/rec-resource/$id/activities': typeof RecResourceIdActivitiesIndexRoute
  '/rec-resource/$id/geospatial': typeof RecResourceIdGeospatialIndexRoute
  '/rec-resource/$id/overview': typeof RecResourceIdOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rec-resource/$id': typeof RecResourceIdRouteWithChildren
  '/rec-resource/$id/fees': typeof RecResourceIdFeesRoute
  '/rec-resource/$id/files': typeof RecResourceIdFilesRoute
  '/rec-resource/$id/': typeof RecResourceIdIndexRoute
  '/rec-resource/$id/activities/edit': typeof RecResourceIdActivitiesEditRoute
  '/rec-resource/$id/geospatial/edit': typeof RecResourceIdGeospatialEditRoute
  '/rec-resource/$id/overview/edit': typeof RecResourceIdOverviewEditRoute
  '/rec-resource/$id/activities/': typeof RecResourceIdActivitiesIndexRoute
  '/rec-resource/$id/geospatial/': typeof RecResourceIdGeospatialIndexRoute
  '/rec-resource/$id/overview/': typeof RecResourceIdOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rec-resource/$id'
    | '/rec-resource/$id/fees'
    | '/rec-resource/$id/files'
    | '/rec-resource/$id/'
    | '/rec-resource/$id/activities/edit'
    | '/rec-resource/$id/geospatial/edit'
    | '/rec-resource/$id/overview/edit'
    | '/rec-resource/$id/activities'
    | '/rec-resource/$id/geospatial'
    | '/rec-resource/$id/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rec-resource/$id/fees'
    | '/rec-resource/$id/files'
    | '/rec-resource/$id'
    | '/rec-resource/$id/activities/edit'
    | '/rec-resource/$id/geospatial/edit'
    | '/rec-resource/$id/overview/edit'
    | '/rec-resource/$id/activities'
    | '/rec-resource/$id/geospatial'
    | '/rec-resource/$id/overview'
  id:
    | '__root__'
    | '/'
    | '/rec-resource/$id'
    | '/rec-resource/$id/fees'
    | '/rec-resource/$id/files'
    | '/rec-resource/$id/'
    | '/rec-resource/$id/activities/edit'
    | '/rec-resource/$id/geospatial/edit'
    | '/rec-resource/$id/overview/edit'
    | '/rec-resource/$id/activities/'
    | '/rec-resource/$id/geospatial/'
    | '/rec-resource/$id/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecResourceIdRoute: typeof RecResourceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rec-resource/$id': {
      id: '/rec-resource/$id'
      path: '/rec-resource/$id'
      fullPath: '/rec-resource/$id'
      preLoaderRoute: typeof RecResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rec-resource/$id/': {
      id: '/rec-resource/$id/'
      path: '/'
      fullPath: '/rec-resource/$id/'
      preLoaderRoute: typeof RecResourceIdIndexRouteImport
      parentRoute: typeof RecResourceIdRoute
    }
    '/rec-resource/$id/files': {
      id: '/rec-resource/$id/files'
      path: '/files'
      fullPath: '/rec-resource/$id/files'
      preLoaderRoute: typeof RecResourceIdFilesRouteImport
      parentRoute: typeof RecResourceIdRoute
    }
    '/rec-resource/$id/fees': {
      id: '/rec-resource/$id/fees'
      path: '/fees'
      fullPath: '/rec-resource/$id/fees'
      preLoaderRoute: typeof RecResourceIdFeesRouteImport
      parentRoute: typeof RecResourceIdRoute
    }
    '/rec-resource/$id/overview/': {
      id: '/rec-resource/$id/overview/'
      path: '/overview'
      fullPath: '/rec-resource/$id/overview'
      preLoaderRoute: typeof RecResourceIdOverviewIndexRouteImport
      parentRoute: typeof RecResourceIdRoute
    }
    '/rec-resource/$id/geospatial/': {
      id: '/rec-resource/$id/geospatial/'
      path: '/geospatial'
      fullPath: '/rec-resource/$id/geospatial'
      preLoaderRoute: typeof RecResourceIdGeospatialIndexRouteImport
      parentRoute: typeof RecResourceIdRoute
    }
    '/rec-resource/$id/activities/': {
      id: '/rec-resource/$id/activities/'
      path: '/activities'
      fullPath: '/rec-resource/$id/activities'
      preLoaderRoute: typeof RecResourceIdActivitiesIndexRouteImport
      parentRoute: typeof RecResourceIdRoute
    }
    '/rec-resource/$id/overview/edit': {
      id: '/rec-resource/$id/overview/edit'
      path: '/overview/edit'
      fullPath: '/rec-resource/$id/overview/edit'
      preLoaderRoute: typeof RecResourceIdOverviewEditRouteImport
      parentRoute: typeof RecResourceIdRoute
    }
    '/rec-resource/$id/geospatial/edit': {
      id: '/rec-resource/$id/geospatial/edit'
      path: '/geospatial/edit'
      fullPath: '/rec-resource/$id/geospatial/edit'
      preLoaderRoute: typeof RecResourceIdGeospatialEditRouteImport
      parentRoute: typeof RecResourceIdRoute
    }
    '/rec-resource/$id/activities/edit': {
      id: '/rec-resource/$id/activities/edit'
      path: '/activities/edit'
      fullPath: '/rec-resource/$id/activities/edit'
      preLoaderRoute: typeof RecResourceIdActivitiesEditRouteImport
      parentRoute: typeof RecResourceIdRoute
    }
  }
}

interface RecResourceIdRouteChildren {
  RecResourceIdFeesRoute: typeof RecResourceIdFeesRoute
  RecResourceIdFilesRoute: typeof RecResourceIdFilesRoute
  RecResourceIdIndexRoute: typeof RecResourceIdIndexRoute
  RecResourceIdActivitiesEditRoute: typeof RecResourceIdActivitiesEditRoute
  RecResourceIdGeospatialEditRoute: typeof RecResourceIdGeospatialEditRoute
  RecResourceIdOverviewEditRoute: typeof RecResourceIdOverviewEditRoute
  RecResourceIdActivitiesIndexRoute: typeof RecResourceIdActivitiesIndexRoute
  RecResourceIdGeospatialIndexRoute: typeof RecResourceIdGeospatialIndexRoute
  RecResourceIdOverviewIndexRoute: typeof RecResourceIdOverviewIndexRoute
}

const RecResourceIdRouteChildren: RecResourceIdRouteChildren = {
  RecResourceIdFeesRoute: RecResourceIdFeesRoute,
  RecResourceIdFilesRoute: RecResourceIdFilesRoute,
  RecResourceIdIndexRoute: RecResourceIdIndexRoute,
  RecResourceIdActivitiesEditRoute: RecResourceIdActivitiesEditRoute,
  RecResourceIdGeospatialEditRoute: RecResourceIdGeospatialEditRoute,
  RecResourceIdOverviewEditRoute: RecResourceIdOverviewEditRoute,
  RecResourceIdActivitiesIndexRoute: RecResourceIdActivitiesIndexRoute,
  RecResourceIdGeospatialIndexRoute: RecResourceIdGeospatialIndexRoute,
  RecResourceIdOverviewIndexRoute: RecResourceIdOverviewIndexRoute,
}

const RecResourceIdRouteWithChildren = RecResourceIdRoute._addFileChildren(
  RecResourceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecResourceIdRoute: RecResourceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
