secrets:
  dbHost: ~
  dbName: ~
  dbPassword: ~
  dbUser: ~
image:
  tag: ~
resources:
  requests:
    cpu: 250m
    memory: 1500Mi
initContainerResources:
  requests:
    cpu: 400m
    memory: 256Mi
schedule: "0 8 * * *" # Daily at midnight PST
backoffLimit: 3 # retry 3 times before giving up
successHistoryLimit: 7
failedHistoryLimit: 7
config:
  awsS3Bucket: "rst-fta-dataload-oracle" # default bucket for S3 uploads
  jobMode: "" # "hourly" for hourly sync job, leave empty for main (daily) job
  flywayEcsCluster: ""
  flywayTaskDefinition: ""
  flywayTaskVpcSubnet: ""
  flywayTaskVpcSecurityGroup: ""
  sharedResourceNamePrefix: "" # Used for naming shared resources (PVC, secrets) between jobs.
  createPvc: false # Set to true to create the PVC
