/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC Admin API
 * RST Admin API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRecreationResourceImageBodyDto
 */
export interface CreateRecreationResourceImageBodyDto {
    /**
     * Image caption
     * @type {string}
     * @memberof CreateRecreationResourceImageBodyDto
     */
    caption: string;
}

/**
 * Check if a given object implements the CreateRecreationResourceImageBodyDto interface.
 */
export function instanceOfCreateRecreationResourceImageBodyDto(value: object): value is CreateRecreationResourceImageBodyDto {
    if (!('caption' in value) || value['caption'] === undefined) return false;
    return true;
}

export function CreateRecreationResourceImageBodyDtoFromJSON(json: any): CreateRecreationResourceImageBodyDto {
    return CreateRecreationResourceImageBodyDtoFromJSONTyped(json, false);
}

export function CreateRecreationResourceImageBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRecreationResourceImageBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'caption': json['caption'],
    };
}

export function CreateRecreationResourceImageBodyDtoToJSON(json: any): CreateRecreationResourceImageBodyDto {
    return CreateRecreationResourceImageBodyDtoToJSONTyped(json, false);
}

export function CreateRecreationResourceImageBodyDtoToJSONTyped(value?: CreateRecreationResourceImageBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caption': value['caption'],
    };
}

