/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
import * as $runtime from '@prisma/client/runtime/client';

/**
 * @param limit
 * @param offset
 */
export const getRecreationResourceSummary = $runtime.makeTypedQueryFactory(
  'select\nrr.rec_resource_id,\nrr.name,\nrr.display_on_public_site,\nrdc.district_code,\nrdc.description as district_description,\nrtv.rec_resource_type_code,\nrtv.description as rec_resource_type_description,\nrs.status_code,\nrsc.description as status_description,\nrs.comment as closure_comment,\npublic.st_asgeojson(rsp.geometry)::text as site_point_geometry,\ncount(*) over()::int as total_count\nfrom rst.recreation_resource rr\ninner join rst.recreation_resource_type_view_admin rtv\non rr.rec_resource_id = rtv.rec_resource_id\nand rtv.rec_resource_type_code is not null\nleft join rst.recreation_district_code rdc\non rr.district_code = rdc.district_code\nleft join rst.recreation_status rs\non rr.rec_resource_id = rs.rec_resource_id\nleft join rst.recreation_status_code rsc\non rs.status_code = rsc.status_code\nleft join rst.recreation_site_point rsp\non rr.rec_resource_id = rsp.rec_resource_id\norder by rr.rec_resource_id asc\nlimit $1\noffset $2;',
) as (
  limit: number,
  offset: number,
) => $runtime.TypedSql<
  getRecreationResourceSummary.Parameters,
  getRecreationResourceSummary.Result
>;

export namespace getRecreationResourceSummary {
  export type Parameters = [limit: number, offset: number];
  export type Result = {
    rec_resource_id: string;
    name: string | null;
    display_on_public_site: boolean | null;
    district_code: string;
    district_description: string;
    rec_resource_type_code: string | null;
    rec_resource_type_description: string | null;
    status_code: number;
    status_description: string;
    closure_comment: string;
    site_point_geometry: string | null;
    total_count: number | null;
  };
}
