/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC API
 * RST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdvisoryDto
 */
export interface AdvisoryDto {
  /**
   * Unique identifier for the advisory
   * @type {number}
   * @memberof AdvisoryDto
   */
  advisory_number: number;
  /**
   * Title of the advisory
   * @type {string}
   * @memberof AdvisoryDto
   */
  title: string;
  /**
   * Description of the advisory
   * @type {string}
   * @memberof AdvisoryDto
   */
  description?: string;
  /**
   * Name of the person or organization that submitted the advisory
   * @type {string}
   * @memberof AdvisoryDto
   */
  submitted_by: string;
  /**
   * Access status group label for the advisory
   * @type {string}
   * @memberof AdvisoryDto
   */
  access_status_grouplabel: string;
  /**
   * Access status name for the advisory
   * @type {string}
   * @memberof AdvisoryDto
   */
  access_status_name: string;
  /**
   * Description of the access status for the advisory
   * @type {string}
   * @memberof AdvisoryDto
   */
  access_status_description: string;
  /**
   * Event type of the advisory
   * @type {string}
   * @memberof AdvisoryDto
   */
  event_type: string;
  /**
   * Urgency level of the advisory
   * @type {string}
   * @memberof AdvisoryDto
   */
  urgency: string;
  /**
   * Publication status of the advisory
   * @type {string}
   * @memberof AdvisoryDto
   */
  advisory_status: string;
  /**
   * Indicates if the advisory affects reservations
   * @type {boolean}
   * @memberof AdvisoryDto
   */
  is_reservations_affected: boolean;
  /**
   * Indicates if the advisory date should be displayed
   * @type {boolean}
   * @memberof AdvisoryDto
   */
  is_advisory_date_displayed: boolean;
  /**
   * Indicates if the effective date should be displayed
   * @type {boolean}
   * @memberof AdvisoryDto
   */
  is_effective_date_displayed: boolean;
  /**
   * Indicates if the end date should be displayed
   * @type {boolean}
   * @memberof AdvisoryDto
   */
  is_end_date_displayed: boolean;
  /**
   * Indicates if the updated date should be displayed
   * @type {boolean}
   * @memberof AdvisoryDto
   */
  is_updated_date_displayed: boolean;
  /**
   * Date and time when the advisory was created
   * @type {Date}
   * @memberof AdvisoryDto
   */
  advisory_date?: Date;
  /**
   * Date and time when the advisory becomes effective
   * @type {Date}
   * @memberof AdvisoryDto
   */
  effective_date?: Date;
  /**
   * Date and time when the advisory ends
   * @type {Date}
   * @memberof AdvisoryDto
   */
  end_date?: Date;
  /**
   * Date and time when the advisory is to be removed
   * @type {Date}
   * @memberof AdvisoryDto
   */
  removal_date?: Date;
  /**
   * Date and time when the advisory was last modified
   * @type {Date}
   * @memberof AdvisoryDto
   */
  modified_date?: Date;
  /**
   * Date and time when the advisory was published
   * @type {Date}
   * @memberof AdvisoryDto
   */
  published_at?: Date;
  /**
   * Date and time when the advisory was last updated
   * @type {Date}
   * @memberof AdvisoryDto
   */
  updated_date?: Date;
  /**
   * Date and time when the advisory will expire
   * @type {Date}
   * @memberof AdvisoryDto
   */
  expiry_date?: Date;
  /**
   * Rank for ordering advisories in listings, calculated based on urgency, access status, and event type to ensure the most critical advisories are displayed prominently.
   * @type {number}
   * @memberof AdvisoryDto
   */
  listing_rank: number;
  /**
   * Sequence number for the urgency level associated with the advisory.
   * @type {number}
   * @memberof AdvisoryDto
   */
  urgency_sequence: number;
  /**
   * Precedence value for the access status associated with the advisory.
   * @type {number}
   * @memberof AdvisoryDto
   */
  access_status_precedence: number;
  /**
   * Precedence value for the event type associated with the advisory.
   * @type {number}
   * @memberof AdvisoryDto
   */
  event_type_precedence: number;
}

/**
 * Check if a given object implements the AdvisoryDto interface.
 */
export function instanceOfAdvisoryDto(value: object): value is AdvisoryDto {
  if (!('advisory_number' in value) || value['advisory_number'] === undefined)
    return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('submitted_by' in value) || value['submitted_by'] === undefined)
    return false;
  if (
    !('access_status_grouplabel' in value) ||
    value['access_status_grouplabel'] === undefined
  )
    return false;
  if (
    !('access_status_name' in value) ||
    value['access_status_name'] === undefined
  )
    return false;
  if (
    !('access_status_description' in value) ||
    value['access_status_description'] === undefined
  )
    return false;
  if (!('event_type' in value) || value['event_type'] === undefined)
    return false;
  if (!('urgency' in value) || value['urgency'] === undefined) return false;
  if (!('advisory_status' in value) || value['advisory_status'] === undefined)
    return false;
  if (
    !('is_reservations_affected' in value) ||
    value['is_reservations_affected'] === undefined
  )
    return false;
  if (
    !('is_advisory_date_displayed' in value) ||
    value['is_advisory_date_displayed'] === undefined
  )
    return false;
  if (
    !('is_effective_date_displayed' in value) ||
    value['is_effective_date_displayed'] === undefined
  )
    return false;
  if (
    !('is_end_date_displayed' in value) ||
    value['is_end_date_displayed'] === undefined
  )
    return false;
  if (
    !('is_updated_date_displayed' in value) ||
    value['is_updated_date_displayed'] === undefined
  )
    return false;
  if (!('listing_rank' in value) || value['listing_rank'] === undefined)
    return false;
  if (!('urgency_sequence' in value) || value['urgency_sequence'] === undefined)
    return false;
  if (
    !('access_status_precedence' in value) ||
    value['access_status_precedence'] === undefined
  )
    return false;
  if (
    !('event_type_precedence' in value) ||
    value['event_type_precedence'] === undefined
  )
    return false;
  return true;
}

export function AdvisoryDtoFromJSON(json: any): AdvisoryDto {
  return AdvisoryDtoFromJSONTyped(json, false);
}

export function AdvisoryDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdvisoryDto {
  if (json == null) {
    return json;
  }
  return {
    advisory_number: json['advisory_number'],
    title: json['title'],
    description: json['description'] == null ? undefined : json['description'],
    submitted_by: json['submitted_by'],
    access_status_grouplabel: json['access_status_grouplabel'],
    access_status_name: json['access_status_name'],
    access_status_description: json['access_status_description'],
    event_type: json['event_type'],
    urgency: json['urgency'],
    advisory_status: json['advisory_status'],
    is_reservations_affected: json['is_reservations_affected'],
    is_advisory_date_displayed: json['is_advisory_date_displayed'],
    is_effective_date_displayed: json['is_effective_date_displayed'],
    is_end_date_displayed: json['is_end_date_displayed'],
    is_updated_date_displayed: json['is_updated_date_displayed'],
    advisory_date:
      json['advisory_date'] == null
        ? undefined
        : new Date(json['advisory_date']),
    effective_date:
      json['effective_date'] == null
        ? undefined
        : new Date(json['effective_date']),
    end_date: json['end_date'] == null ? undefined : new Date(json['end_date']),
    removal_date:
      json['removal_date'] == null ? undefined : new Date(json['removal_date']),
    modified_date:
      json['modified_date'] == null
        ? undefined
        : new Date(json['modified_date']),
    published_at:
      json['published_at'] == null ? undefined : new Date(json['published_at']),
    updated_date:
      json['updated_date'] == null ? undefined : new Date(json['updated_date']),
    expiry_date:
      json['expiry_date'] == null ? undefined : new Date(json['expiry_date']),
    listing_rank: json['listing_rank'],
    urgency_sequence: json['urgency_sequence'],
    access_status_precedence: json['access_status_precedence'],
    event_type_precedence: json['event_type_precedence'],
  };
}

export function AdvisoryDtoToJSON(json: any): AdvisoryDto {
  return AdvisoryDtoToJSONTyped(json, false);
}

export function AdvisoryDtoToJSONTyped(
  value?: AdvisoryDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    advisory_number: value['advisory_number'],
    title: value['title'],
    description: value['description'],
    submitted_by: value['submitted_by'],
    access_status_grouplabel: value['access_status_grouplabel'],
    access_status_name: value['access_status_name'],
    access_status_description: value['access_status_description'],
    event_type: value['event_type'],
    urgency: value['urgency'],
    advisory_status: value['advisory_status'],
    is_reservations_affected: value['is_reservations_affected'],
    is_advisory_date_displayed: value['is_advisory_date_displayed'],
    is_effective_date_displayed: value['is_effective_date_displayed'],
    is_end_date_displayed: value['is_end_date_displayed'],
    is_updated_date_displayed: value['is_updated_date_displayed'],
    advisory_date:
      value['advisory_date'] == null
        ? undefined
        : value['advisory_date'].toISOString(),
    effective_date:
      value['effective_date'] == null
        ? undefined
        : value['effective_date'].toISOString(),
    end_date:
      value['end_date'] == null ? undefined : value['end_date'].toISOString(),
    removal_date:
      value['removal_date'] == null
        ? undefined
        : value['removal_date'].toISOString(),
    modified_date:
      value['modified_date'] == null
        ? undefined
        : value['modified_date'].toISOString(),
    published_at:
      value['published_at'] == null
        ? undefined
        : value['published_at'].toISOString(),
    updated_date:
      value['updated_date'] == null
        ? undefined
        : value['updated_date'].toISOString(),
    expiry_date:
      value['expiry_date'] == null
        ? undefined
        : value['expiry_date'].toISOString(),
    listing_rank: value['listing_rank'],
    urgency_sequence: value['urgency_sequence'],
    access_status_precedence: value['access_status_precedence'],
    event_type_precedence: value['event_type_precedence'],
  };
}
