/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC API
 * RST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AlphabeticalRecreationResourceDto
 */
export interface AlphabeticalRecreationResourceDto {
  /**
   * Unique identifier of the Recreation Resource
   * @type {string}
   * @memberof AlphabeticalRecreationResourceDto
   */
  rec_resource_id: string;
  /**
   * Official name of the Recreation Resource
   * @type {string}
   * @memberof AlphabeticalRecreationResourceDto
   */
  name: string;
  /**
   * Type of the Recreation Resource
   * @type {string}
   * @memberof AlphabeticalRecreationResourceDto
   */
  recreation_resource_type: string;
  /**
   * Code representing the type of the Recreation Resource
   * @type {string}
   * @memberof AlphabeticalRecreationResourceDto
   */
  recreation_resource_type_code: string;
  /**
   * Closest community to the Recreation Resource
   * @type {string}
   * @memberof AlphabeticalRecreationResourceDto
   */
  closest_community: string;
}

/**
 * Check if a given object implements the AlphabeticalRecreationResourceDto interface.
 */
export function instanceOfAlphabeticalRecreationResourceDto(
  value: object,
): value is AlphabeticalRecreationResourceDto {
  if (!('rec_resource_id' in value) || value['rec_resource_id'] === undefined)
    return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (
    !('recreation_resource_type' in value) ||
    value['recreation_resource_type'] === undefined
  )
    return false;
  if (
    !('recreation_resource_type_code' in value) ||
    value['recreation_resource_type_code'] === undefined
  )
    return false;
  if (
    !('closest_community' in value) ||
    value['closest_community'] === undefined
  )
    return false;
  return true;
}

export function AlphabeticalRecreationResourceDtoFromJSON(
  json: any,
): AlphabeticalRecreationResourceDto {
  return AlphabeticalRecreationResourceDtoFromJSONTyped(json, false);
}

export function AlphabeticalRecreationResourceDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AlphabeticalRecreationResourceDto {
  if (json == null) {
    return json;
  }
  return {
    rec_resource_id: json['rec_resource_id'],
    name: json['name'],
    recreation_resource_type: json['recreation_resource_type'],
    recreation_resource_type_code: json['recreation_resource_type_code'],
    closest_community: json['closest_community'],
  };
}

export function AlphabeticalRecreationResourceDtoToJSON(
  json: any,
): AlphabeticalRecreationResourceDto {
  return AlphabeticalRecreationResourceDtoToJSONTyped(json, false);
}

export function AlphabeticalRecreationResourceDtoToJSONTyped(
  value?: AlphabeticalRecreationResourceDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    rec_resource_id: value['rec_resource_id'],
    name: value['name'],
    recreation_resource_type: value['recreation_resource_type'],
    recreation_resource_type_code: value['recreation_resource_type_code'],
    closest_community: value['closest_community'],
  };
}
