/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC API
 * RST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationResourceReservationInfoDto
 */
export interface RecreationResourceReservationInfoDto {
  /**
   * Reservation instructions of designed resource
   * @type {string}
   * @memberof RecreationResourceReservationInfoDto
   */
  reservation_instructions: string;
  /**
   * Reservation website of designed resource
   * @type {string}
   * @memberof RecreationResourceReservationInfoDto
   */
  reservation_website: string;
  /**
   * Reservation phone number of designed resource
   * @type {string}
   * @memberof RecreationResourceReservationInfoDto
   */
  reservation_phone_number: string;
  /**
   * Reservation email of designed resource
   * @type {string}
   * @memberof RecreationResourceReservationInfoDto
   */
  reservation_email: string;
  /**
   * Reservation comments of designed resource
   * @type {string}
   * @memberof RecreationResourceReservationInfoDto
   */
  reservation_comments: string;
}

/**
 * Check if a given object implements the RecreationResourceReservationInfoDto interface.
 */
export function instanceOfRecreationResourceReservationInfoDto(
  value: object,
): value is RecreationResourceReservationInfoDto {
  if (
    !('reservation_instructions' in value) ||
    value['reservation_instructions'] === undefined
  )
    return false;
  if (
    !('reservation_website' in value) ||
    value['reservation_website'] === undefined
  )
    return false;
  if (
    !('reservation_phone_number' in value) ||
    value['reservation_phone_number'] === undefined
  )
    return false;
  if (
    !('reservation_email' in value) ||
    value['reservation_email'] === undefined
  )
    return false;
  if (
    !('reservation_comments' in value) ||
    value['reservation_comments'] === undefined
  )
    return false;
  return true;
}

export function RecreationResourceReservationInfoDtoFromJSON(
  json: any,
): RecreationResourceReservationInfoDto {
  return RecreationResourceReservationInfoDtoFromJSONTyped(json, false);
}

export function RecreationResourceReservationInfoDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationResourceReservationInfoDto {
  if (json == null) {
    return json;
  }
  return {
    reservation_instructions: json['reservation_instructions'],
    reservation_website: json['reservation_website'],
    reservation_phone_number: json['reservation_phone_number'],
    reservation_email: json['reservation_email'],
    reservation_comments: json['reservation_comments'],
  };
}

export function RecreationResourceReservationInfoDtoToJSON(
  json: any,
): RecreationResourceReservationInfoDto {
  return RecreationResourceReservationInfoDtoToJSONTyped(json, false);
}

export function RecreationResourceReservationInfoDtoToJSONTyped(
  value?: RecreationResourceReservationInfoDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    reservation_instructions: value['reservation_instructions'],
    reservation_website: value['reservation_website'],
    reservation_phone_number: value['reservation_phone_number'],
    reservation_email: value['reservation_email'],
    reservation_comments: value['reservation_comments'],
  };
}
