/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC API
 * RST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationSuggestionDto
 */
export interface RecreationSuggestionDto {
  /**
   * Unique identifier for the recreation resource
   * @type {string}
   * @memberof RecreationSuggestionDto
   */
  rec_resource_id: string;
  /**
   * Name of the recreation resource
   * @type {string}
   * @memberof RecreationSuggestionDto
   */
  name: string;
  /**
   * Closest known community to the resource
   * @type {string}
   * @memberof RecreationSuggestionDto
   */
  closest_community?: string;
  /**
   * Description of the recreation district
   * @type {string}
   * @memberof RecreationSuggestionDto
   */
  district_description?: string;
  /**
   * Type code of the recreation resource
   * @type {string}
   * @memberof RecreationSuggestionDto
   */
  recreation_resource_type?: string;
  /**
   * Type of the recreation resource
   * @type {string}
   * @memberof RecreationSuggestionDto
   */
  recreation_resource_type_code?: string;
}

/**
 * Check if a given object implements the RecreationSuggestionDto interface.
 */
export function instanceOfRecreationSuggestionDto(
  value: object,
): value is RecreationSuggestionDto {
  if (!('rec_resource_id' in value) || value['rec_resource_id'] === undefined)
    return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function RecreationSuggestionDtoFromJSON(
  json: any,
): RecreationSuggestionDto {
  return RecreationSuggestionDtoFromJSONTyped(json, false);
}

export function RecreationSuggestionDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationSuggestionDto {
  if (json == null) {
    return json;
  }
  return {
    rec_resource_id: json['rec_resource_id'],
    name: json['name'],
    closest_community:
      json['closest_community'] == null ? undefined : json['closest_community'],
    district_description:
      json['district_description'] == null
        ? undefined
        : json['district_description'],
    recreation_resource_type:
      json['recreation_resource_type'] == null
        ? undefined
        : json['recreation_resource_type'],
    recreation_resource_type_code:
      json['recreation_resource_type_code'] == null
        ? undefined
        : json['recreation_resource_type_code'],
  };
}

export function RecreationSuggestionDtoToJSON(
  json: any,
): RecreationSuggestionDto {
  return RecreationSuggestionDtoToJSONTyped(json, false);
}

export function RecreationSuggestionDtoToJSONTyped(
  value?: RecreationSuggestionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    rec_resource_id: value['rec_resource_id'],
    name: value['name'],
    closest_community: value['closest_community'],
    district_description: value['district_description'],
    recreation_resource_type: value['recreation_resource_type'],
    recreation_resource_type_code: value['recreation_resource_type_code'],
  };
}
