/* tslint:disable */
/* eslint-disable */
/**
 * Recreation Sites and Trails BC API
 * RST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecreationResourceImageUrlDto
 */
export interface RecreationResourceImageUrlDto {
  /**
   * Original size image URL
   * @type {string}
   * @memberof RecreationResourceImageUrlDto
   */
  original?: string;
  /**
   * Thumbnail (175x175) image URL
   * @type {string}
   * @memberof RecreationResourceImageUrlDto
   */
  thm?: string;
  /**
   * Preview (900x480) image URL
   * @type {string}
   * @memberof RecreationResourceImageUrlDto
   */
  pre?: string;
  /**
   * Screen resolution (1400x800) image URL
   * @type {string}
   * @memberof RecreationResourceImageUrlDto
   */
  scr?: string;
}

/**
 * Check if a given object implements the RecreationResourceImageUrlDto interface.
 */
export function instanceOfRecreationResourceImageUrlDto(
  value: object,
): value is RecreationResourceImageUrlDto {
  return true;
}

export function RecreationResourceImageUrlDtoFromJSON(
  json: any,
): RecreationResourceImageUrlDto {
  return RecreationResourceImageUrlDtoFromJSONTyped(json, false);
}

export function RecreationResourceImageUrlDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecreationResourceImageUrlDto {
  if (json == null) {
    return json;
  }
  return {
    original: json['original'] == null ? undefined : json['original'],
    thm: json['thm'] == null ? undefined : json['thm'],
    pre: json['pre'] == null ? undefined : json['pre'],
    scr: json['scr'] == null ? undefined : json['scr'],
  };
}

export function RecreationResourceImageUrlDtoToJSON(
  json: any,
): RecreationResourceImageUrlDto {
  return RecreationResourceImageUrlDtoToJSONTyped(json, false);
}

export function RecreationResourceImageUrlDtoToJSONTyped(
  value?: RecreationResourceImageUrlDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    original: value['original'],
    thm: value['thm'],
    pre: value['pre'],
    scr: value['scr'],
  };
}
