alter table rst.recreation_agreement_holder
    drop constraint if exists recreation_agreement_holder_pkey;

alter table rst.recreation_agreement_holder
    add column if not exists agreement_holder_id integer;

-- Adopt FTA's agreement_holder_id so the sync has a stable key to upsert
-- against. The fta schema only exists where the FTA migrations have been run.
do $$
begin
    if to_regclass('fta.recreation_agreement_holder') is not null then
        execute $sql$
            update rst.recreation_agreement_holder r
            set agreement_holder_id = f.agreement_holder_id
            from fta.recreation_agreement_holder f
            where f.forest_file_id = r.rec_resource_id
              and f.client_number is not distinct from r.client_number
              and f.revision_count is not distinct from r.revision_count
              and r.agreement_holder_id is null
        $sql$;
    end if;
end
$$;

with unmatched as (
    select rec_resource_id,
           1000000 + row_number() over (order by rec_resource_id) as new_id
    from rst.recreation_agreement_holder
    where agreement_holder_id is null
)
update rst.recreation_agreement_holder r
set agreement_holder_id = u.new_id
from unmatched u
where u.rec_resource_id = r.rec_resource_id
  and r.agreement_holder_id is null;

alter table rst.recreation_agreement_holder
    alter column agreement_holder_id set not null;

alter table rst.recreation_agreement_holder
    add constraint recreation_agreement_holder_pkey primary key (agreement_holder_id);

alter table rst.recreation_agreement_holder
    alter column agreement_holder_id add generated by default as identity;

-- Explicitly-inserted ids do not advance an identity sequence, so the sequence
-- must be pushed past the range FTA's own ids occupy.
select setval(
    pg_get_serial_sequence('rst.recreation_agreement_holder', 'agreement_holder_id'),
    greatest(
        1000000,
        coalesce((select max(agreement_holder_id) from rst.recreation_agreement_holder), 0)
    ),
    true
);

alter table rst.recreation_agreement_holder
    add column if not exists visible_on_public_website boolean not null default false;

update rst.recreation_agreement_holder
set visible_on_public_website = true
where visible_on_public_website = false;

alter table rst.recreation_agreement_holder
    add column if not exists partner_relationship_type_code varchar(20) default 'SITE_OPERATOR';

update rst.recreation_agreement_holder
set partner_relationship_type_code = 'SITE_OPERATOR'
where partner_relationship_type_code is null;

alter table rst.recreation_agreement_holder
    alter column partner_relationship_type_code set not null;

alter table rst.recreation_agreement_holder
    add constraint recreation_agreement_holder_partner_relationship_type_code_fkey
    foreign key (partner_relationship_type_code)
    references rst.recreation_partner_relationship_type_code (partner_relationship_type_code);

create index if not exists recreation_agreement_holder_rec_resource_id_idx
    on rst.recreation_agreement_holder (rec_resource_id);

create index if not exists recreation_agreement_holder_client_number_idx
    on rst.recreation_agreement_holder (client_number);

-- Added as nullable up front: sync_temporal_table_schema copies `not null` from
-- the source column but only carries a default when column_default is set, and
-- an identity column reports none, so syncing would fail on a non-empty history.
alter table rst.recreation_agreement_holder_history
    add column if not exists agreement_holder_id integer;

alter table rst.recreation_agreement_holder_history
    add column if not exists visible_on_public_website boolean;

alter table rst.recreation_agreement_holder_history
    add column if not exists partner_relationship_type_code varchar(20);

select setup_temporal_table ('rst', 'recreation_agreement_holder', true);

comment on column rst.recreation_agreement_holder.agreement_holder_id is 'Surrogate primary key. The FTA sync inserts FTA''s own values explicitly; the identity sequence starts above 1000000 so RST-generated values cannot collide with them.';

comment on column rst.recreation_agreement_holder.visible_on_public_website is 'Whether this partner is shown on the public website. Set to true by the FTA sync on insert; not overwritten on subsequent syncs.';

comment on column rst.recreation_agreement_holder.partner_relationship_type_code is 'The type of relationship this partner holds with the resource. Defaults to SITE_OPERATOR, the only relationship FTA supplies.';
