create table rst.recreation_map_feature
(
    rmf_skey                    int not null primary key,
    rec_resource_id             varchar(10) references rst.recreation_resource(rec_resource_id),
    section_id                  varchar(30),
    amendment_id                integer,
    amend_status_code           varchar(3),
    recreation_resource_type varchar(3) references rst.recreation_resource_type_code(rec_resource_type_code),
    amend_status_date           date,
    retirement_date             date,
    revision_count              integer,
    recreation_map_feature_guid varchar(36),
    unique (rec_resource_id, section_id)
);


select upsert_timestamp_columns('rst', 'recreation_map_feature');

select setup_temporal_table('rst', 'recreation_map_feature');

create index idx_recreation_map_feature_rmf_skey on rst.recreation_map_feature(rmf_skey);
create index idx_recreation_map_feature_rec_resource_id on rst.recreation_map_feature(rec_resource_id);
create index idx_recreation_map_feature_recreation_resource_type on rst.recreation_map_feature(recreation_resource_type);

create table rst.recreation_map_feature_geom
(
    rmf_skey           integer primary key references rst.recreation_map_feature,
    map_feature_id     int,
    geometry_type_code varchar(3),
    geometry           geometry,
    feature_area       numeric(11, 4),
    feature_length     numeric(11, 4),
    feature_perimeter  numeric(11, 4),
    revision_count     integer,
    unique (map_feature_id)
);

select upsert_timestamp_columns('rst', 'recreation_map_feature_geom');

select setup_temporal_table('rst', 'recreation_map_feature_geom');

create index idx_recreation_map_feature_geom_map_feature_id on rst.recreation_map_feature_geom(map_feature_id);


comment on table rst.recreation_map_feature is 'Captures both current and historical attributes for Recreation Map Features.';

comment on column rst.recreation_map_feature.rmf_skey is 'The SKEY for the RECREATION MAP FEATURE.';

comment on column rst.recreation_map_feature.rec_resource_id is 'File identification assigned to Provincial Forest Use files. Assigned file number. Usually the Licence, Tenure or Private Mark number.';

comment on column rst.recreation_map_feature.section_id is 'The section id for the RECREATION MAP FEATURE.';

comment on column rst.recreation_map_feature.amendment_id is 'The amendment id for the RECREATION MAP FEATURE.';

comment on column rst.recreation_map_feature.amend_status_code is 'Code to indicate status of amendment, that is, pending, approved or disallowed. This references Timber_Status_Code.';

comment on column rst.recreation_map_feature.recreation_resource_type is 'Identifies the RECREATION MAP FEATURE TYPE CODE.';

comment on column rst.recreation_map_feature.amend_status_date is 'The date the amendment status was changed.';

comment on column rst.recreation_map_feature.retirement_date is 'The date the entry is retired.';

comment on column rst.recreation_map_feature.revision_count is 'A count of the number of times an entry in the entity has been modified. Used to validate if the current information displayed on a user''s web browser is the most current.';

comment on column rst.recreation_map_feature.created_by is 'The userid responsible for inserting data into a table.';

comment on column rst.recreation_map_feature.created_at is 'Contains the system timestamp when data in a table was inserted.';

comment on column rst.recreation_map_feature.updated_by is 'The userid of the individual who last updated this road section record.';

comment on column rst.recreation_map_feature.updated_at is 'The timestamp of the last update to the road section record.';

comment on column rst.recreation_map_feature.recreation_map_feature_guid is 'Global Unique Identifier generated by the system for new records. It was added for FTA 5.';

comment on table rst.recreation_map_feature_geom is 'Captures amendments to spatial geometry for recreation applications received via the electronic submission process.';

comment on column rst.recreation_map_feature_geom.rmf_skey is 'The SKEY for the RECREATION MAP FEATURE.';

comment on column rst.recreation_map_feature_geom.map_feature_id is 'A unique identifier to a version of a map object. This is very similar to the feature ID in INCOSADA except it was universally unique. If a new version of a cut block came in it would be assigned a new identifier.';

comment on column rst.recreation_map_feature_geom.geometry_type_code is 'Identifies linear or polygonal geometry types for a tenure application feature.';

comment on column rst.recreation_map_feature_geom.geometry is 'The geometry for this feature.';

comment on column rst.recreation_map_feature_geom.feature_area is 'Spatial feature area in hectares. This value is calculated.';

comment on column rst.recreation_map_feature_geom.feature_length is 'Spatial feature length in kilometres. This value is calculated.';

comment on column rst.recreation_map_feature_geom.feature_perimeter is 'Spatial feature perimeter in kilometres. This value is calculated.';

comment on column rst.recreation_map_feature_geom.revision_count is 'A count of the number of times an entry in the entity has been modified. Used to validate if the current information displayed on a user''s web browser is the most current.';

comment on column rst.recreation_map_feature_geom.created_by is 'The userid responsible for inserting data into a table.';

comment on column rst.recreation_map_feature_geom.created_at is 'Contains the system timestamp when data in a table was inserted.';

comment on column rst.recreation_map_feature_geom.updated_by is 'The userid of the individual who last updated this road section record.';

comment on column rst.recreation_map_feature_geom.updated_at is 'The timestamp of the last update to the road section record.';
