create table rst.recreation_asset_code
(
    asset_code  serial primary key,
    description varchar(120)
);

comment on table  rst.recreation_asset_code is 'Codes describing the classification type of an individual recreation asset (e.g. Campsite, Table, Toilet). Not FTA-synced; managed internally.';
comment on column rst.recreation_asset_code.asset_code  is 'Surrogate primary key for the asset type code.';
comment on column rst.recreation_asset_code.description is 'Description of the asset type.';

insert into rst.recreation_asset_code (description)
values
    ('Table - log'),
    ('Table - wheelchair accessible'),
    ('Toilet - wood'),
    ('Toilet - wheelchair accessible'),
    ('Fire ring'),
    ('Litter barrel - 45 gallon'),
    ('Barrel shelters'),
    ('Parking - unimproved'),
    ('Parking - unsurfaced'),
    ('Parking - spaces gravel'),
    ('Parking - spaces pavement'),
    ('Parking - wheelchair accessible'),
    ('Registration post'),
    ('Boat launch - cartop (unimproved)'),
    ('Boat launch - unimproved'),
    ('Boat launch - gravel'),
    ('Boat launch - concrete'),
    ('Safety barrier'),
    ('Signs'),
    ('Sign - stop'),
    ('Sign - directional (facility)'),
    ('Entrance kiosk'),
    ('Sign shelter'),
    ('Shelter (cabins, warming huts)'),
    ('Shelter - wheelchair accessible'),
    ('Traffic counter'),
    ('Dock wharf'),
    ('Dock wharf - wheelchair accessible'),
    ('Bench'),
    ('Boardwalk'),
    ('Bridge - foot (>6M)'),
    ('Bridge - foot (<6M)'),
    ('Bridge - wheelchair accessible'),
    ('Corral - firewood'),
    ('Corral - firewood - wheelchair accessible'),
    ('Corral - horse'),
    ('Hitching rail'),
    ('Observation tower'),
    ('Viewing platform'),
    ('Viewing blinds'),
    ('Trail'),
    ('Trail - wheelchair accessible'),
    ('Tent pad'),
    ('Vehicle space'),
    ('Total length of associated roads'),
    ('Dock pier'),
    ('Dock floating'),
    ('Table - concrete'),
    ('Table - metal'),
    ('Toilet - metal'),
    ('Toilet - concrete'),
    ('Toilet - solar composting'),
    ('Litter barrel - bear proof single'),
    ('Litter barrel - bear proof double'),
    ('Gate'),
    ('In-site road'),
    ('Culvert'),
    ('Fencing - russell'),
    ('Stairs'),
    ('Pools and tubs - hotsprings'),
    ('Fish cleaning station'),
    ('Bridge - vehicle'),
    ('Bridge - foot (suspension)'),
    ('Cable car'),
    ('Helipad'),
    ('Log boom'),
    ('Bear cache'),
    ('Fencing - barb wire'),
    ('Fencing - log'),
    ('Fencing - chain link'),
    ('Sign shelter - small'),
    ('Sign shelter - large'),
    ('Sign - 3 blade'),
    ('Sign - highway'),
    ('Barrier - no post'),
    ('Barrier - lock block'),
    ('Gate - single'),
    ('Mooring buoy'),
    ('Registration box'),
    ('Barrier - rock'),
    ('Fencing - strand'),
    ('Gate - double'),
    ('Barrier - wood'),
    ('Bridge - foot'),
    ('Campsite');

select upsert_timestamp_columns('rst', 'recreation_asset_code');

select setup_temporal_table('rst', 'recreation_asset_code', false);
