name: Build Containers

on:
  workflow_call:

permissions:
  attestations: write
  id-token: write
  packages: write

jobs:
  # https://github.com/bcgov/action-builder-ghcr
  build-containers:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # Only building frontend containers to run PR based e2e tests
        package: ['admin/backend', 'admin/frontend', 'migrations/rst', 'migrations/fta', 'public/backend', 'public/frontend']
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@v4.0.0
        with:
          package: ${{ matrix.package }}
          tags: ${{ github.sha }}
