name: Build Containers

on:
  workflow_call:

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  security-events: write
  attestations: write

jobs:
  # https://github.com/bcgov/action-builder-ghcr
  build-containers:
    name: Builds
    runs-on: ubuntu-24.04
    environment: dev

    strategy:
      matrix:
        include:
          - package: 'admin/frontend'
            build_context: '.'
          - package: 'public/frontend'
            build_context: '.'
          - package: 'admin/backend'
            build_context: 'admin/backend'
          - package: 'public/backend'
            build_context: 'public/backend'
          - package: 'migrations/rst'
            build_context: 'migrations/rst'
          - package: 'migrations/fta'
            build_context: 'migrations/fta'

    timeout-minutes: 10
    steps:
    - uses: bcgov/action-builder-ghcr@v4.1.0
      with:
        package: ${{ matrix.package }}
        tags: ${{ github.sha }}
        build_context: ${{ matrix.build_context }}
        build_file: ${{ matrix.package }}/Dockerfile
        sbom: 'false'
        build_args: |
          VITE_KEYCLOAK_AUTH_SERVER_URL=${{ secrets.KEYCLOAK_AUTH_SERVER_URL }}
          VITE_KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }}
          VITE_KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }}
