name: Build Containers

on:
  workflow_call:

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  build-containers:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # Only building frontend containers to run PR based e2e tests
        package: ['admin/backend', 'admin/frontend', 'migrations/rst', 'migrations/fta', 'public/backend', 'public/frontend']
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@d63c76a4bb7914d3a986a035904b49d99c2c4613 # v3.0.0
        with:
          package: ${{ matrix.package }}
          tags: ${{ github.sha }}
