name: Build Containers

on:
  workflow_call:

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  build-containers:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, 'migrations/rst', 'migrations/fta', frontend]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.3.0
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.sha }}
