name: Build Containers

on:
  workflow_call:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write
  security-events: write
  attestations: write # This is required for uploading attestations to the Security tab

jobs:
  # https://github.com/bcgov/action-builder-ghcr
  build-containers:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # Only building frontend containers to run PR based e2e tests
        package: ['admin/backend', 'admin/frontend', 'migrations/rst', 'migrations/fta', 'public/backend', 'public/frontend']
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@v4.0.0
        with:
          package: ${{ matrix.package }}
          tags: ${{ github.sha }}
