name: Deploy application to AWS

on:
  workflow_call:
    inputs:
      app_env:
        required: true
        description: 'The APP env separates between AWS ENV and Actual APP, since AWS dev is where PR, and TEST is deployed'
        type: string
      command:
        required: true
        description: 'The Terraform command to run'
        type: string
      environment_name:
        description: 'The name of the environment to deploy to'
        required: true
        type: string
      tag:
        description: 'The tag of the containers to deploy'
        required: true
        type: string

env:
  AWS_REGION: ca-central-1

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write

jobs:
  # https://github.com/bcgov/quickstart-openshift-helpers
  deploy-db:
    name: Deploys Database
    uses: ./.github/workflows/.aws-deployer.yml
    with:
      app_env: ${{ inputs.app_env }}
      environment_name: ${{ inputs.environment_name }}
      command: ${{ inputs.command }}
      working_directory: database
    secrets: inherit
  deploy-api:
    name: Deploys API
    needs: [deploy-db]
    uses: ./.github/workflows/.aws-deployer.yml
    with:
      environment_name: ${{ inputs.environment_name }}
      command: ${{ inputs.command }}
      working_directory: api
      tag: ${{ inputs.tag }}
      app_env: ${{ inputs.app_env }}
    secrets: inherit