name: Playwright Tests

on:
  workflow_call:
    inputs:
      tag:
        description: 'The tag of the containers to run tests on'
        required: true
        type: string

jobs:
  playwright-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Run Docker compose
      env:
        BACKEND_IMAGE: ghcr.io/bcgov/nr-rec-resources/backend:${{ inputs.tag }}
        FLYWAY_IMAGE: ghcr.io/bcgov/nr-rec-resources/migrations:${{ inputs.tag }}
        FRONTEND_IMAGE: ghcr.io/bcgov/nr-rec-resources/frontend:${{ inputs.tag }}
      run: docker compose up -d --wait
      continue-on-error: true
    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
    - name: Fix permissions
      run: sudo chown -R $USER:$USER frontend
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm ci
      working-directory: ./frontend
    - run: npx @playwright/test install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      working-directory: ./frontend
    - run: npx @playwright/test install-deps
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      working-directory: ./frontend
    - name: Run Playwright tests
      run: npx happo-e2e -- npx playwright test
      working-directory: ./frontend
      env:
        HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
        HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
        HAPPO_PROJECT: rst-public
