name: Playwright e2e tests

on:
  workflow_call:
    inputs:
      app:
        description: 'The app to run tests on'
        required: true
        type: string
      environment:
        description: 'The GitHub environment to run the tests in'
        required: false
        type: string
      tag:
        description: 'The tag of the containers to run tests on'
        required: true
        type: string
      local:
        description: 'Run locally using docker compose'
        required: false
        type: boolean
        default: false

jobs:
  playwright-e2e:
    # Remove this once admin e2e tests are implemented
    if: ${{ inputs.app == 'public' }}
    name: Playwright e2e
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4
    - name: Run Docker compose
      if: ${{ inputs.local }}
      env:
        BACKEND_IMAGE: ghcr.io/bcgov/nr-rec-resources/public/backend:${{ inputs.tag }}
        FLYWAY_IMAGE: ghcr.io/bcgov/nr-rec-resources/migrations/rst:${{ inputs.tag }}
        FRONTEND_IMAGE: ghcr.io/bcgov/nr-rec-resources/public/frontend:${{ inputs.tag }}
      run: docker compose up -d --wait
      continue-on-error: true
    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
    - name: Fix permissions
      run: sudo chown -R $USER:$USER public/frontend
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: npm ci
      working-directory: ./${{ inputs.app }}/frontend
    - run: npx @playwright/test install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      working-directory: ./${{ inputs.app }}/frontend
    - run: npx @playwright/test install-deps
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      working-directory: ./${{ inputs.app }}/frontend
    - name: Run Playwright tests
      run: npx happo-e2e -- npx playwright test
      working-directory: ./${{ inputs.app }}/frontend
      env:
        HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
        HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
        HAPPO_PROJECT: ${{ secrets.HAPPO_PROJECT }}
        E2E_BASE_URL: ${{ inputs.local && 'http://localhost:3000' || secrets.E2E_BASE_URL }}
    - name: Dump docker logs on failure
      if: failure() && ${{ inputs.local }}
      uses: jwalton/gh-docker-logs@v2

  # Remove this job once admin e2e tests are implemented
  admin:
    if: ${{ inputs.app == 'admin' }}
    name: Skip Playwright e2e
    runs-on: ubuntu-24.04
    steps:
    - name: Skip Playwright e2e
      run: echo "Skipping Playwright e2e tests for admin app"
