name: Promote

on:
  workflow_call:
    inputs:
      app:
        description: "The app to promote"
        type: string
        required: true
      tag:
        description: "Manually provide the tag of the containers to promote"
        type: number
        required: true

jobs:
  promote:
    name: Promote Images
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: ['${{ inputs.app }}/backend', '${{ inputs.app }}/frontend', 'migrations/rst', 'migrations/fta']
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ github.sha }}
          tags: |
            latest
            ${{ inputs.tag && inputs.tag || github.sha }}
