name: Make Release

on:
  workflow_call:
    inputs:
      app:
        description: Application name
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v6
        id: changelog
        continue-on-error: true
        with:
          github-token: ${{ github.token }}
          output-file: "CHANGELOG.md"
          skip-version-file: true
          skip-commit: true
          git-push: ${{ github.ref_name == 'main' }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.tag != '' }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          token: ${{ github.token }}
          tag_name: ${{ inputs.app }}-${{ steps.changelog.outputs.tag }}
          name: ${{ inputs.app }} ${{ steps.changelog.outputs.tag }}
          body: |
            ## ${{ inputs.app }} Release ${{ steps.changelog.outputs.tag }}

            ${{ steps.changelog.outputs.clean_changelog }}
