name: Make Release

on:
  workflow_call:
    inputs:
      app:
        description: Application name
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    concurrency:
      group: release-${{ inputs.app }}
      cancel-in-progress: false
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - name: Debug - Check recent commits
        run: |
          echo "Recent commits:"
          git log --oneline -10
          echo "Current branch:"
          git branch
          echo "Checking for existing tags:"
          git tag --sort=-version:refname | head -5
          echo "Checking for existing releases:"
          git log --grep="chore:" --oneline -5
      - name: Initialize version file
        run: |
          if [ ! -f "VERSION.txt" ]; then
            echo "0.0.0" > VERSION.txt
            git add VERSION.txt
            git commit -m "chore: initialize version file" || true
          fi
      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v6
        id: changelog
        continue-on-error: true
        with:
          github-token: ${{ github.token }}
          output-file: "CHANGELOG.md"
          version-file: "VERSION.txt"
          skip-commit: "true"
          git-push: "true"
      - name: Debug - Check changelog outputs
        run: |
          echo "Changelog tag: '${{ steps.changelog.outputs.tag }}'"
          echo "Changelog clean_changelog: '${{ steps.changelog.outputs.clean_changelog }}'"
          echo "Changelog new_version: '${{ steps.changelog.outputs.new_version }}'"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.tag != '' }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          token: ${{ github.token }}
          tag_name: ${{ inputs.app }}-${{ steps.changelog.outputs.tag }}
          name: ${{ inputs.app }} ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
      - name: Debug - No release created
        if: ${{ steps.changelog.outputs.tag == '' }}
        run: |
          echo "No release was created because no conventional commits were found"
          echo "Make sure your commits follow conventional commit format:"
          echo "  feat: add new feature"
          echo "  fix: bug fix"
          echo "  chore: maintenance"
          echo "  docs: documentation"
          echo "  style: formatting"
          echo "  refactor: code refactoring"
          echo "  test: adding tests"
