name: Review and deploy

on:
  workflow_call:
    app:
      description: Application name
      required: true
      type: string
    inputs:
      tag:
        required: true
        type: string
    secrets:
      inherit: true

jobs:
  deploy-to-aws-dev:
    name: Deploy Application to AWS dev
    uses: ./.github/workflows/.deploy-app.yml
    with:
      app_env: dev
      command: apply
      environment_name: dev
      tag: ${{ inputs.tag }}
    secrets: inherit

  tests-e2e-dev-environment:
    name: Run e2e tests on dev env
    needs: deploy-to-aws-dev
    uses: ./.github/workflows/.e2e.yml
    with:
      tag: ${{ inputs.tag }}
      environment: dev
    secrets: inherit

  # Separate review job since we can't use GitHub environments in reusable workflows
  review-test-deployment:
    name: Review Test Deployment
    needs: tests-e2e-dev-environment
    runs-on: ubuntu-24.04
    concurrency:
      group: review-test-deployment-${{ github.ref }}
      cancel-in-progress: true
    environment: review-test-deployment
    steps:
      - name: Review Test Deployment
        run: echo "Reviewing Test Deployment"

  # Deploys to test environment in the same AWS account as dev.
  # resources in test environment uses the same vpc as the dev (Dev_vpc)
  deploy-to-aws-test:
    name: Deploy Application to AWS test
    needs: review-test-deployment
    uses: ./.github/workflows/.deploy-app.yml
    with:
      app_env: test
      command: apply
      environment_name: test
      tag: ${{ inputs.tag }}
    secrets: inherit

  tests-e2e-test-environment:
    name: Run e2e tests on test env
    needs: deploy-to-aws-test
    uses: ./.github/workflows/.e2e.yml
    with:
      tag: ${{ inputs.tag }}
      environment: test
    secrets: inherit

  # release:
  #   name: Release
  #   needs: tests-e2e-test-environment
  #   uses: ./.github/workflows/.release.yml

  # only promote specific app images?
  # promote:
  #   name: Promote
  #   needs: release
  #   uses: ./.github/workflows/.promote.yml

  # Separate review job since we can't use GitHub environments in reusable workflows
  review-prod-deployment:
    name: Review Prod Deployment
    needs: promote
    runs-on: ubuntu-24.04
    concurrency:
      group: review-prod-deployment-${{ github.ref }}
      cancel-in-progress: true
    environment: review-prod-deployment
    steps:
      - name: Review Prod Deployment
        run: echo "Reviewing Prod Deployment"

  deploy-to-aws-prod:
    name: Deploy Application to AWS prod
    needs: review-prod-deployment
    uses: ./.github/workflows/.deploy-app.yml
    with:
      app_env: prod
      command: apply
      environment_name: prod
      tag: ${{ inputs.tag }}
    secrets: inherit
