name: Review and deploy

on:
  workflow_call:
    inputs:
      app:
        description: Application name
        required: true
        type: string
      tag:
        description: The tag of the containers to deploy
        required: true
        type: string

jobs:
  deploy-to-aws-dev:
    name: Deploy Application to AWS dev
    uses: ./.github/workflows/.deploy-app.yml
    concurrency:
      group: deploy-${{ inputs.app }}-to-aws-dev
      cancel-in-progress: false
    with:
      app: ${{ inputs.app }}
      app_env: dev
      command: apply
      environment_name: dev
      tag: ${{ inputs.tag }}
    secrets: inherit

  tests-e2e-dev-environment:
    name: Run e2e tests on dev env
    needs: deploy-to-aws-dev
    if: ${{ inputs.app != 'admin' }}
    uses: ./.github/workflows/.e2e.yml
    concurrency:
      group: e2e-tests-${{ inputs.app }}-dev
      cancel-in-progress: false
    with:
      app: ${{ inputs.app }}
      tag: ${{ inputs.tag }}
      environment: dev
    secrets: inherit

  # TODO: Remove this job once admin e2e tests are set up for deployed environments.
  tests-e2e-dev-skip:
    if: ${{ inputs.app == 'admin' }}
    name: Skip Playwright e2e (admin deployed - dev)
    needs: deploy-to-aws-dev
    runs-on: ubuntu-24.04
    steps:
      - name: Skip
        run: echo "Skipping admin e2e tests for deployed environment - to be removed once admin e2e tests are set up for deployed environments."

  # Separate review job since we can't use GitHub environments in reusable workflows
  review-test-deployment:
    name: Review ${{ inputs.app }} test deployment
    needs: [deploy-to-aws-dev, tests-e2e-dev-environment, tests-e2e-dev-skip]
    if: ${{ always() && needs.deploy-to-aws-dev.result == 'success' && (needs.tests-e2e-dev-skip.result == 'success' || needs.tests-e2e-dev-environment.result == 'success') }}
    runs-on: ubuntu-24.04
    environment: review-${{ inputs.app}}-test-deployment
    steps:
      - name: Review Test Deployment
        run: echo "Reviewing Test Deployment"

  # Deploys to test environment in the same AWS account as dev.
  deploy-to-aws-test:
    name: Deploy Application to AWS test
    needs: review-test-deployment
    if: ${{ always() && needs.review-test-deployment.result == 'success' }}
    uses: ./.github/workflows/.deploy-app.yml
    concurrency:
      group: deploy-${{ inputs.app }}-to-aws-test
      cancel-in-progress: false
    with:
      app: ${{ inputs.app }}
      app_env: test
      command: apply
      environment_name: test
      tag: ${{ inputs.tag }}
    secrets: inherit

  tests-e2e-test-environment:
    name: Run e2e tests on test env
    needs: deploy-to-aws-test
    if: ${{ inputs.app != 'admin' }}
    uses: ./.github/workflows/.e2e.yml
    concurrency:
      group: e2e-tests-${{ inputs.app }}-test
      cancel-in-progress: true
    with:
      app: ${{ inputs.app }}
      tag: ${{ inputs.tag }}
      environment: test
    secrets: inherit

  # TODO: Remove this job once admin e2e tests are set up for deployed environments.
  tests-e2e-test-skip:
    if: ${{ inputs.app == 'admin' }}
    name: Skip Playwright e2e (admin deployed - test)
    needs: deploy-to-aws-test
    runs-on: ubuntu-24.04
    steps:
      - name: Skip
        run: echo "Skipping admin e2e tests for deployed environment - to be removed once admin e2e tests are set up for deployed environments."

  # Separate review job since we can't use GitHub environments in reusable workflows
  review-prod-deployment:
    name: Review ${{ inputs.app }} prod deployment
    needs: [deploy-to-aws-test, tests-e2e-test-environment, tests-e2e-test-skip]
    if: ${{ always() && needs.deploy-to-aws-test.result == 'success' && (needs.tests-e2e-test-skip.result == 'success' || needs.tests-e2e-test-environment.result == 'success') }}
    runs-on: ubuntu-24.04
    environment: review-${{inputs.app}}-prod-deployment
    steps:
      - name: Review Prod Deployment
        run: echo "Reviewing Prod Deployment"

  promote:
    name: Promote
    needs: review-prod-deployment
    if: ${{ always() && needs.review-prod-deployment.result == 'success' }}
    uses: ./.github/workflows/.promote.yml
    with:
      app: ${{ inputs.app }}
      tag: ${{ inputs.tag }}

  deploy-to-aws-prod:
    name: Deploy Application to AWS prod
    needs: review-prod-deployment
    if: ${{ always() && needs.review-prod-deployment.result == 'success' }}
    uses: ./.github/workflows/.deploy-app.yml
    concurrency:
      group: deploy-${{ inputs.app }}-to-aws-prod
      cancel-in-progress: false
    with:
      app: ${{ inputs.app }}
      app_env: prod
      command: apply
      environment_name: prod
      tag: ${{ inputs.tag }}
    secrets: inherit
