name: Test shared code
# We may want to add SonarCloud analysis here in the future

on:
  workflow_call:

jobs:
  test-shared:
    name: Run shared tests
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./shared
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run shared tests
        run: npm run test
