name: Deploy AWS

on:
  pull_request:

env:
  FRONTEND_BUCKET: frontend
  STACK_NAME: rst-dev



permissions:
  id-token: write # This is required for GitHub OIDC auth with AWS
  contents: read # This is required for actions/checkout

jobs:
  deploy-infrastructure-to-aws:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Provision infrastructure with AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.STACK_NAME }}
          no-fail-on-empty-changeset: "1"
          template: ./infrastructure/deploy.yml

      # Build frontend and deploy to s3 - maybe split this out into a separate workflow and call from here
      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./frontend

      - name: Build project
        working-directory: ./frontend
        run: npm run build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync .frontend/dist s3://$FRONTEND_BUCKET --delete
