name: Playwright Tests

on:
  workflow_call:

jobs:
  playwright-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run local app
      uses: ./.github/actions/run-local-app
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./frontend
    - name: Run Playwright tests
      run: npm run playwright test
      working-directory: ./frontend
