name: Playwright Tests

on:
  workflow_call:

jobs:
  playwright-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run local app
      uses: ./.github/actions/run-local-app
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm ci
      working-directory: ./frontend
    - run: npx playwright install --with-deps
      working-directory: ./frontend
    - name: Run Playwright tests
      run: npm run e2e
      working-directory: ./frontend
