name: FTA Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to AWS'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

env:
  AWS_REGION: ca-central-1

permissions:
  id-token: write # for AWS OIDC
  contents: read
  packages: write

jobs:
  fta-migration:
    name: FTA migration (${{ github.event.inputs.environment }})
    uses: ./.github/workflows/.aws-deployer.yml
    concurrency:
      group: deploy-fta-migration-${{ inputs.environment_name }}
      cancel-in-progress: false
    with:
      app: public
      app_env: ${{ github.event.inputs.environment }}
      environment_name: ${{ github.event.inputs.environment }}
      command: apply
      flyway_image: ghcr.io/bcgov/nr-rec-resources/migrations/fta:latest
      working_directory: migration
      tag: latest
    secrets: inherit
