name: FTA Migration

on:
  schedule: [cron: "0 11 * * *"] # 11 AM UTC = 3 AM PST
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the containers to deploy'
        required: false
        type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write

jobs:
  run-fta-migration:
    strategy:
      matrix:
        environment: [test, prod]
    name: Run FTA ${{ matrix.environment }} Migration
    uses: ./.github/workflows/.aws-deployer.yml
    with:
      app: public
      app_env: ${{ matrix.environment }}
      environment_name: ${{ matrix.environment }}
      command: apply
      flyway_image: ghcr.io/bcgov/nr-rec-resources/migrations/fta:${{ inputs.tag || 'latest' }}
      working_directory: migration
      tag: ${{ inputs.tag || 'latest' }}
    secrets: inherit
