name: FTA Migration

on:
  # Will schedule this to run on test/prod in the future
  # schedule: [cron: "0 3 * * *"] # Every day at 3 AM
  workflow_call:
    inputs:
      app_env:
        required: true
        description: 'The APP env separates between AWS ENV and Actual APP, since AWS dev is where PR, and TEST is deployed'
        type: string
      environment_name:
        description: 'The name of the environment to deploy to'
        required: true
        type: string
      tag:
        description: 'The tag of the containers to deploy'
        required: true
        type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write

jobs:
  run-fta-migration:
    name: Run FTA ${{ inputs.app_env }} Migration
    uses: ./.github/workflows/.aws-deployer.yml
    with:
      app_env: ${{ inputs.app_env || 'dev' }}
      environment_name: ${{ inputs.environment_name || 'dev' }}
      command: apply
      flyway_image: ghcr.io/bcgov/nr-rec-resources/migrations/fta:${{ inputs.tag || 'latest' }}
      working_directory: migration
      tag: ${{ inputs.tag }}
    secrets: inherit
