name: Scheduled FTA Migration

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour on the hour
  workflow_dispatch:

env:
  AWS_REGION: ca-central-1

permissions:
  id-token: write # for AWS OIDC
  contents: read
  packages: write

jobs:
  fta-migration-dev:
    name: FTA migration dev
    uses: ./.github/workflows/.aws-deployer.yml
    concurrency:
      group: scheduled-fta-migration-dev
      cancel-in-progress: false
    with:
      app: public
      app_env: dev
      environment_name: dev
      command: apply
      flyway_image: ghcr.io/bcgov/nr-rec-resources/migrations/fta:latest
      working_directory: migration
      tag: latest
    secrets: inherit
  fta-migration-prod:
    name: FTA migration prod
    uses: ./.github/workflows/.aws-deployer.yml
    concurrency:
      group: scheduled-fta-migration-prod
      cancel-in-progress: false
    with:
      app: public
      app_env: prod
      environment_name: prod
      command: apply
      flyway_image: ghcr.io/bcgov/nr-rec-resources/migrations/fta:latest
      working_directory: migration
      tag: latest
    secrets: inherit
