# This is the main workflow which will orchestrate the other workflows:

name: main

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/.build-containers.yml
  analysis:
    uses: ./.github/workflows/.analysis.yml
    secrets: inherit
  tests-e2e:
    name: Tests
    needs: build
    uses: ./.github/workflows/.e2e.yml
    with:
      tag: ${{ github.sha }}
    secrets: inherit
  deploy-to-aws-dev:
    if: github.ref == 'refs/heads/main'
    needs: [build, tests-e2e]
    name: Deploys Application to AWS dev
    uses: ./.github/workflows/.deploy-app.yml
    with:
      app_env: dev
      command: apply
      environment_name: dev
      tag: ${{ github.sha }}
    secrets: inherit
  promote:
    needs: [deploy-to-aws-dev]
    uses: ./.github/workflows/.promote.yml
