# This is the main workflow which will orchestrate the other workflows:

name: main

on:
  push:
    branches: [main]
    paths-ignore:
      - docs/**
  pull_request:
    paths-ignore:
      - docs/**


jobs:
  build-containers:
    name: Build containers
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-containers
      cancel-in-progress: true
    uses: ./.github/workflows/.build.yml

  repo-analysis:
    name: Repository analysis
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-analysis
      cancel-in-progress: true
    uses: ./.github/workflows/.analysis.yml
    secrets: inherit

  analysis-results:
    name: Analysis Results
    needs: [repo-analysis]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"

  # test-admin:
  #   name: Run tests for admin app
  #   needs: build-containers
  #   concurrency:
  #     group: ${{ github.workflow }}-${{ github.ref }}-tests-public-app
  #     cancel-in-progress: true
  #   uses: ./.github/workflows/.tests.yml
  #   with:
  #     app: admin
  #   secrets: inherit

  test-public:
    name: Run tests for public app
    needs: build-containers
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-tests-public-app
      cancel-in-progress: true
    uses: ./.github/workflows/.tests.yml
    with:
      app: public
    secrets: inherit

  # review-and-deploy-admin:
  #   name: Review and Deploy Pipeline
  #   needs: test-admin
  #   uses: ./.github/workflows/.review-and-deploy.yml
  #   with:
  #     app: admin
  #     tag: ${{ github.sha }}
  #   secrets: inherit

  review-and-deploy-public:
    if: github.ref_name == 'main' || github.head_ref == 'main'
    name: Review and Deploy Pipeline
    needs: test-public
    uses: ./.github/workflows/.review-and-deploy.yml
    with:
      app: public
      tag: ${{ github.sha }}
    secrets: inherit

  # review-and-deploy-admin:
  #   if: github.ref_name == 'main' || github.head_ref == 'main'
  #   name: Review and Deploy Pipeline
  #   needs: tests-e2e-local
  #   uses: ./.github/workflows/.review-and-deploy.yml
  #   with:
  #     app: public
  #     tag: ${{ github.sha }}
  #   secrets: inherit
