# This is the main workflow which will orchestrate the other workflows:

name: main

on:
  push:
    branches: [main]
    paths-ignore:
      - docs/**
  pull_request:
    paths-ignore:
      - docs/**


jobs:
  build-containers:
    name: Build containers
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-containers
      cancel-in-progress: true
    uses: ./.github/workflows/.build.yml

  analysis:
    name: Analysis
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-analysis
      cancel-in-progress: true
    uses: ./.github/workflows/.analysis.yml
    secrets: inherit

  analysis-results:
    name: Analysis Results
    needs: [analysis]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"

  tests-e2e-local:
    name: Run E2E tests locally
    needs: build-containers
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-e2e-local
      cancel-in-progress: true
    uses: ./.github/workflows/.e2e.yml
    with:
      tag: ${{ github.sha }}
      local: true
    secrets: inherit

  deploy-to-aws-dev:
    if: github.ref_name == 'main' || github.head_ref == 'main'
    name: Deploys Application to AWS dev
    needs: tests-e2e-local
    uses: ./.github/workflows/.deploy-app.yml
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-deploy-to-aws-dev
      cancel-in-progress: false
    with:
      app_env: dev
      command: apply
      environment_name: dev
      tag: ${{ github.sha }}
    secrets: inherit

  tests-e2e-dev-environment:
    name: Run e2e tests on dev env
    needs: build-containers
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-e2e-dev-environment
      cancel-in-progress: true
    uses: ./.github/workflows/.e2e.yml
    with:
      tag: ${{ github.sha }}
      environment: dev
    secrets: inherit

  # Separate review job since we can't use GitHub environments in reusable workflows
  review-test-deployment:
    name: Review Test Deployment
    needs: [tests-e2e-dev-environment]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-review-test-deployment
      cancel-in-progress: true
    environment: review-test-deployment
    runs-on: ubuntu-24.04
    steps:
      - name: Review Test Deployment
        run: echo "Reviewing Test Deployment"

  # Deploys to test environment in the same AWS account as dev.
  # resources in test environment uses the same vpc as the dev (Dev_vpc)
  deploy-to-aws-test:
    name: Deploys Application to AWS test
    needs: [review-test-deployment]
    uses: ./.github/workflows/.deploy-app.yml
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-deploy-to-aws-test
      cancel-in-progress: false
    with:
      app_env: test
      command: apply
      environment_name: test
      tag: ${{ github.sha }}
    secrets: inherit

  tests-e2e-test-environment:
    name: Run e2e tests on test env
    needs: build-containers
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-e2e-test-environment
      cancel-in-progress: true
    uses: ./.github/workflows/.e2e.yml
    with:
      tag: ${{ github.sha }}
      environment: test
    secrets: inherit

  release:
    name: Release
    needs: [deploy-to-aws-test]
    uses: ./.github/workflows/.release.yml

  promote:
    name: Promote
    needs: [release]
    uses: ./.github/workflows/.promote.yml

  # Separate review job since we can't use GitHub environments in reusable workflows
  review-prod-deployment:
    name: Review Prod Deployment
    needs: [promote]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-review-prod-deployment
      cancel-in-progress: true
    environment: review-prod-deployment
    runs-on: ubuntu-24.04
    steps:
      - name: Review Prod Deployment
        run: echo "Reviewing Prod Deployment"

  deploy-to-aws-prod:
    name: Deploys Application to AWS prod
    needs: [review-prod-deployment]
    uses: ./.github/workflows/.deploy-app.yml
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-deploy-to-aws-prod
      cancel-in-progress: false
    with:
      app_env: prod
      command: apply
      environment_name: prod
      tag: ${{ github.sha }}
    secrets: inherit
