# This is the main workflow which will orchestrate the other workflows:

name: main

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-containers:
    name: Build containers
    uses: ./.github/workflows/.build.yml

  analysis:
    name: Analysis
    uses: ./.github/workflows/.analysis.yml
    secrets: inherit

  analysis-results:
    name: Analysis Results
    needs: [analysis]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"

  tests-e2e:
    name: Tests
    needs: build-containers
    uses: ./.github/workflows/.e2e.yml
    with:
      tag: ${{ github.sha }}
    secrets: inherit

  deploy:
    name: Deploy
    needs: [tests-e2e]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
