# This is the main workflow which will orchestrate the other workflows:

name: main

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build-containers:
    name: Build containers
    uses: ./.github/workflows/.build.yml

  deploy-to-aws-test:
    name: Deploys Application to AWS test
    needs: [ build-containers ]
    uses: ./.github/workflows/.deploy-app.yml
    with:
      app_env: test
      command: apply
      environment_name: dev
      tag: ${{ github.sha }}
      vpc_target_env: dev # same vpc as dev environment since using the same aws account
    secrets: inherit

  # Running FTA migration after each dev deployment since we are clearing the database each run
  fta-migration:
    needs: build-containers
    name: FTA Migration
    uses: ./.github/workflows/fta-migration.yml
    with:
      app_env: test
      environment_name: test
      vpc_target_env: dev
      tag: ${{ github.sha }}
    secrets: inherit
