name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '!.github/workflows/**'
  workflow_dispatch:
    inputs:
      pr_no:
        description: "PR-numbered container set to deploy"
        type: number
        required: true

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr || github.event.inputs.pr_no }}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: pr
        uses: bcgov-nr/action-get-pr@v0.0.1

  deploy-to-aws-dev:
    needs: [vars]
    name: Deploys Application to AWS dev
    uses: ./.github/workflows/.deploy-app.yml
    with:
      environment_name: dev
      app_env: dev
      tag: ${{ needs.vars.outputs.pr }}
    secrets: inherit

  promote:
    name: Promote Images
    needs: [deploy-to-aws-dev, vars]
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        # Only building frontend for e2e testing
        package: [migrations, backend, frontend]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.vars.outputs.pr }}
          tags: |
            prod
            latest
            ${{ needs.vars.outputs.pr }}
