name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '!.github/workflows/**'
  workflow_dispatch:
    inputs:
      pr_no:
        description: "PR-numbered container set to deploy"
        type: number
        required: true

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr || github.event.inputs.pr_no }}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: pr
        uses: bcgov-nr/action-get-pr@v0.0.1

  deploy-to-aws-dev:
    needs: [vars]
    name: Deploys Application to AWS dev
    uses: ./.github/workflows/.deploy-app.yml
    with:
      app_env: dev
      command: apply
      environment_name: dev
      tag: ${{ needs.vars.outputs.pr }}
    secrets: inherit

  # Separate review job since we can't use GitHub environments in reusable workflows
  review-test-deployment:
    name: Review Test Deployment
    needs: [deploy-to-aws-dev]
    environment: test
    runs-on: ubuntu-24.04
    steps:
      - name: Review Test Deployment
        run: echo "Reviewing Test Deployment"

  deploy-to-aws-test:
    needs: [review-test-deployment]
    name: Deploys Application to AWS test
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to AWS test
        # Placeholder
        run: echo "Deploying to AWS test"

  release:
    name: Release
    needs: [deploy-to-aws-test]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v5
        id: changelog
        continue-on-error: true
        with:
          github-token: ${{ github.token }}
          output-file: "CHANGELOG.md"
          skip-version-file: "true"
          skip-commit: "true"
          git-push: "true"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.tag != '' }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  promote:
    name: Promote Images
    needs: [deploy-to-aws-test, vars]
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        # Only building frontend for e2e testing
        package: [migrations, backend, frontend]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.vars.outputs.pr }}
          tags: |
            prod
            latest
            ${{ needs.vars.outputs.pr }}

  # Separate review job since we can't use GitHub environments in reusable workflows
  review-prod-deployment:
    name: Review Prod Deployment
    needs: [promote]
    environment: prod
    runs-on: ubuntu-24.04
    steps:
      - name: Review Prod Deployment
        run: echo "Reviewing Prod Deployment"

  deploy-to-aws-prod:
    needs: [deploy-to-aws-test]
    name: Deploys Application to AWS prod
    environment: prod
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to AWS prod
        # Placeholder
        run: echo "Deploying to AWS prod"
